### ISSUE TITLE
Many HystrixTimer-Threads

### ISSUE THREAD

**Issue by tine2k** [Netflix/Hystrix#1030]
I am using Hystrix on a heavy machine with many cores in a virtualized environment. My problem is that Hystrix creates 128 HystrixTimer-Threads, which I do not require. For my use case a couple of threads would be sufficient.
The cause of this seems to be in **com.netflix.hystrix.util.HystrixTimer**, which uses **Runtime.getRuntime().availableProcessors()**. In my case, this returns 128. I have not found an easy way to configure/override this.
Could we configure this via system property and default to Runtime.getRuntime().availableProcessors()?

**Comment by tine2k** [comment]
Created a pull request with a fix for this: #1032

**Comment by mattrjacobs** [comment]
Closing this issue now that #1032 is merged and in 1.4.23.  I'm going to do some performance testing with varying timer threads in Netflix production.  If I come up with a better default than numProcessors, I'll open a new issue.  If anyone in the community has a good idea for a default to use, I'd love to hear it.
