### ISSUE TITLE
Roadmap/direction of hystrix-dashboard

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#1033]
Internally at Netflix, we've stopped using the Hystrix dashboard.  We've been using other visualization approaches, as described here: http://techblog.netflix.com/2014/01/improving-netflixs-operational.html.

We recognize that the dashboard is still relied on by many organizations and individuals, so we'd like to see it continue.  However, it doesn't make sense for me personally, or Netflix as a whole, to be driving its development anymore.

My current thinking is as follows:
- When possible (maybe ~1 month), split off the dashboard into a separate repo.  In this repo, document the fact that feature development is no longer ongoing by me or anyone at Netflix.
- I'll keep admin rights so that I may merge feature requests/bugfixes by others.
- If someone would like to take over as maintainer of the project, I can grant admin rights and then help get all of the documentation/procedures in place so that I can handoff the project and roadmap.

I'd love input on all of the above, and am happy to answer any questions as well.

**Comment by the4yeast** [comment]
@mattrjacobs has Netflix open-sourced any of the tools they used to replace the dashboard?

**Comment by mattrjacobs** [comment]
@the4yeast As of today, no.  That may change as the tools get more mature.

**Comment by the4yeast** [comment]
Thanks @mattrjacobs
