### ISSUE TITLE
Hystrix 1.4.22 is not available on Maven Central

### ISSUE THREAD

**Issue by chrisgray** [Netflix/Hystrix#1037]
It looks like the artifacts for hystrix-* for 1.4.22 never made it to Maven central? The latest there is still 1.4.21.

**Comment by mattrjacobs** [comment]
Sorry for the delay - I'm working with our internal team to get access to Bintray so that I can get it copied over from Bintray -> Maven Central.  Unfortunately, #979 is still unresolved.

**Comment by chrisgray** [comment]
Thanks for the prompt response!

**Comment by mattrjacobs** [comment]
Got this sorted out manually.  Now available at: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.netflix.hystrix%22%20AND%20v%3A%221.4.22%22

Still working on a longer-term fix to #979

**Comment by chrisgray** [comment]
:+1:
