### ISSUE TITLE
Hystrix Circuit Breaker question when there are multiple instances of the calling service

### ISSUE THREAD

**Issue by nmallya** [Netflix/Hystrix#1041]
I use Hystrix where a service S1 talks to S2. It works great, I am able to configure my parameters and can ensure that the circuit opens properly when S2 is down and there are 'n' failing requests.

What I am trying to understand about Hystrix is this: 
If I have, say 3 instances of S1 deployed on different servers and S2 goes down, do each of the S1 instance circuit breakers have to go through 'n' failing requests before all 3 circuit breakers are opened?

Is there something I am missing which might ensure that not all instances would have to hit S2 so many times once we know S2 is down?

While solutions like using a queue / cache / Database could be used to maintain state information, I was wondering if there is any other way in Hystrix or in Spring Netflix Cloud that I can leverage?

Thanks!

**Comment by mattrjacobs** [comment]
@nmallya This is a conscious design decision.  You are correct - each node has completely separate circuit breakers and there's no shared data between nodes.  

This is done to keep the decision-making as simple as possible by keeping the scope of data small.  It also doesn't introduce a new failure mode of not being able to reach the shared data.  It also allows for variation between nodes to not affect any other node.  For example, a node that is doing a full GC might timeout many Hystrix commands, and this shouldn't affect any other node's decisions.

In practice, we see that all nodes in a cluster generally act similarly when a remote failure occurs.  They don't fail in lockstep, but the likelihood of short-circuiting increases to a similar steady-state among all the nodes.

**Comment by nmallya** [comment]
Thanks @mattrjacobs  I will close this issue
