### ISSUE TITLE
Using javanica @HystrixCommand annotation on methods called from the same class

### ISSUE THREAD

**Issue by michaelcowan** [Netflix/Hystrix#1046]
I am using Spring and have a controller that looks something like this:

```java
@Service
public class ReleaseService {
  public Release GetLatestRelease {
    // Whole bunch of other stuff that I dont want carried out in a HystrixCommand
    FetchRelease("latest");
  }
  public Release GetRelease(String id) {
    // Whole bunch of other stuff that I dont want carried out in a HystrixCommand
    FetchRelease(id);
  }
  private Release FetchRelease(String id) {
    // HTTP Call to external service
  }
}
```

What I would like to be able to do is annotate the ```FetchRelease``` method with _@HystrixCommand_. When I try this the annotation seems to have no affect.

Am I right in thinking that the annotation will only work for public facing methods called from outside the class?

The only solution I could see to this was to create a Class to handle the HTTP request and annotate that. This works fine but doesn't suit nearly every other method in the service class.

Is there an alternative I haven't considered?

**Comment by spencergibb** [comment]
That's not how AOP works in general, what you stated is one way to go. The other is to not use javanica and create the command yourself.

**Comment by michaelcowan** [comment]
@spencergibb Thanks for confirming. Hand rolling a HystrixCommand may actually work for me. Thanks for the suggestion!
