### ISSUE TITLE
Builds hang due to Hystrix locks

### ISSUE THREAD

**Issue by marcingrzejszczak** [Netflix/Hystrix#1051]
Some of our builds are hanging on Hystrix related tests on our EC2 instance (C3 Compute Optimised Double Extra Large). This is the link of the last one: https://build.spring.io/download/SCE2E-SCSE2E-JOB1/build_logs/SCE2E-SCSE2E-JOB1-324.log

I did a thread dump of that build when it was stalling and this is its part

```
Thread 7521: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Interpreted frame)
 - java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=175 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt() @bci=1, line=836 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(int) @bci=72, line=997 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(int) @bci=24, line=1304 (Interpreted frame)
 - java.util.concurrent.CountDownLatch.await() @bci=5, line=231 (Interpreted frame)
 - rx.internal.operators.BlockingOperatorToFuture$2.get() @bci=4, line=107 (Interpreted frame)
 - com.netflix.hystrix.HystrixCommand.execute() @bci=4, line=335 (Interpreted frame)
 - com.netflix.hystrix.contrib.javanica.command.CommandExecutor.execute(com.netflix.hystrix.HystrixExecutable, com.netflix.hystrix.contrib.javanica.command.ExecutionType, com.netflix.hystrix.contrib.jav
anica.command.MetaHolder) @bci=45, line=45 (Interpreted frame)
 - com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect.methodsAnnotatedWithHystrixCommand(org.aspectj.lang.ProceedingJoinPoint) @bci=137, line=96 (Interpreted frame)
 - sun.reflect.NativeMethodAccessorImpl.invoke0(java.lang.reflect.Method, java.lang.Object, java.lang.Object[]) @bci=0 (Compiled frame)
 - sun.reflect.NativeMethodAccessorImpl.invoke(java.lang.Object, java.lang.Object[]) @bci=100, line=62 (Compiled frame)
 - sun.reflect.DelegatingMethodAccessorImpl.invoke(java.lang.Object, java.lang.Object[]) @bci=6, line=43 (Compiled frame)
 - java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) @bci=56, line=497 (Compiled frame)
 - org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(java.lang.Object[]) @bci=36, line=621 (Interpreted frame)
 - org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(org.aspectj.lang.JoinPoint, org.aspectj.weaver.tools.JoinPointMatch, java.lang.Object, java.lang.Throwable) @bci=10, line=610
(Interpreted frame)
 - org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(org.aopalliance.intercept.MethodInvocation) @bci=58, line=68 (Interpreted frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=85, line=168 (Interpreted frame)
 - org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(org.aopalliance.intercept.MethodInvocation) @bci=18, line=92 (Interpreted frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=101, line=179 (Interpreted frame)
 - org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(java.lang.Object, java.lang.reflect.Method, java.lang.Object[], org.springframework.cglib.proxy.MethodProxy) @bci=1
20, line=655 (Interpreted frame)
 - org.springframework.cloud.sleuth.instrument.hystrix.SpanPassingForHystrixViaAnnotationsIntegrationTests$HystrixCommandInvocationSpanCatcher$$EnhancerBySpringCGLIB$$5b1dcfe1.invokeLogicWrappedInHystrixCommand() @bci=31 (Interpreted frame)
 - org.springframework.cloud.sleuth.instrument.hystrix.SpanPassingForHystrixViaAnnotationsIntegrationTests.whenHystrixCommandAnnotatedMethodGetsExecuted() @bci=4, line=47 (Interpreted frame)
 - org.springframework.cloud.sleuth.instrument.hystrix.SpanPassingForHystrixViaAnnotationsIntegrationTests.should_set_span_on_an_hystrix_command_annotated_method() @bci=6, line=35 (Interpreted frame)
```

There is also another log that is stalling at the same place - https://build.spring.io/download/SCE2E-SCSE2E-JOB1/build_logs/SCE2E-SCSE2E-JOB1-323.log . Here the thread is waiting (by mistake I've done two subsequent thread dumps).

I don't know if it's Hystrix related but looks that way (similar issues we had with spring-cloud-netflix). Here is the link to the test: https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/hystrix/SpanPassingForHystrixViaAnnotationsIntegrationTests.java

**Comment by mattrjacobs** [comment]
@marcingrzejszczak I'm having trouble getting my IDE set up for this project.  Can you give me a command-line invocation of Maven that would run just this test, so I can trace through the execution paths?

**Comment by marcingrzejszczak** [comment]
In the IDE you have to provide `.settings.xml` as the settings file for Maven.

From the command line just type `./mvnw clean install` to run everything.

To run one test:

```
$ pwd
> ..../spring-cloud-sleuth/spring-cloud-sleuth-core
$ mvn -s ../.settings.xml -Dtest=SpanPassingForHystrixViaAnnotationsIntegrationTests test
```

**Comment by mattrjacobs** [comment]
@marcingrzejszczak I haven't been able to reproduce this while running locally, which I think you said was your situation as well.

What I can gather from the stack trace included in the link to your failed CI build is:

* `org.springframework.cloud.sleuth.instrument.TraceDelegate.startSpan(TraceDelegate.java:59)` fails with `java.lang.IllegalStateException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1d81e101 has been closed already`

AFAICT, that failure is within the module you're testing, and Hystrix isn't responsible for that error occuring.

Once that error occurs, the HystrixTimer thread attempts to run and give the caller thread a Timeout OnError.  However, the `HystrixContextRunnable` throws an error before that can get delivered.  As a result, the caller thread waits forever.

Are you registering a `HystrixConcurrencyStrategy`?

The code that is throwing is `com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:59)`  This implies that the following code is throwing: `concurrencyStrategy.wrapCallable(actual.run()).call()`.

In this case, `actual` refers to the OnError delivery, and should not be the source of the exception.  So I'm curious if you've got a `HystrixConcurrencyStrategy` that could be generating this error

**Comment by marcingrzejszczak** [comment]
@mattrjacobs hmm actually we are - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixConcurrencyStrategy.java 

It's more than probable that we're doing it wrong?

**Comment by mattrjacobs** [comment]
Quite possibly.  One thing that's worth checking is what `HystrixConcurrencyStrategy` is used during your tests.  If a command runs before your custom concurrency strategy gets set up, then it picks the default `HystrixConcurrencyStrategy` and uses that for the lifetime of the JVM.

That might be what's happening here.  There's more context here: https://github.com/Netflix/Hystrix/wiki/FAQ-:-Operational, but with a different symptom than yours.

**Comment by marcingrzejszczak** [comment]
Hi!

Sorry for the late reply. 

Our custom strategy is just wrapping a `Callable` into `TraceCallable`. The latter is just creating an object and closing it. So it shouldn't influence anything.

**Comment by mattrjacobs** [comment]
Can you determine what is closing the 'org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext' ?  That should help narrow the problem down.

The stack-trace indicates that the `TraceDelegate` class is throwing the exception.  One option is to make that more robust to request contexts disappearing, or to understand why the request context is getting closed before the `TraceDelegate` gets to `.startSpan()`.

**Comment by marcingrzejszczak** [comment]
I'm pretty sure it's related to us setting custom strategy  - let's close it and if I have any proof that it's Hystrix fault then I'll reopen it :)

**Comment by mattrjacobs** [comment]
Thanks for following up @marcingrzejszczak .  Let me know if I can help diagnose anything
