### ISSUE TITLE
Hystrix 1.4.23 is not available on Maven Central

### ISSUE THREAD

**Issue by chrisgray** [Netflix/Hystrix#1053]
Looks like again the similar issue where the build process only got the artifacts to bintray and not maven central :'(

**Comment by mattrjacobs** [comment]
Finally figured out how to do the Bintray -> Sonatype sync myself this morning.  In a couple hours, Maven Central should have 1.4.23.  Will close when I confirm that

**Comment by mattrjacobs** [comment]
Sync worked, so this should no longer be an issue going forward
