### ISSUE TITLE
Hystrix dashboard doesn't work correctly with hystrix-examples-webapp

### ISSUE THREAD

**Issue by deejay1** [Netflix/Hystrix#1098]
The example webapp doesn't work correctly with v1.5.0-rc.3 (and current master) as it fails in hystrixCommand.js with "Failed preProcessData: Key Missing: latencyTotal_mean for CreditCardCommand" (and similar)

**Comment by mattrjacobs** [comment]
Thanks for the report, @deejay1 !  I think I fixed this in #1099

**Comment by deejay1** [comment]
@mattrjacobs Seems to work fine now, thanks!
