### ISSUE TITLE
Make queue size of MetricJsonListener configurable

### ISSUE THREAD

**Issue by anuragw** [Netflix/Hystrix#1109]
Currently, the MetricJsonListener in the hystrix-metrics-event-stream collects metrics into a queue which is hard-coded to a size of 1000. Our system has a very high request rate, hence this queue gets populated quite soon when pulling the metrics stream. While we're using version 1.4.23 right now, the latest RC also has the same issue.

Could this queue size be made configurable, perhaps with a default set to the current value of 1000, in order to allow more flexibility for larger systems? Also, if this is agreeable, and the change is included in the current/next release candidate, what would be an approximate ETA on the next release?

**Comment by mattrjacobs** [comment]
Yeah, this sounds like an OK thing to do.  I'm happy to review a PR for this.

**Comment by anuragw** [comment]
My upstream git config got messed up, I'll probably have to rewrite the history and force-push. I'll let you know once its done, there should only be the original two commits I had.

**Comment by mattrjacobs** [comment]
Closed via #1114

**Comment by anuragw** [comment]
Thanks, @mattrjacobs!

**Comment by anuragw** [comment]
@mattrjacobs Any updates on when 1.4.25 might be released? I'm assuming this change goes in the 1.4.25 release.

**Comment by mattrjacobs** [comment]
Just released in 1.4.25: https://github.com/Netflix/Hystrix/releases/tag/v1.4.25

Haven't done a release out of master yet - I need to evaluate a couple other changes/proposals before I cut that.
