### ISSUE TITLE
TimeoutException in AbstractCommand doesn't chain its cause

### ISSUE THREAD

**Issue by pz7** [Netflix/Hystrix#1119]
When getting the TimeoutException from hystrix command we can't trace it down to our specific code.
The issue seems to be that the TimeoutException created in the AbstractCommand (around line 600) is **not chaining** its cause.

I suggest to change the code from:
```java
return getFallbackOrThrowException(HystrixEventType.TIMEOUT, FailureType.TIMEOUT, "timed-out", new TimeoutException());
```

to something like this:
```java
TimeoutException timeoutException = new TimeoutException();
timeoutException.initCause(t); // IMPORTANT - chaining to the cause
return getFallbackOrThrowException(HystrixEventType.TIMEOUT, FailureType.TIMEOUT, "timed-out", timeoutException);
```

Thanks.

**Comment by mattrjacobs** [comment]
This was a premature optimization to save on allocations.  As you brought up, the ability to get the proper cause is more important than saving the allocation.  This will go out in next release (sometime this week)

**Comment by pz7** [comment]
:thumbsup:
