### ISSUE TITLE
Consider logging on lower level in hystrix metrics eventstream components

### ISSUE THREAD

**Issue by sslavic** [Netflix/Hystrix#1122]
HystrixMetricsPoller and HystrixMetricsStreamServlet log too much on Info level - starting/stopping poller messages are all over the place in logs and add not enough value.

For now as workaround I can adjust logging level for com.netflix.hystrix.contrib.metrics.eventstream logger to warning or error, but IMO at least some of logged messages could be logged on debug level instead in the first place.

Please review used logging level in these components and consider making adjustments where needed.

**Comment by mattrjacobs** [comment]
Sure, seems reasonable.  Would you like to submit a PR?  Otherwise, I should be able to get to this sometime this week.

**Comment by sslavic** [comment]
Sorry, wish I could, but it's complicated.

**Comment by mattrjacobs** [comment]
Does #1124 look OK, @sslavic ?

**Comment by sslavic** [comment]
Looks great. Thanks!
