### ISSUE TITLE
Demo falls into infinite loop

### ISSUE THREAD

**Issue by reboss** [Netflix/Hystrix#1145]
Hi,

The ./gradlew runDemo command falls into an infinite loop at 88%, where it calls CreditCardCommand over and over again.  I poured over the code in HystrixCommandDemo.java and found a while(true) statement in the startDemo() method that seems to be the problem. 

Maybe someone can elaborate a bit.  I feel like I might be missing something here.

Thanks.

**Comment by mattrjacobs** [comment]
@reboss This is by design.  This is basically simulating a long-running server that accepts user requests until the process is killed.  There are certainly other possible use cases of Hystrix, but this is the one we at Netflix are most familiar with.

**Comment by reboss** [comment]
Ok, that makes sense, I think it was the 88% complete part that threw me off.

I wonder, would it be useful to have a log file for the output of the demo?

**Comment by mattrjacobs** [comment]
That's basically just how Gradle deals with running an infinite loop in a main method.  If you wanted a process outside of Gradle with proper logging, then you could build an executable jar and set up logging within that.  I'm happy to review a PR if you're interested in that.

**Comment by reboss** [comment]
Yea that would be great.  I'll see if I can muster something up for a PR.

Thanks.
