### ISSUE TITLE
onExecutionStart in HystrixCommandExecutionHook does not have HystrixRequestContext initialized

### ISSUE THREAD

**Issue by sahlex** [Netflix/Hystrix#1148]
When the` onExecutionStart()` method in the `HystrixCommandExecutionHook` is actually called, the `HystrixRequestContext` has not been initialized from parent command. Is there a way to achieve that the copy of the context is already done when calling that hook?

**Comment by mattrjacobs** [comment]
The `HystrixRequestContext`does get generated in a `HystrixCommand`, it gets generated outside of Hystrix upon the start of a request.  If you look at `HystrixCommandTest`, that's simulated by setting up a `HystrixRequestContext` at each test start and tearing it down at the end of the test.  This simulates each unit test running in a separate request.

Adding the log as I've done in https://github.com/mattrjacobs/Hystrix/commit/bc0e17df3a2d485da25e91d86f611c6b2bfd1880 and then running `HystrixCommandTest` demonstrates that the `HystrixRequestContext` is available in the hook implementation.

**Comment by sahlex** [comment]
Hello Matt!

Yes, sure. We ARE in fact creating the HystrixRequest context outside the command. Situation is more complicated here. We have two commands, let's call them Parent and Child. The Parent calls a Child command and calls `subscribeOn(Schedulers.NewThread).subscribe()` on the child,

Given this situation, the client command does not receive the request context from the parent! It works as long as I don't use subscribeOn...

Please find attached a test file.

Best regards, Alexander
[ExecutionHookTest.zip](https://github.com/Netflix/Hystrix/files/177426/ExecutionHookTest.zip)

**Comment by mattrjacobs** [comment]
OK, that makes sense then.  Thanks for providing that context.  What's happening is that the `HystrixRequestVariable` is implemented as a `ThreadLocal` that gets passed among threads in a request.  The `HystrixContextScheduler` is responsible for putting the context on the Hystrix thread.

At the moment, nothing is responsible for sharing that context over to the Rx-owned threads.  RxJava provides hooks where you can override scheduling behavior (http://reactivex.io/RxJava/javadoc/rx/plugins/RxJavaSchedulersHook.html).  If you apply those hooks, you can then provide a new implementation of scheduling that does the context wrapping.  You would probably want a implementation similar to `HystrixContexSchedulerAction` (yes, known typo :))

Hope that helps

**Comment by sahlex** [comment]
Ah, ok, thanks.
