### ISSUE TITLE
private method getProperty is unused

### ISSUE THREAD

**Issue by fcalderonnearsoft** [Netflix/Hystrix#1150]
Is there a reason to keep getProperty in class HystrixCollapserProperties with '@SuppressWarnings("unused")' annotation?

**Comment by mattrjacobs** [comment]
No good reason.  Removed in #1151

**Comment by fcalderonnearsoft** [comment]
@mattrjacobs I found more https://github.com/Netflix/Hystrix/pull/1154

**Comment by mattrjacobs** [comment]
Closed via #1154
