### ISSUE TITLE
There is no way of accessing HystrixObservableCommand.Setter.HystrixThreadPoolProperties.Setter

### ISSUE THREAD

**Issue by sahlex** [Netflix/Hystrix#1153]
Maybe one's not intended to to this, but shouldn't it be possible to set the thread pool properties on a `HystrixInvokableCommand`? Right currently there is no `andThreadPoolPropertiesDefaults `like in HystrixCommand's Setter class.

Best regards,
Alexander.

**Comment by mattrjacobs** [comment]
You're correct - we haven't found a case where this is the right thing to do (so far).  See discussion here: https://github.com/Netflix/Hystrix/issues/805#issuecomment-109371037

**Comment by kennedyoliveira** [comment]
@mattrjacobs, i ready the discussion from #805, and understood the use of `HystrixObservableCommand`, but since it won't use a thread, how could i set a timeout that hystrix will use to calculate and generate metrics about it?

**Comment by sahlex** [comment]
But since I'm able to chose the thread execution strategy in favor of the semaphore strategy, how do I restrict the number of concurrent executions of an observable command? Why then offering the ability to set thread execution strategy anyways?

**Comment by sahlex** [comment]
I'd like to shortly explain why I'd need this: 

We implemented a unit-of-work framework similar to JEE's persitance framework that is bound to a hystrix request context in spite of being bound to a thread local like in JEE. As we are able to do autonomous transactions for subsequent/nested commands, we need to able to switch the hystrix context to a new one for the autonomous transaction. This obviously does not work, when everything executes on the same thread. 

The implementation makes heavy use of Hystrix' CommandExecutionHook

**Comment by mattrjacobs** [comment]
@sahlex / @kennedyoliveira I'm on vacation until Monday.  Will answer Monday ASAP

**Comment by kennedyoliveira** [comment]
@mattrjacobs, ok!

**Comment by mattrjacobs** [comment]
@kennedyoliveira A semaphore-isolated command does not use a Hystrix thread.  However, timeouts are all scheduled on a `HystrixTimer` thread.  That thread causes a `HystrixTimeoutException` to be emitted into the result path of the command.

**Comment by mattrjacobs** [comment]
@sahlex This was done mostly to not introduce separate configuration mechanisms for `HystrixCommand` / `HystrixObservableCommand`.  On semaphore-isolated commands, you can still set: https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.semaphore.maxConcurrentRequests and bound concurrency

**Comment by kennedyoliveira** [comment]
@mattrjacobs, i understand what you said, so, when using an already Async Observable within an HystrixObservableCommand and semaphore-isolated i can't have a timeout?
If i use a thread in an Async Observable with HystrixObservableCommand it would be a waste of resource since the Command already executes async, then it would have 2 threads

**Comment by mattrjacobs** [comment]
@sahlex For your 2nd question, I'm not familiar with JEE Persistence.  A code pointer would make your use case more clear to me.

**Comment by mattrjacobs** [comment]
@kennedyoliveira 

Here are the 2 recommended possibilities for modeling work:

1) Blocking I/O: Use `HystrixCommand` and thread-isolation.  Each command instance runs on a Hystrix thread and returns a `T`.  If the timeout latency is reached without a value being emitted, the `HystrixTimer` thread returns a `HystrixTimeoutException` to the caller, and attempts to interrupt the Hystrix thread.

2) Nonblocking I/O: Use `HystrixObservableCommand` and semaphore-isolation.  Each command instance begins on the caller thread (with work happening in the background, as defined by the specific nonblocking I/O library).  If the timeout latency is reached without a value being emitted, the `HystrixTimer` thread returns a `HystrixTimeoutException` to the caller, and the nonblocking I/O operation is unsubscribed from.

Note that the `HystrixTimer` threads are shared by all Hystrix commands in a JVM, so there's very small incremental cost to doing these non-blocking timeouts.

**Comment by sahlex** [comment]
Thanks for clarification!

**Comment by kennedyoliveira** [comment]
@mattrjacobs, Thanks for the great explanation!
