### ISSUE TITLE
Hystrix exceptions not passed into fallback.

### ISSUE THREAD

**Issue by ckstettler** [Netflix/Hystrix#1155]
I have implemented a fallback that accepts Throwable.

What I see is the following:

If I get into my @HystrixCommand annotated function and throw an exception, then I do in fact see the correct throwable in the fallback function.

If the exception is raised as part of the @HystrixCommand processing within javanica such as timeout or queue threshold is reached etc, then the throwable in the fallback is not populated.

Is there anyway for me to see these exceptions?  I am using 1.5.1.

**Comment by mattrjacobs** [comment]
@ckstettler Thanks for the report.  Can someone more familiar with `hystrix-javanica` look into this bug? 
/cc @dmgcodevil

**Comment by dmgcodevil** [comment]
Hi, it's a duplicate https://github.com/Netflix/Hystrix/issues/974
Problem was getFailedExecutionException() doesn't return exceptions in case of timeouts and etc but nulls. to get exception javanica uses getFailedExecutionException().
I remember Matt fixed this issue in core. 
@mattrjacobs  should I change something in javanica to get such exceptions and propogate them ?

**Comment by mattrjacobs** [comment]
@dmgcodevil IIRC, it's the change you mentioned here: https://github.com/Netflix/Hystrix/issues/1013#issuecomment-163368438

**Comment by dmgcodevil** [comment]
Oh, right, will change today then

**Comment by fayndee** [comment]
Hi @dmgcodevil, is there any progress on this fix?

**Comment by dmgcodevil** [comment]
Hi @fayndee, yes, Spencer has fixed the issue. I guess we can close this issue

**Comment by mattrjacobs** [comment]
Released in 1.4.26/1.5.2

**Comment by ckstettler** [comment]
Awesome!! Thank you.
