### ISSUE TITLE
class file for rx.Observable not found when creating hello-world

### ISSUE THREAD

**Issue by arunasujith** [Netflix/Hystrix#1159]
I am getting the "class file for rx.Observable not found" error when trying to compile after following the instructions in, [1].

Need to add  rxjava dependency to resolve the build issue. Better to add this information to the README.
`      
 <dependency>
            <groupId>io.reactivex</groupId>
            <artifactId>rxjava</artifactId>
            <version>1.1.2</version>
</dependency>
`
[1]. https://github.com/Netflix/Hystrix/blob/master/README.md

**Comment by mattrjacobs** [comment]
Can you more explicit about which instructions you were following?

When I set up a new Gradle project and added the single line: 
```
 compile group: 'com.netflix.hystrix', name: 'hystrix-core', version: '1.5.1'
```

, I was able to start an application with Hystrix working.

See the project at: https://github.com/mattrjacobs/minimal-hystrix

**Comment by arunasujith** [comment]
Sorry @mattrjacobs  for not providing the project. 
I just created maven project and tried to run from IDE and it complains giving the below error.

**Error:(21, 8) java: cannot access rx.Observable
  class file for rx.Observable not found**

Here is the github project I've used to test. [1].

[1]. https://github.com/arunasujith/hystrix-test

**Comment by mattrjacobs** [comment]
Ah, I think I see what's happening.  There was an issue with the build process for 1.4.0-1.4.19 that didn't mark dependencies properly.  If you use the most recent versions of the 1.4.x or 1.5.x series (1.4.25/1.5.1), you shouldn't need to include rxjava (or any other Hystrix dependency) explicitly.  

This was issue #730
