### ISSUE TITLE
Mechanism for Auditing Network Access Not Isolated by Hystrix

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/Hystrix#116]
Explore options for tracking when network access is done with Hystrix isolating it (such as within a thread isolated HystrixCommand).

If a reasonable solution can be done generically implement a contrib module.

The intent is:
- find unknown vulnerabilities
- track "drift" over time as transitive dependencies pull in code that performs network access
- track metrics and optionally provide alerts
- allow failing a canary build if unexpected network access occurs
- alert in production if unexpected network access starts (such as if a property is flipped to turn on a feature)

**Comment by karthikitzmi** [comment]
HystrixNetworkAuditorEventListener#handleNetworkEvent() isn't invoked when  encountered with "java/net/ConnectException". Its not invoked with other exceptions. Here is the link.

Is there anything that could be done. Not sure if its the issue with version

http://stackoverflow.com/questions/40643621/hystrixnetworkauditoreventlistener-is-not-invoked-upon-failure-in-connecting-to
