### ISSUE TITLE
Fallback with an Exception is not found when using hystrix-javanica

### ISSUE THREAD

**Issue by csmithmtb** [Netflix/Hystrix#1165]
I created a simple fallback with an Exception.  When the command fails, there is an error that logged that Hystrix Javanica (via @HystrixCommand) can't find the fallback method with the Exception parameter and it appears to be looking for the method without the Exception.  The fallback seems to work fine when I remove the Exception parameter from the fallback method.

This is a spring boot application and the hystrix version is 1.4.10 (although, I have tried with version 1.5.1 and got the same issue).

Is there a configuration property that needed for this to work with the Exception parameter in the fallback method?

Class:
```
@Component
public class AuthenticaResourceIntegration {

	@Value("${authentica-resource-url:http://authentica-mock-resource}")
	private String authenticaResourceUrl;

	@Autowired
	@LoadBalanced
	private RestTemplate restTemplate;

	@HystrixCommand(fallbackMethod = "fallbackAuthenticaRoot")
	public String getAuthenticaRoot(String id) {
		System.out.println("URL: " + authenticaResourceUrl);
		return restTemplate.getForObject(authenticaResourceUrl, String.class);
	}

	public String fallbackAuthenticaRoot(String id, Exception e) {
		System.out.println("Fallback error. Reason: " + e.getMessage());
		return "Authentica Fallback!";
	}

}

```
Error:

java.lang.NoSuchMethodException: com.elavon.synchronicity.test.AuthenticaResourceIntegration.fallbackAuthenticaRoot(java.lang.String)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.netflix.hystrix.contrib.javanica.command.AbstractHystrixCommandFactory.createFallbackAction(AbstractHystrixCommandFactory.java:87)
	at com.netflix.hystrix.contrib.javanica.command.AbstractHystrixCommandFactory.create(AbstractHystrixCommandFactory.java:66)
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect.methodsAnnotatedWithHystrixCommand(HystrixCommandAspect.java:81)

**Comment by dmgcodevil** [comment]
Sorry guys, I wasn't able to create PR and left for vacation. But there is
just one line to fix, I think Spenser can help out.

**Comment by spencergibb** [comment]
Is this a duplicate of #1155?

**Comment by mattrjacobs** [comment]
I think so

**Comment by csmithmtb** [comment]
After updating to 1.5.1 and re-reading the document, it appears to be a user error...My Exception parameter should be Throwable.  I updated the parameter from Exception to Throwable in the fallback method and it works as expected.

**Comment by basurohit77** [comment]
Thing is both parameters and return type of the fallbackMethod and the main method should be same.
The fallbackMethod may have an extra argument of type Throwable
