### ISSUE TITLE
Dashboard + Turbine for multiple services on the same server

### ISSUE THREAD

**Issue by pparth** [Netflix/Hystrix#117]
Hello again Ben,

I used the Dashboard to monitor a single service successfully. I tried to use Turbine in order to aggregate Hystrix metrics from multiple services residing on the same server, but this seems to be impossible. 
So, let me clear the things a little bit:
The architecture of the relevant Netflix implementation, which is reflected in the Dashboard images presented all over the Dashboard and Turbine Wiki, essentially implies that each service resides on its own server. In order to aggregate Hystrix metrics from all services (each defining its own set of Hystrix commands), all services should generate the metrics stream on the same port (e.g. 8080) which is configured in Turbine. The question is: can Turbine aggregate different sets of Hystrix commands metrics this way?
So, if i have 5 different services, each with different sets of Hystrix commands, located in 5 different servers, then can i have a Dashboard where i could see the union of all Hystrix commands, using Turbine to define a Default cluster of these instances? 
What happens when the same Hystrix Command is defined in different hosts?

**Comment by seh13** [comment]
@codependent Did you ever find a solution to your issue with 2 servers? I'm having pretty much the same issue and can't seem to figure out what the problem is.

Thanks!

**Comment by codependent** [comment]
@seh13 Yes, it was pretty straightforward. I don't have access to the code right now, I'll post it here tomorrow.

**Comment by codependent** [comment]
Hi seh13, this is my cfg:

    #################################
    # Turbine 
    #################################
    turbine.aggregator.clusterConfig=myCluster
    turbine.instanceUrlSuffix.myCluster=/hystrix.stream

    #################################
    # ConfigPropertyBasedInstanceDiscovery 
    # (config.properties-based impl only)
    #################################
    turbine.ConfigPropertyBasedDiscovery.myCluster.instances=domain1:9080/app1,domain1:9080/app2

You can keep adding domains+app to `turbine.ConfigPropertyBasedDiscovery.myCluster.instances`

Hope this helps

**Comment by seh13** [comment]
@codependent Great, that would be much appreciated!

**Comment by swethasappati** [comment]
Hi, 
   First time I'm working with hystrix turbine. I'm able to access one service on turbine successfully, but I'm unable to access multiple services on same host with different ports. I have configured my turbine yml file as below , I have 2 microservices, 1 eureka and 1 turbine server.

turbine:
   combineHostPort: true
   appConfig: FIRSTSPRINGBOOTAPP,FIRSTRESTAPP
   aggregator:
      clusterConfig: myCluster
      instanceUrlSuffix: 
        myCluster: /hystrix.stream
   ConfigPropertyBasedDiscovery: 
      myCluster:
          instances: http://ushydssappati1:8091/FIRSTSPRINGBOOTAPP,http://ushydssappati1:8095/FIRSTRESTAPP

when I run my turbine service, my console shows,

2016-07-08 12:23:54.808  INFO 2460 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Fetching instance list for apps: [FIRSTSPRINGBOOTAPP, FIRSTRESTAPP]
2016-07-08 12:23:54.808  INFO 2460 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Fetching instances for app: FIRSTSPRINGBOOTAPP
2016-07-08 12:23:54.808  INFO 2460 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Received instance list for app: FIRSTSPRINGBOOTAPP, size=1
2016-07-08 12:23:54.824  INFO 2460 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Fetching instances for app: FIRSTRESTAPP
2016-07-08 12:23:54.824  INFO 2460 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Received instance list for app: FIRSTRESTAPP, size=1
2016-07-08 12:23:54.825  INFO 2460 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Retrieved hosts from InstanceDiscovery: 2
2016-07-08 12:23:54.825  INFO 2460 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Found hosts that have been previously terminated: 0
2016-07-08 12:23:54.826  INFO 2460 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Hosts up:2, hosts down: 0

but If I hit the URL: host:turbine_port/turbine.stream?cluster=myCluster, I  couldn't see anything on browser. Could anybody please help me to achieve this. I'm not understanding that what I'm missing and where I'm missing.

Warm Regards,
Swetha

**Comment by JagmohanSharma** [comment]
Sorry for commenting here but I am facing kind of similar issue. As We have single service on same host but different port . so I am using consul discovery client here where I am able to get two different instances for this service. 

But when we fetch this from 
public TurbineDataMonitor<K> findMonitor(String name) {
        return registry.get(name);
    }

it return only single monitor and I am not able to see the aggregated view using same cluster name for these two instances. Can somebody help how to make this happen ?
