### ISSUE TITLE
Javanica fallback not found when contained in super class

### ISSUE THREAD

**Issue by ctoestreich** [Netflix/Hystrix#1177]
We are using the Annotated methods on classes where a service extends another service

```groovy 
class WishlistService extends CartService { ... }
```

And then inside CartService there is a some methods like

``` groovy 
 @HystrixCommand(commandProperties = [
            @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "5000")
    ], threadPoolProperties = [
            @HystrixProperty(name = "coreSize", value = "20"),
            @HystrixProperty(name = "maxQueueSize", value = "150"),
            @HystrixProperty(name = "queueSizeRejectionThreshold", value = "150")
    ], threadPoolKey = 'CartService', fallbackMethod = 'transferItemsFallback')
    CartResponseDTO transferItems(CartKey fromKey, CartKey toKey, List itemIds){
     ...
}

CartResponseDTO transferItemsFallback(CartKey fromKey, CartKey toKey, List items, Throwable e) { ... }
```

When using the service `wishListService` in a class the following exception is thrown

``` console
com.netflix.hystrix.contrib.javanica.exception.FallbackDefinitionException: fallback method wasn't found: transferItemsFallback([class com.bsb.cart.domain.CartKey, class com.bsb.cart.domain.CartKey, interface java.util.List])
	at com.netflix.hystrix.contrib.javanica.utils.MethodProvider.getFallbackMethod(MethodProvider.java:82) ~[hystrix-javanica-1.5.2.jar:1.5.2]
	at com.netflix.hystrix.contrib.javanica.utils.MethodProvider.getFallbackMethod(MethodProvider.java:55) ~[hystrix-javanica-1.5.2.jar:1.5.2]
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect$MetaHolderFactory.metaHolderBuilder(HystrixCommandAspect.java:120) ~[hystrix-javanica-1.5.2.jar:1.5.2]
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect$CommandMetaHolderFactory.create(HystrixCommandAspect.java:208) ~[hystrix-javanica-1.5.2.jar:1.5.2]
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect$MetaHolderFactory.create(HystrixCommandAspect.java:106) ~[hystrix-javanica-1.5.2.jar:1.5.2]
```

It would appear that when calling reflection for the class in com.netflix.hystrix.contrib.javinca.utils.MethodProvider line 92 
`return Optional.of(type.getDeclaredMethod(name, parameterTypes));` it does not resolve the super classes fallback method.  

We are using groovy and grails and this may be a factor in the evaluation of the type methods via reflection.  However calling the following DOES resolve the method.

``` java
type.getSuperclass().getDeclaredMethod(name, parameterTypes)
```

![screen shot 2016-04-13 at 10 27 47 am](https://cloud.githubusercontent.com/assets/691357/14499090/7422e470-0162-11e6-98fe-acea8158db4e.png)

**Comment by mattrjacobs** [comment]
@dmgcodevil Any thoughts on this one?

**Comment by dmgcodevil** [comment]
Interesting, will take a look. Ok.

**Comment by bischoje** [comment]
We have the exact same scenario and problem as ctoestreich describes in this issue. However, we are *not* using Groovy or Grails, just plain Java.

I'm going to attempt a workaround for this by declaring the fallback methods as 'abstract' in the super class, thus forcing the subclasses to implement them. This workaround obviously won't work for everyone, so it would be good to make the fallback method search more robust so it can find inherited methods too!

**Comment by mattrjacobs** [comment]
ping @dmgcodevil 

any thoughts?

**Comment by dmgcodevil** [comment]
Hi was busy with other activities, on the next weekend I will recall all
existing issues and try fix them at once. Sorry for inconvenience.

**Comment by bischoje** [comment]
My workaround to implement in the subclasses is working for now. It would be great to resolve this though, thank you in advance!

**Comment by dmgcodevil** [comment]
@mattrjacobs can we close ?

**Comment by mattrjacobs** [comment]
Yes, thanks @dmgcodevil !
