### ISSUE TITLE
Issue with AsyncResult in Javanica

### ISSUE THREAD

**Issue by santoshavkr** [Netflix/Hystrix#1179]
Hi,
Not sure if this is an issue but im facing a basic problem with AsyncResult 

 @HystrixCommand(commandKey = "GetUserCommand", threadPoolKey = "CommandTestAsync")
    public Future<User> getUserAsync(final String id, final String name) {
        return new AsyncResult<User>() {
            @Override
            public User invoke() {
                return new User(id, name + id); // it should be network call
            }
        };
    }

    public static void main(String[] args) throws Exception{
        DummyAPI dummyAPI=new DummyAPI();

        Future<User> f1 = dummyAPI.getUserAsync("1", "name: ");

        System.out.println(f1.get().getName());
    } 

This results in an Exception

java.lang.UnsupportedOperationException: AsyncResult is just a stab and cannot be used as complete implementation of Future

.Not sure if im missing anything Please help

**Comment by spencergibb** [comment]
You're missing a lot. Javanica uses AOP. Read the docs, but you need to set it up correctly. I'm on my phone so I can't provide a proper example. https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-javanica/README.md

**Comment by santoshavkr** [comment]
Thanks much for the quick response on this.I missed the most important step and after configuring AOP it worked fine.
