### ISSUE TITLE
Problem in increasing the window for statistics

### ISSUE THREAD

**Issue by shashank19aug** [Netflix/Hystrix#1195]
i am using Hystrix for my app, the number of requests in my app per minute are not high, probably 3-4  at max .
So in Hystrix dashboard , the statistics it shows it is only for some seconds, so is there a way so that it shows me data for the whole day.
i mean seeing Hystrix dashboard at the end of the day i should be able to figure out how many requests failed for my app, how many short circuited.etc 
is there a way to achieve this.
i believe there should be a configuration, i tried playing around with all configurations but no luck.
Could someone please help me with this.

**Comment by mattrjacobs** [comment]
In general, the streaming data that the dashboard depends on (`hystrix-metrics-event-stream`) is intended at the granularity of seconds/minutes, not hours/days.  

If you'd like to do time-series analysis, you should investigate one of the other metrics producers: https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#metrics-publisher.  

At Netflix, we use [Servo](https://www.github.com/Netflix/Servo) to publish metrics and [Atlas](http://www.github.com/Netflix/Atlas) to store/visualize them.

**Comment by mattrjacobs** [comment]
Closing out due to inactivity.  Please re-open if there's more to discuss.
