### ISSUE TITLE
Rx Async execution

### ISSUE THREAD

**Issue by bertvh** [Netflix/Hystrix#1201]
I want to execute a Hystrix command asynchronously, I'm not interested in the results in the thread I'm launching the command from. I'm using Javanica.

    @HystrixCommand(observableExecutionMode = LAZY)
    public final Observable<Boolean> doSomething() {
      return Observable.create(new Observable.OnSubscribe<Boolean>() {
        @Override
            public void call(Subscriber<? super Boolean> subscriber) {
              // Call an external system
              subscriber.onNext(true);
              subscriber.onCompleted();
            }
      }
    }

Now I would think executing this would be asynchronous (returns immediately), however it doesn't:

    doSomething().subscribe(/*do some logging*/); 

What does work is this:

    observable().subscribeOn(Schedulers.io()).subscribe(/*do some logging*/);

However, I'm afraid I'm messing with the threading introduced by Hystrix here. I'm really confused on what to do there. Any suggestions?

EDIT: ~~indeed, when subscribing on the io() thread, Hystrix does not time out.~~
EDIT2: Wrong.. it does time out!

**Comment by mattrjacobs** [comment]
In the uppermost-example, the Observable you're creating is synchronous.  Therefore, when Hystrix wraps a synchronous call, the result of that will also be synchronous.

If you put the call to `subscribeOn` in the Observable that Hystrix wraps, then you'll get an async command

**Comment by mattrjacobs** [comment]
Closing out due to inactivity.  Please re-open if there's more to discuss
