### ISSUE TITLE
 java.lang.IllegalArgumentException: Percentile (995.0) is not currently cached 

### ISSUE THREAD

**Issue by AchimWe** [Netflix/Hystrix#1214]
Hi,

first of all thanks for providing the “hystrix servo metrics publisher”. It works fine but with version 1.5.2 of the hystrix-core I got illegal argument exceptions:
 java.lang.IllegalArgumentException: Percentile (995.0) is not currently cached 
This exception is thrown in com.netflix.hystrix.metric .CachedValuesHistogram.java line 150.

I think this problem is cause by a typo in 
com.netflix.hystrix.contrib.servopublisher. HystrixServoMetricsPublisherCommand.

At line 518 the following statement adds a value 995
monitors.add(getTotalLatencyPercentileMonitor("latencyTotal_percentile_995", 995));
I think the value should be 99.5 instead of 995.

Kind regards
Achim Wehling

**Comment by mattrjacobs** [comment]
Thanks for the report.  Fixed in #1215
