### ISSUE TITLE
How can I monitor if fallback is being used?   

### ISSUE THREAD

**Issue by billyy** [Netflix/Hystrix#1216]
We have configured alert for excessive command failures (no fallback) so we can detect dependency issues.    Now we are adding fallback so the same command will report success even though the primary fails.   Is there a way to tell success with fallback so we can still send our alert due to excessive primary failure?   Thanks.

**Comment by mattrjacobs** [comment]
Yes, all of the monitoring integrations support counters on the fallback counters: FALLBACK_SUCCESS, FALLBACK_FAILURE, FALLBACK_REJECTION, FALLBACK_MISSING.

Is that what you're asking?

**Comment by billyy** [comment]
Yes.  That's what I am looking for.   So I need to log this metric too.  What was the counter name again? Does Hystrix Dashboard display the fallback status?

**Comment by mattrjacobs** [comment]
https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-metrics-event-stream shows a sample  JSON SSE stream

https://github.com/Netflix/Hystrix/tree/master/hystrix-dashboard shows the dashboard.  The dashboard does not show fallback outcomes

**Comment by billyy** [comment]
Got it.   I overlooked it when I saw the "Rolling" prefix.
