### ISSUE TITLE
Unable to set threadPoolProperties using Javanica on HystrixObservableCommand

### ISSUE THREAD

**Issue by yesdave** [Netflix/Hystrix#1228]
If I annotate my Observable returning command with `threadPoolProperties`:

```java
@HystrixCommand(
    commandProperties = {
        @HystrixProperty(name = "execution.isolation.strategy", value = "THREAD")
    },
    threadPoolProperties = {
        @HystrixProperty(name = "coreSize", value = "20")
    }
)
public Observable<User> getUser(Long id) {
      ...
}
```

It appears to be ignored:
> java.util.concurrent.FutureTask@7b9f4fb4 rejected from java.util.concurrent.ThreadPoolExecutor@69f1dd4f[Running, pool size = 10, active threads = 10, queued tasks = 0, completed tasks = 0]

This looks to be because `GenericSetterBuilder.buildObservableCommandSetter()` only sets commandProperties and ignores threadPoolProperties, unlike the `build()` method, which in turn might be because (core) `HystrixObservableCommand.Setter` class only deals with commandProperties.

Have threadPoolProperties been intentionally ignored on Observables, has this not been implemented yet, or am I missing something else entirely?

**Comment by mattrjacobs** [comment]
Allowing `HystrixObservableCommand`s to use thread-isolation was a mistake, and will be removed in a future version of Hystrix.  See #1200 for more details.

The 2 recommended ways to use Hystrix are:
1) If you are wrapping blocking I/O, model this as a `HystrixCommand` (not `HystrixObservableCommand`).  Use thread-isolation for resilience benefits.  You also gain the ability to perform async execution via `queue()`/`observe()`/`toObservable()`.
2) If you are wrapping nonblocking I/O, model this as a `HystrixObservableCommand`.  Use semaphore-isolation.

**Comment by swapnil1988** [comment]
I am evaluating hystrix for my new project. Correct  me if I am wrong but it seems I have a requirement where in I would require thread isolation for hystericObservableCommand. 
We would be using vertx framework along with hystrix. Vertx is non blocking async framework but also support blocking execution. So we would be using mix of both blocking and non blocking code. 
As part of wrapping a service call in hystrix we would have some blocking code as well as some non blocking in same service. Example would be some blocking code processing using legacy java library then send a message using vertx event bus and pass handler for getting reply that is async/ non blocking and when reply is received service execution is complete. 
Do let me know if what ever I have thought of make sence ?
