### ISSUE TITLE
Command is not executed in thread pool when using observable

### ISSUE THREAD

**Issue by baym0n** [Netflix/Hystrix#1239]
I have something like this in my service.

    @HystrixCommand
    public Observable<String> string() {
        log.info("invoke string()");
        return Observable.create(subscriber -> {
            log.info("invoke string() (observable)");
            try {
                if (!subscriber.isUnsubscribed()) {
                    subscriber.onNext("string");
                    subscriber.onCompleted();
                }
            } catch (final RuntimeException e) {
                subscriber.onError(e);
            }
        });
    }

When I call this service method, I can see in the log file that everything is executed within the tomcat request thread instead of a hystrix thread.

I followed the example on https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-javanica#reactive-execution, and it doesn't work as expected.

**Comment by mattrjacobs** [comment]
When using a `HystrixObservableCommand`, which javanica is doing here, it is expected that it runs of the caller thread.  The expectation is that you're providing an asynchronous Observable, in which case it's fine to use the caller thread.

If you are providing a synchronous Observable, as you are above, then it's more appropriate to use the Synchronous Execution model.  In this case, you would just return "string" directly.  That models your work as a `HystrixCommand`.  This would run on a Hystrix-provided thread in that case.

**Comment by dmgcodevil** [comment]
@mattrjacobs can we close ?
