### ISSUE TITLE
Support for non cached dynamic properties for a single commandKey

### ISSUE THREAD

**Issue by daniellavoie** [Netflix/Hystrix#1241]
Hi there, I am going to need some guidance. It feels to me it is impossible that multiple hystrix command sharing the same command key have different properties.

The following code from `HystrixPropertiesFactory` ignores the `builder` parameters and overwrite my command with the properties given for a previous command of the same group.

```
public static HystrixCommandProperties getCommandProperties(HystrixCommandKey key, HystrixCommandProperties.Setter builder) {
  HystrixPropertiesStrategy hystrixPropertiesStrategy = HystrixPlugins.getInstance().getPropertiesStrategy();
  String cacheKey = hystrixPropertiesStrategy.getCommandPropertiesCacheKey(key, builder);
  if (cacheKey != null) {
    HystrixCommandProperties properties = commandProperties.get(cacheKey);
    if (properties != null) {
      return properties;
    } else {
      ..
    }
    ...
  }
}
```

For my use case, I would like to adjust my execution timeout based on the functional parameters passed to my Hystrix Command (IE : Adjust the execution timeout based on the number of identifiers requested to the backend).

Should I aim for a custom Hystrix plugin ?

**Comment by mattrjacobs** [comment]
Hystrix intentionally does not support varying properties across instances that share a `HystrixCommandKey`.  The rationale is that it's much easier to understand the system by maintaining consistency of properties within a `HystrixCommandKey`.  

In your case, if the number of arguments is not too high, you could model each as a separate HystrixCommand.  If you don't like that approach, then you can implement your own plugin for property resolution.

**Comment by daniellavoie** [comment]
Hi Matt,

Thanks for the quick answer. I was affraid you would answer me such :) The arguments are at the hand of the end users, hence a relative timeout would have made sense. I suppose I'll have to go with a plugin.

Thank you for your assistance.
