### ISSUE TITLE
Is it necessary always to set the core pool size in HystrixThreadPoolDefault.touchConfig()

### ISSUE THREAD

**Issue by yanglifan** [Netflix/Hystrix#1245]
While creating a HystrixCommand, a thread pool will be acquired and `HystrixThreadPoolDefault.touchConfig()` will be executed by default. In `HystrixThreadPoolDefault.touchConfig()`, `threadPool.setCorePoolSize(dynamicCoreSize)` will be executed.

In Java 6, `threadPool.setCorePoolSize(dynamicCoreSize)` will execute a lock operation all the time. That is negative for the performance and sometimes in the high load scenario will cause a live lock issue.

In Java 7 & 8, if the max size is greater than the core size (it is not the default scenario, but someone can have the custom thread pool), the idle worker threads will be interrupted. I think it is unnecessary if the core pool size is not changed.

So I think before execute `setCorePoolSize`, the new core pool size should be compared the original one to decide the necessity of the execution of `setCorePoolSize`

**Comment by mattrjacobs** [comment]
I didn't know either of those facts - thanks for bringing this up!  Your proposal sounds like a good one.  Are you interested in submitting a PR?  I'm happy to review, if so.  Otherwise, I can get to it before I cut the next release.

**Comment by yanglifan** [comment]
I have created a [PR](https://github.com/Netflix/Hystrix/pull/1247)

**Comment by yanglifan** [comment]
The change was very simple but it caused the CI to be failed.  I will check the reason, but it will be great if you could have a look.

**Comment by mattrjacobs** [comment]
Merged PR, looking at flaky unit tests now

**Comment by yanglifan** [comment]
#1247
