### ISSUE TITLE
Unable to (reasonably) override command configuration sources in a properties plugin

### ISSUE THREAD

**Issue by wg-tsuereth** [Netflix/Hystrix#1249]
Related to #1248, I attempted to shoehorn-in support for archaius2 by writing a `HystrixPropertiesStrategy` plugin.

By implementing a strategy for my plugin (i.e. `HystrixPropertiesStrategyArchaius2`), I'm able to point `getCommandProperties` calls to a custom implementation of `HystrixCommandProperties`.  However, in my properties implementation (i.e. `HystrixCommandPropertiesArchaius2`), I can't override the generic `getProperty` methods, because they are private to the parent class.

To use an alternate configuration source for command properties, I would be forced to override every individual getter method in `HystrixCommandProperties`, which - aside from being silly and tedious - means that my implementation breaks if command properties are removed or modified in future Hystrix versions, and will break _invisibly_ if command properties are added in the future.

If the `getProperty` methods in `HystrixCommandProperties` were public or protected, it would be much simpler to implement a command properties plugin to use an alternate configuration source.

**Comment by agentgt** [comment]
You don't want to mess with `HystrixPropertiesStrategy` plugin but rather `HystrixDynamicProperties`.

An example implementation is in fact the [`system properties one`]( https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/strategy/properties/HystrixDynamicPropertiesSystemProperties.java). I need to talk to @mattrjacobs about updating the wiki but you should be able to plugin what ever configuration system so long as you exclude old archaius jar from the classpath or override it (see javadoc on `HystrixPlugins`.

**Comment by wg-tsuereth** [comment]
Thanks for pointing this out, @agentgt -- `HystrixDynamicProperties` looks like exactly what I wanted to use (should have been using).

Please do have the wiki updated, since the Plugins page is what sent me down the `HystrixPropertiesStrategy` rabbit-hole.
