### ISSUE TITLE
threadpool configuration

### ISSUE THREAD

**Issue by lcf** [Netflix/Hystrix#1256]
We've been having issues with configuration of the threadpool as per Hystrix recommendations:

> requests per second at peak when healthy × 99th percentile latency in seconds + some breathing room

For example:
we suddenly get double the traffic - some marketing effort worked - all our infrastructure scales out automatically due to continued high utilization of Memory and CPU. However some requests to a remote dependency from our machine will be cut off because of the Hystrix thread pool configuration, for no good reason.

1. The dependency itself is healthy and is responding in accordance with its SLA (otherwise the circuit breaker would kick in)
2. The machine itself has enough memory and computing power to handle the increased traffic. 

Why isn't this taken into account in the formula above?

The bulkhead pattern protection seems nice, but what should be protected? We ended up having only the protection that comes from Hystrix Threadpool size limit. However, things that are actually CPU and Memory intensive that will really kill the machine in case of e.g increased traffic - those things may not even have a network call involved. That is sure our problem and not Hystrix's, but that brings a question - is it wise to apply bulkhead pattern to all Hystrix threadpools? 

The formula makes sense if nothing changes and there is a fixed number of instances, but is very hard to maintain for multiple services running on multiple machines each having dozens of hystrix threadpools. I wonder if we're missing something important or whether the documentation can be updated to explain the logic behind that a little better. I would appreciate any advice.

**Comment by mattrjacobs** [comment]
I think there are a few things worth discussing in the example you bring up.

1.  The advice you mentioned is a guideline.  The intent is to get you to a threadpool size that allows very close to 100% of traffic through in steady-state, but actually does reject when the backend latency increases.  It's a guideline, and some distributions of command arrival time and latency may not work well for that guideline.

2. IMO it is wise to apply a bulkhead to all Hystrix threadpools.  I don't think Hystrix should be used for non-IO work.  There's nothing stopping you, but most of Hystrix's value is in preventing runaway IO from killing your system.  So, if all Hystrix commands are IO, then I think it makes sense to use a bound on the concurrency by using a fixed-size threadpool.  If you don't, then experience has taught us that application threads are liable to get stuck doing unwanted IO at the worst possible times.

3. Our deployment topology is very dynamic.  We autoscale most of our services by an order of magnitude through the day.  We have enough traffic, though, that each box has an incoming RPS that's relatively constant throughout the day.  If you're in a case where an individual box has very different incoming RPS throughout the day, then I think you should use the max RPS characteristics to tune.  So tune for the worst-case, and don't adjust it down with lower RPS.  If your service can't get in trouble with threadpool Foo sized to 5, then setting it to 4 is only very slightly better.

Hope that helps, and happy to answer any followups

**Comment by lcf** [comment]
thank you @mattrjacobs. 

Could you elaborate on the intent a little more, please:

>  The intent is to get you to a threadpool size that allows very close to 100% of traffic through in steady-state, but actually does reject when the backend latency increases.

I understood this is a guideline and may not fit everyone. Assuming a more typical set up like yours. Isn't the healthy latency controlled by the circuit breaker configuration? Given that the latency increases but within bounds as per CB configuration - why would you reject?

**Comment by mattrjacobs** [comment]
If Service A is making network calls to Service B with customer traffic, then 2 distributions emerge: the request rate of A->B, and the latency of this call.  The latency of the call is network time + time it takes service B to respond to the request.  Neither of those are properties of Service A, so we generally see that the latency is unrelated to any config on Service A.

Once we arrive at that steady state, we find a number of threads that doesn't reject too many commands ("too much" is command-specific).  Depending on the importance of the command and the quality of the fallback, a 10% rejection rate may be OK.  But it may be 1%, 0.1%, 0.01%, etc).  

The tradeoff here is that more threads in the pool prevent commands from getting rejected, but will all become saturated when Service B becomes latent.  The more unresponsive threads in your system, the worse your application will be when this outage occurs.  Put concretely, you could bound all thread pools to 1000 and prevent almost all rejection, but it would come at the cost of allowing too many threads to get tied up on a latent dependency.

**Comment by lcf** [comment]
If a dependency is latent to the point where it matters, shouldn't we count on Circuit Breaker for protection?

> Put concretely, you could bound all thread pools to 1000 and prevent almost all rejection, but it would come at the cost of allowing too many threads to get tied up on a latent dependency.

Given that we have enough resources on the machine to maintain 1000 threads for each thread pool - would it be okay to have that value set, you think? How much is too many is defined by how many the machine can handle, not by how often we call a dependency at the moment. Is that correct or am I still missing something.

**Comment by mattrjacobs** [comment]
Quick clarification on terminology: A circuit-breaker may short-circuit when its observed error rate rises to a certain level.  This is purely a property of error rate, not latency/concurrency.

The way that Hystrix bounds latency is:
1) Directly via timeouts
2) Indirectly by bounding thread pools (if a command gets latent, the bounded pool gets saturated and commands get rejected upon trying to claim a thread)

The problem with having unbounded thread pools (or with very high bounds) is that too much work gets queued up and the system can't achieve a steady state.  A steady state is one where the arrival rate of work that gets done is less than the completion rate of work.  

The way I think about this is in terms of a distribution of threads being used.  At any point in time, a certain number of threads is used.  With enough samples, this becomes a distribution.  Consider this one, for sake of example:

| Threads  | Observations |
| ------------- | ------------- |
| 0  | 7  |
| 1 | 10 |
| 2 | 6 |
| 3 | 4 |
| 4 | 0 |
| 5 | 2 |
| 6 | 1 |

For example, we observed the thread pool as having one thread utilized 10 times (out of 30).  We can guess that if we set the thread pool to 5, then roughly 1/30 (3%) of requests would get rejected.  If we set the thread pool to 4, then roughly 3/30 (10%) of requests would get rejected.

The 2 factors which control this distribution are arrival rate (RPS in) and completion rate (command latency).  If RPS increases, then the thread pool becomes more utilized.  If latency increases, then the thread pool becomes more utilized.  

This article on [Little's Law](https://en.wikipedia.org/wiki/Little%27s_law) contains some good info and pointers to more background on queuing theory.

**Comment by lcf** [comment]
Thank you for the detailed explanation and the link. I see how the the law could be applied on the side of the dependency/server, but I can't quite understand yet how we can reason about arrival and completion rates _on the client_, what hystrix pool configuration essentially does.

We have no knowledge about other clients of the dependency at any given point in time. For example, another team releases a new feature and the dependency is called twice as often now. Or, dependency was scaled up and completion rate has doubled. I'd expect in any of these cases for all thread pools on all clients to be reconfigured. I guess that's not impossible, but in reality we've been having a really hard time maintaining those.

That said, assuming we have control over the dependency - the server we're calling. If we configure the dependency such that it rejects the excess of incoming requests that it cannot process and remain healthy - would that be okay to remove the upper bound on the client's thread pool, you think? Or would that still compromise the system in some way?

**Comment by mattrjacobs** [comment]
Yeah, in practice, as call patterns change and latencies move around, we often tweak our threadpool configs.  At the moment, we use [Atlas](https://github.com/Netflix/atlas) to store time-series data like threadpool completions/rejections and thread utilization.  We can set up alerts to determine if threadpool rejection is too high, or thread utilization is too low.

The problem with your suggestion is the unexpected case when your server goes latent.  When that happens, the number of threads doing I/O to that system will increase until they reach the bound of the threadpool.  The higher that is, the worse off your system will be.

**Comment by lcf** [comment]
Thanks for the Atlas suggestion. We use a different set of tools right now, but atlas is also available, I'll look into it.

> The problem with your suggestion is the unexpected case when your server goes latent. When that happens, the number of threads doing I/O to that system will increase until they reach the bound of the threadpool. The higher that is, the worse off your system will be.

I didn't get why the number of threads doing I/O would increase. Consider an example (actually the real numbers for one of our services):

We have a service with arrival rate of 1000 req per sec. It takes 0.1s to serve one request. Therefore as per the Little's law, the long-term average number of customers in a stable system is 1000 * 0.1 = one hundred.

We configure the service to only allow for 100 concurrent incoming requests to ensure the "steady state". We use jetty configuration for that, btw, also a thread pool.

Now, the service goes latent and it takes 0.2 to process a request on average. However as per our configuration we will reject any extra requests and the system will remain stable and the number of threads will still be ~100. Why do you say it would increase?

**Comment by mattrjacobs** [comment]
Atlas is just what we use.  Any sort of historical time-series DB should be adequate for these purposes.

In your case, when you have 100% assurances about how the remote system will behave, then you can rely on those guarantees to be less restrictive in the calling system.

Hystrix is designed for not having 100% assurances about the remote system or the client library calling it.  In the case where you don't own this client-server relationship, Hystrix helps by bounding the worst thing that can happen.  In your case, you have already bounded the worst case without Hystrix, so Hystrix may not be very valuable for your resiliency.

Good discussion - thanks for bringing this up.

**Comment by lcf** [comment]
Got it, that makes sense. Thank you.
