### ISSUE TITLE
Hystrix not fall properly

### ISSUE THREAD

**Issue by saboteurkid** [Netflix/Hystrix#1263]
Hi all,
I have a situation that I need to call an external service (in my case is RESTful)
[My Code](https://gist.github.com/saboteurkid/ed18b0f44aa0724d8884288cc12dac80)
If I understand properly, that after 20 times fail (by default), Hystrix should open the circuit, but in my case, it not. It cause me a lot trouble be cause the 3rd service quite bad and their downtime quite large.
Can anyone explain me where I do it wrong?
Thank in advance.
P/s: Sorry for my bad English.

**Comment by mattrjacobs** [comment]
For a circuit to open, 2 conditions need to be met:

1. Volume must be high enough.  This is controlled by config: https://github.com/Netflix/Hystrix/wiki/Configuration#circuitBreaker.requestVolumeThreshold

2. Error rate must be high enough.  This is controlled by config:
https://github.com/Netflix/Hystrix/wiki/Configuration#circuitbreakererrorthresholdpercentage

If you're seeing a command fail very frequently, but the circuit isn't opening, see what rate your command is executing at.  If you'd like it to open, then you might need to lower the volume threshold.

**Comment by saboteurkid** [comment]
Thank for these link. I've read it, but may be I'm not fully understand.
But when my code running, the Error/ Total percentage is stuck as 10/10 -100% when time out = 1sec.

In source code (it quite a complex code for me), Hystrix check the **Total error** vs **VolumeThreadhold** then check the error percentage. But in my case, the **Total error** not counting on (same for Total request).

Just wonder why it not counting on to 20, but stuck in 10?

**Comment by mattrjacobs** [comment]
The counters are all windowed, meaning they only track the last `n` seconds of metrics.  (The default is 10 seconds).  So as commands are executing, the new ones appear in the counter, and the metrics older than 10 seconds fall off.  

In your case, it sounds like you're observing a steady rate of 1 cmd/sec, so the counter for this command will alway contain 10 data points.
