### ISSUE TITLE
Wrong version in HystrixMetricsPoller @Deprecated comment

### ISSUE THREAD

**Issue by egormasalitin** [Netflix/Hystrix#1280]
[Here is comment](https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java#L57):
`@Deprecated //since 1.5.4`

But latest version is 1.5.3.

Is this is a mistake?

Thank you.

**Comment by mattrjacobs** [comment]
This is in master but unreleased.  Should be out soon.

**Comment by egormasalitin** [comment]
@mattrjacobs  I understood, that's why I closed it, thank you. What is approximate release date?

**Comment by mattrjacobs** [comment]
Should be in the next week or so

**Comment by egormasalitin** [comment]
@mattrjacobs  Thank you

**Comment by egormasalitin** [comment]
@mattrjacobs Any updates about `1.5.4` release?

**Comment by mattrjacobs** [comment]
Should be tomorrow.  Thanks for your patience
