### ISSUE TITLE
fallback is throwing HystrixRuntimeException only

### ISSUE THREAD

**Issue by vasuharish** [Netflix/Hystrix#1281]
In our project we have to catch the exception in the fallback method and throw business exception.

But while throwing HttpStatusCodeException , i am getting HttpStatusCodeException.

as fallback method failed

**Comment by mattrjacobs** [comment]
I don't understand your question.  What are you trying to do, what do you expect, and what are you observing?

**Comment by vasuharish** [comment]
sorry for being explained properly

i have method

@HystrixCommand(fallback=""defaultCall)
public XXX call(){
---
Business logic
----
}

private void defaultCall(Throwable exception){
throw new HttpClientErrorException(HttpStatus.BAD_REQUEST,
				"user Exception");
}

when ever fallback occurs, i am throwing HttpClientErrorException,but in the logs it is giving HystrixRuntimeException.

**Comment by mattrjacobs** [comment]
This is expected.  Exceptions that aren't generated by Hystrix itself are wrapped in a HystrixRuntimeException

**Comment by vasuharish** [comment]
Thank you, i got it now

**Comment by vasuharish** [comment]
Matt, need your help on one particular scenario, 

When ever any exception occurs fallback method will be called and we can catch exception adding throwable  class in the fallback method signature.

Once I catch the exception I am transforming the HystrixRuntimeException to HttpStatusCodeException and throwing HttpStatusCodeException inside fallback method.

But my controlleradvice got notified at the RuntimeException instead of HttpStatusCodeException. 

Even at the controller advice level at RuntimeException handler method I am again throwing business exception but still I am getting HystrixRuntimeException only. 

Is there anything I missed here in the config. Are is it expected, if expected we are stubbing all the business related exceptions here, which is not a idle scenario.
