### ISSUE TITLE
[hystrix-servo-metrics-publisher] Use command group key in servo metric name

### ISSUE THREAD

**Issue by sslavic** [Netflix/Hystrix#1284]
As documented [here](https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java#L276) and implemented [here](https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java#L78) only command key is used in metric name, but not the command group key. Please consider using command group key as well.

**Comment by mattrjacobs** [comment]
In practice, we (internally at Netflix) generally have descriptive enough command keys that this is unnecessary.  That could also be because we're working around this issue in an awkward way.  In your experience, are you defining key names that appear in multiple groups?

**Comment by sslavic** [comment]
No conflicts yet, just seemed that it's strange without group, would make more sense with group.command hierarchy. I guess it wouldn't hurt if it was made to include group segment as optional, defaulting to command key only for backward compatibility.

**Comment by mattrjacobs** [comment]
Yeah, that makes sense.   I think doing it this way from the beginning wold have been cleaner. 

I think one problem with adding this as a feature is that it would change all of the names of metrics sent to Servo and possibly break any metric consumers that are already in place.  So any change here would have to be opt-in.  The question is if it's worth it to add another configuration knob for this feature.  I lean no, but am willing to be convinced.

**Comment by sslavic** [comment]
I understand. Closing.
