### ISSUE TITLE
HystrixThreadPool.Factory.shutdown(timeout, unit) does not guarantee threadpool shuts-down

### ISSUE THREAD

**Issue by thesmith** [Netflix/Hystrix#1289]
The following code at https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java#L146 ignores the return value from awaitTermination called on the ThreadPoolExecutor.

    pool.getExecutor().awaitTermination(timeout, unit);

There's no guarantee that the executor has terminated. The message in the RuntimeException that is thrown if there's an InteruptedException indicates that the intention is to make sure the ThreadPool is properly shutdown, so I think this is an exceptional state.

Typically I would put this in a loop even though this somewhat changes the semantics of timeout / unit to be a frequency to check.

BTW this particularly causes problems in tests (where Hystrix.reset is called a lot) and there are Hystrix managed threads that get put to sleep a lot. My use-case is a Hystrix command that wraps the HTTP call to SQS, which lets you wait up to 20sec for a message.

**Comment by mattrjacobs** [comment]
Yeah, that makes sense to me, though we've never run into this in practice ourselves.  If it makes testing easier though, then that seems like a good change.  Would you like to submit a PR for this?  I'd be happy to review one.

**Comment by thesmith** [comment]
Created #1294. Travis doesn't seem to like me, so any help appreciated.

**Comment by mattrjacobs** [comment]
Closed via #1294
