### ISSUE TITLE
Dashboard not working when running on different servlet-path

### ISSUE THREAD

**Issue by tobiasamon** [Netflix/Hystrix#1291]
Hi,

I'm running a spring boot application with hystrix and hystrix-dashboard.
The spring boot application is running on a different servlet-path (in applicaition.yml -> server:servlet-path: /admin).
With this setting the hystrix dashboard can be reached under http://host:port/admin/hystrix. However the header image and the jquery javascript file cannot be found due to wrong paths (the servlet-path is not prepended).

**Comment by spencergibb** [comment]
Wrong repo to file. Use spring cloud Netflix
