### ISSUE TITLE
Circuit Breaker Keys Not Unique Enough By Default

### ISSUE THREAD

**Issue by ryanjbaxter** [Netflix/Hystrix#1293]
I have a situation that I have run into where the keys used to cache circuit breakers are not unique enough.  Because of this I have distinct Hystrix Commands that end up using the same circuit breaker object.

I traced the problem to this line of code
https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/HystrixCircuitBreaker.java#L77

I know by default the method name is used as the key.  In my case both hystrix commands are wrapping methods with the same name.  I also realize that you can customize the command name as well.  However I am wondering if the default behavior should try to be a little bit more creative in how the key is creative?  It is not terribly obvious that you might be running into this situation...

**Comment by mattrjacobs** [comment]
Are you using hystrix-javanica for annotations, or using vanilla Hystrix?  Internally, we use vanilla Hystrix where we create and instantiate subclasses of HystrixCommand/HystrixObservableCommand.  We don't really run into name collisions, and if we do, we explicitly set the command key in the constructor of the concrete subclass.  

Given that this already provides as much flexibility as possible, what other strategy do you have in mind?

**Comment by ryanjbaxter** [comment]
@mattrjacobs i responded over in the google group, let me know if you prefer to track this via a github issue instead.

**Comment by mattrjacobs** [comment]
Easiest for me in Github.  Repasting your comments here inline:

> I am coming at this from a Spring Cloud Netflix perspective.  We have a dependency on just Hystrix [1].  However we are using annotations (@HystrixCommand).  
> The easiest solution that comes to mind is instead of just the method name as the key, could we use the fully qualified class + method name?  
> [1] https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-dependencies/pom.xml#L23

**Comment by mattrjacobs** [comment]
>Digging into the code a little more my situation might be a bit more unique.
> What I have is a collision of circuit breaker cache keys from 2 different Hystrix Commands.  
> One command is created by using the @HystrixCommand annotation and the other is being created by Feign in one of my Feign Clients.  By default Feign will just use the method name as the cache key [1], same as Hystrix, but with Feign there is no way to customize the name.  That is a change in OpenFeign I think.
> However from a Hystrix point of view I am wondering if we can check if there is a command that is already cached when we are creating a new command with a given key and if so log some kind of warning about it?  That would at least give some kind of indication that there might be a problem.

[1] https://github.com/OpenFeign/feign/blob/master/hystrix/src/main/java/feign/hystrix/HystrixInvocationHandler.java#L90

**Comment by mattrjacobs** [comment]
Under the covers, the way that Hystrix works is to create an internal static cache of `HystrixCommandKey`s.  Whenever a command instance is created with a key that is equal to something already in the cache, then that command key-specific config is used for that command instance.

So the general pattern in Hystrix is to create a high volume of command instances, each of which either share a `HystrixCommandKey`, or create a new instance with a common name.  That is what you want to prevent (or warn on), and I don't know how you could reasonably tell the difference.

**Comment by ryanjbaxter** [comment]
@mattrjacobs so would multiple command instances commonly be created because there are multiple instances of the same app running which contains those commands?  How would the cache be shared across those instances?

**Comment by mattrjacobs** [comment]
Every command instance is single-use, so a single app will create many command instances.  Each command instance has a reference to a `HystrixCommandKey`.  Those keys are placed in a static data structure that is shared across the entire application.

**Comment by ryanjbaxter** [comment]
OK, but I don't understand what the use case is then for a single app instance using the same key for multiple hystrix commands.  Wouldn't the app want to direct all calls through a single hystrix protected method call instead of having multiple methods that are wrapped in the same hystrix command?

**Comment by mattrjacobs** [comment]
I think you've got the `hystrix-javanica` mental model.  

In Hystrix without Javanica, we construct command instances very frequently, and they are all single-use.  This is what Javanica is doing under the hood.

**Comment by ryanjbaxter** [comment]
OK I think I understand now, so in generic hystrix you are dynamically constructing  and running commands, so you could be creating multiple instances of the same command....and actually that might be quite common.  

I still think from a Feign point of view we can do a little better with our command names, so I will open an issue in OpenFeign to see if we can address that.  Thanks for the help Matt!
