### ISSUE TITLE
Is there any way to count particular types of error occurred this many times? 

### ISSUE THREAD

**Issue by ankit8051** [Netflix/Hystrix#1311]
I am using HystixObservable command in my rest client. I want to count the HttpServerErrorException occurred during rest operation. 

Thanks in advance.

**Comment by mattrjacobs** [comment]
Have you looked at the Wiki?

Hystrix generates a large amount of metrics, and you have many choices on how to consume them.  One such way is the Dashboard: https://github.com/Netflix/Hystrix/wiki/Dashboard
