### ISSUE TITLE
Difficulty propagating ThreadLocal from Servlet request to HystrixCommand

### ISSUE THREAD

**Issue by conorgriffin** [Netflix/Hystrix#1312]
I am using Zipkin Brave in my project and need to propagate the span data from `ThreadLocal` values in servlet request threads and pass them to a `HystrixCommand` that makes a call to another service so that the span data gets propagated from the inbound request to the outbound request.  I've attempted to do this by adding `HystrixRequestContext` in the `doFilter()` method as follows:
```
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        HystrixRequestContext hystrixRequestContext = HystrixRequestContext.initializeContext();
        try {
            super.doFilter(request, response, chain);
        } finally {
            hystrixRequestContext.shutdown();
        }
    }
```
My understanding was that if this thread creates a `HystrixCommand`, the `ThreadLocal` values would be copied from the servlet thread to the thread used by Hystrix to execute the `HystrixCommand`.  However this doesn't seem to be the case.  Have I missed a step or is there a different way I should be doing this?

**Comment by conorgriffin** [comment]
Actually I figured this out.  So my Servlet filter extends `BraveServletFilter` to capture the Zipkin request headers from the client request.  Then in my Servlet Filter constructor I register a custom concurrency strategy as follows:
```
HystrixPlugins.getInstance().registerConcurrencyStrategy(new ZipkinTracePreservingConcurrencyStrategy());
```

This class looks like this:
```
public class ZipkinTracePreservingConcurrencyStrategy extends HystrixConcurrencyStrategy {
    @Override
    public <T> Callable<T> wrapCallable(Callable<T> callable) {
        return new ZipkinContextCallable<T>(callable);
    }
}
```

So it just wraps the `Callable` Hystrix uses with my custom `ZipkinContextCallable` which looks like this:
```
public class ZipkinContextCallable<K> implements Callable<K> {

    private final BraveCallable<K> actual;

    public ZipkinContextCallable(Callable<K> actual) {
        this(HystrixPlugins.getInstance().getConcurrencyStrategy(), actual);
    }

    public ZipkinContextCallable(HystrixConcurrencyStrategy concurrencyStrategy, Callable<K> actual) {
        ServerSpanThreadBinder serverSpanThreadBinder = new Brave.Builder().build().serverSpanThreadBinder();
        this.actual = BraveCallable.create(actual, serverSpanThreadBinder);
    }

    @Override
    public K call() throws Exception {
        return actual.call();
    }
}
```

**Comment by mattrjacobs** [comment]
@conorgriffin You beat me to it!  We do a similar dance in internal applications
