### ISSUE TITLE
HystrixRequestContext initialization for @CacheResult

### ISSUE THREAD

**Issue by cicioflaviu** [Netflix/Hystrix#1314]
After requesting this method: 

```
    @RequestMapping(method = RequestMethod.GET)
    @CacheResult(cacheKeyMethod = "getAllProductsCacheKey")
    @HystrixCommand(fallbackMethod = "getAllProductsFallback")
    public Product[] getAllProducts() {
        ServiceInstance instance = loadBalancer.choose("product-service");
        return restTemplate.getForObject(instance.getUri() + "/products", Product[].class);
    }
```
it gives me :

> java.lang.IllegalStateException: Request caching is not available. Maybe you need to initialize the HystrixRequestContext?

After hours of searching I didn't found nothing that works, any advice?

**Comment by mattrjacobs** [comment]
So your method is creating an instance of HystrixCommand and executing it.  The `@CacheResult` annotation is trying to set up a request-cache for all executions of this command.  The request-cache will de-duplicate multiple executions of command instances which share a cache key in a single request.

For that to happen, the concept of a request-scope must be defined.  For Hystrix, it is `HystrixRequestContext`.  You need to delineate the start of a request with `HystrixRequestContext.initializeContext`.  That returns an instance of `HystrixRequestContext`.  When the request is done, you call `shutdown()` on that instance.

That should get you unblocked.  The Wiki has more info, like: https://github.com/Netflix/Hystrix/wiki/How-To-Use#Caching

**Comment by cicioflaviu** [comment]
So the following implementation should be correct?

```
    @RequestMapping(method = RequestMethod.GET)
    @HystrixCommand(fallbackMethod = "getAllProductsFallback")
    public Product[] getAllProducts() {
        Product[] p;
        HystrixRequestContext context = HystrixRequestContext.initializeContext();
        try{
            ServiceInstance instance = loadBalancer.choose("product-service");
            p = restTemplate.getForObject(instance.getUri() + "/products", Product[].class);
        } finally {
            context.shutdown();
        }
        return p;
    }
```

**Comment by mattrjacobs** [comment]
That implementation would, I think, fix the error you're seeing.  It wouldn't do any caching, though, so it's not the correct solution.

Before you go on, you should take a moment to read the linked Wiki and make sure that request-caching is appropriate for your use case.  Request-caching assumes that you've got a well-defined request-scope (a web-server request is a common example).  In that request, request-caching will de-duplicate the work of executing multiple commands with the same cache key.  The 2nd-nth commands will all get the result of the first.

A fairly common case is running a servlet-based web server, so you can see the [https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-request-servlet](`hystrix-request-context`) module for an example of how to add request-scoping to a servlet-based web server

**Comment by mukteshkrmishra** [comment]
:+1 for Matt.
