### ISSUE TITLE
Hystrix metrics are not getting populated

### ISSUE THREAD

**Issue by mukteshkrmishra** [Netflix/Hystrix#1315]
Question: (please mark is as label question)

@mattrjacobs ::

I have a requirement where I need to capture Hystrix metrics and send them to a backend persistent storage. Here is what I have done so far:

1)Created a jar and a listener which implements ServletContextListener (as we are dealing with container start/stop where Hystrix based service is deployed).

2) Inside listener registered a custom metrics publisher as a plugin to Hystrix. (Custom metrics publisher is extending HystrixMetricsPublisher class)

3) Created a custom observer to observe updated values in metrics ( CustomObserver is extending BaseMetricsObserver provide by servo.

4) Registered Custom observer in a poller to periodically poll values from Hystrix metrics.

5) Bundled this jar to web application (where actual call is being made)

However, it looks like Hystrix related metrics are not getting polled. Any idea what is going wrong here. (PS : I confirmed that Hystrix related events are being thrown as metrics using Stream servlet and in dashboard I can see various metrics).

**Comment by mukteshkrmishra** [comment]
Never mind I figured out what was the problem. Closing this.

**Comment by srinathpasupathi** [comment]
@mukteshkrmishra Can you please provide some insights on what was the fix for this issue?
