### ISSUE TITLE
disable hystrix at runtime

### ISSUE THREAD

**Issue by sumit1112** [Netflix/Hystrix#1316]
I am calling a service from hystrix command, and is trying to diable it at the runtime as and when required. For this I am using circuitBreaker.enabled still query is showing timeout and executing fallback. Please help if misunderstood something.

**Comment by mukteshkrmishra** [comment]
You can do ut using Archaius. The property mentioed above is not used for enabling disabling Hystrix.

**Comment by mattrjacobs** [comment]
See previous discussion here: #908
