### ISSUE TITLE
Better documentation of returned errors

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#1317]
A common Netflix-internal question is around what all the possible returned values/exceptions may be.  It's worth enumerating them concisely on the Wiki.

**Comment by mukteshkrmishra** [comment]
I was thinking to create categorized format for this. Your thoughts??

**Comment by mattrjacobs** [comment]
Can you explain a bit more what you mean?

**Comment by mukteshkrmishra** [comment]
@mattrjacobs : As in
1) what all exceptions can be wrapped in HystrixBadException and vice versa.
2) Which exceptionscan be ignore as errors

and so on...

**Comment by mattrjacobs** [comment]
I just added a table to https://github.com/Netflix/Hystrix/wiki/How-To-Use#ErrorPropagation describing what the exception instances look like to Hystrix users.  Would love any feedback on what would make this more usable (or PRs)
