### ISSUE TITLE
HystrixObservableCommand Semaphore never released

### ISSUE THREAD

**Issue by kennedyoliveira** [Netflix/Hystrix#1319]
Hello everyone, i want to ask an advice, because i tried alots of things to solve a problem and didn't have any luck.

My use case is the following, i have a service who will make a network call to a third party service, and get an imagem from there, with that image i'll process it and after return to the client. I want to use hystrix because the third party service can slow me down and even stop answering if it receive too many requests in a short period, so hystrix will help with that, and will be able to monitor too.
Currently i'm using Vertx, to do the network call, so it uses non block I/O, i created an HystrixObservableCommand and encapsulated the network call there, with it i shift the result to another Scheduler to manipulate it and after send to the client, the simplified version of the flow would be like that:

````
java
new HystrixObservableCommandWithNetworkCall(dependencies...)
.toObsevable()
.observeOn(Schedulers.computation())
.flatMap(imageProcessingService::processImage)
.subscribe(imageByteArray -> response.end(imageByteArray));
````

The problem is, after 10 requests, all i get is
````
16:02:54.533 [vert.x-eventloop-thread-0] DEBUG com.netflix.hystrix.AbstractCommand - HystrixCommand Execution Rejection by Semaphore.
````

I'm missing something?

The configuration is basic the default, with max 10 concurrent semaphores call.

**Comment by mattrjacobs** [comment]
What version of Hystrix are you using?  We encountered a problem with similar symptoms internally using 1.5.2 and the fix for that issue is in 1.5.3.

**Comment by kennedyoliveira** [comment]
@mattrjacobs, i already found the problem, i'm using `1.5.4`, shame on me, i did subscribe in the vertx http client like that:

````java
httpclient.get(bla bla bla stuff)
.subscribe(s::onNext, s::onError);
````

So it never finished because i never sent onCompleted... i really didn't know why i did that haha.
Anyway, thanks for you time, ... just pretend i didn't ask anything hahaha :D

**Comment by mattrjacobs** [comment]
No problem - glad it works!
