### ISSUE TITLE
version 1.5.4 doesn't work on JDK 7

### ISSUE THREAD

**Issue by caarlos0** [Netflix/Hystrix#1322]
When trying to upgrade from `1.4.23` to `1.5.4`, I started to get this error:

```
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
```

The issue seems somewhat related to https://github.com/Netflix/Hystrix/pull/359 and the issue seems to be described [here](https://gist.github.com/AlainODea/1375759b8720a3f9f094).

FWIW version `1.5.3` works.

**Comment by mattrjacobs** [comment]
Thanks for the report.  I switched the Jenkins build to JDK8, since the new hystrix-reactivesocket modules require JDK8.  Looks like I can't do that for the entire project.  

I will remove those modules and republish with JDK7 (lowest-supported version in Jenkins).

**Comment by caarlos0** [comment]
@mattrjacobs nice, thanks!

**Comment by mattrjacobs** [comment]
I just released 1.5.5.  Can you try that and verify you're fixed?

**Comment by caarlos0** [comment]
@mattrjacobs yeah, just fired a build... I'l report in like half a hour...

**Comment by caarlos0** [comment]
@mattrjacobs worked, thanks!

**Comment by caarlos0** [comment]
Can I close this?

**Comment by mattrjacobs** [comment]
Yes, thanks
