### ISSUE TITLE
Long running or hanging onNext causes semaphore pool to be exhausted

### ISSUE THREAD

**Issue by OskarKjellin** [Netflix/Hystrix#1332]
I'm not sure if this is by design or not, but for me it kinda feels off.

We had an issue where the code in our onNext due to an unrelated issue hanged forever for some of the instances of the command. This causes after a while the semaphore count for all instances of that command to be broken.

I thought the idea of the hystrix command pattern was to protect the code inside the command, not the part outside?

Sample code to reproduce:

```
        AtomicInteger runningRequest = new AtomicInteger();

        for (int i = 0; i < 11; i++)
        {
            System.out.println("Currently running " + runningRequest.getAndIncrement() + " requests. Sending request " + i);
            new HystrixObservableCommand<Void>(HystrixObservableCommand.Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("group"))
                    .andCommandKey(HystrixCommandKey.Factory.asKey("command")))
            {
                @Override
                protected Observable<Void> construct()
                {
                    return Observable.timer(1, TimeUnit.MILLISECONDS).map(ignore -> (Void) null).observeOn(Schedulers.io());
                }
            }.observe()
                    .subscribe((v) ->
                    {
                        runningRequest.decrementAndGet();
                        try
                        {
                            //Wait forever
                            new CountDownLatch(1).await();
                        }
                        catch (InterruptedException e)
                        {
                            e.printStackTrace();
                        }
                    });
            Thread.sleep(100);
        }

```

**Comment by mattrjacobs** [comment]
The reason that Hystrix exists is to protect long-running applications from pieces of functionality which may fail/go latent.  There's nothing in the library to prevent failures - the expectation is that Hystrix will bound the worst case of these failures.

In your specific case, I would expect your operation to timeout and the caller to walk away with the fallback.  What do you expect?

**Comment by OskarKjellin** [comment]
Yes, I didn't mean to imply that it would actually prevent failures.

Well I wouldn't expect it to timeout, as it the code inside the command is actually fast. It's what the subscriber does that is bad, should that really affect the command?

In this case, the commands never timeout, and never decrease the semaphore count. 

Say we have 10 different usages of a command, and the command itself is OK, but one of the usage has a slow subscriber, that would cause the fast subscribers to not be able to use the command, even tho the code inside the command is actually fine (external service call with network).

**Comment by mattrjacobs** [comment]
Ah - I missed the subtlety that it was the consumer slowness causing the problem.  You can mitigate this problem somewhat by placing an `observeOn` after the `cmd.observe()`.  If you do this, then the only act of the Hystrix Command's onNext is to write its output to a buffer.  Then the Scheduler you specify in `observeOn` will pick up those values and propagate them downstream.

This, of course, then runs into other problems, as you'll exhaust that threadpool with your long-running work.  But this is a tradeoff you are free to make

**Comment by OskarKjellin** [comment]
Ah, indeed that solved the issue. 
I understand that stalling the consumer will eventually exhaust the threadpool, but there's really nothing that hystrix can do to prevent that.

Thanks a lot for the help, moving the observeOn outside the command instead of inside it made it act more as I wanted it to.
