### ISSUE TITLE
Metrics values are cached/Persisted 

### ISSUE THREAD

**Issue by mukteshkrmishra** [Netflix/Hystrix#1334]
HI,
I am trying to tap Hystrix metrics data using servo and publish into a queue for further processing.
However there is weird behavior observed ie: after the call via hystrix stopped despite of that HystrixMetrixServoPublisher publishes the data and PollRunnable polls and finds the metrics  [inside update(List<Metrics> lst) of BaseMetricObserver class)] (though no update/call being made via hystrix). For me it looks like data is being cached/persisted somewhere. 

Any help would be deeply appreciated.
@mattrjacobs

**Comment by mattrjacobs** [comment]
I don't think I follow.  For commands, the HystrixCommandMetrics object is passed to your metrics handler.  That object has 2 flavors of method: rolling metrics and cumulative metrics.  Rolling metrics track counters/latency over a rolling window of time and cumulative metrics track counters since the JVM start.

What's the specific behavior you're seeing, and what do you expect to see?

**Comment by mukteshkrmishra** [comment]
@mattrjacobs : We are using Hystrix_servo_metrics publisher and persisting those metrices to a backend. What we observed that even though we stopped making calls to backends via Hystrix, we continue to receive same set of metrices in Update method of MetricObserver( present in servo-core) with different time stamps.

Ie: Same data is being pushed over and over again with each poller run.

**Comment by mattrjacobs** [comment]
What is the specific metrics that you're pushing out?  For cumulative values, those never lose data, so I would expect them to stay the same even with no traffic.  I would expect rolling metrics to drop to 0 some period of time (the window size) after traffic dissipates.

**Comment by mukteshkrmishra** [comment]
@mattrjacobs : I am pulling out following metrics. Its a mixture of both rolling and cumulative. However, May I know the reason behind cumulative data to be present even after call drops to zero.

For command: 
propertyValue_circuitBreakerRequestVolumeThreshold": 4,
		"latencyExecute_percentile_25": 0,
		"countExceptionsThrown": 0,
		"countEmit": 0,
		"countResponsesFromCache": 0,
		"propertyValue_metricsRollingPercentileEnabled": true,
		"countCollapsedRequests": 0,
		"rollingCountBadRequests": 0,
		"propertyValue_executionIsolationStrategy": "THREAD",
		"rollingCountFailure": 0,
		"countTimeout": 0,
		"countShortCircuited": 0,
		"rollingCountSemaphoreRejected": 0,
		"propertyValue_rollingStatisticalWindowInMilliseconds": 10000,
		"rollingCountCollapsedRequests": 0,
		"rollingCountShortCircuited": 0,
		"latencyExecute_percentile_75": 0,
		"rollingCountEmit": 0,
		"countFallbackRejection": 0,
		"latencyTotal_percentile_5": 0,
		"propertyValue_executionIsolationSemaphoreMaxConcurrentRequests": 10,
		"errorPercentage": 0,
		"countFailure": 0,
		"executionSemaphorePermitsInUse": 0,
		"latencyTotal_percentile_75": 0,
		"propertyValue_requestCacheEnabled": true,
		"rollingCountFallbackRejection": 0,
		"propertyValue_requestLogEnabled": true,
		"currentTime": 1472677264215,
		"rollingCountFallbackEmit": 0,
		"commandGroup": "",
		"rollingCountSuccess": 10,
		"propertyValue_circuitBreakerErrorThresholdPercentage": 51,
		"propertyValue_circuitBreakerForceClosed": false,
		"countThreadPoolRejected": 0,
		"propertyValue_executionTimeoutInMilliseconds": 4000,
		"countSuccess": 10,
		"rollingCountFallbackFailure": 0,
		"rollingCountFallbackSuccess": 0,
		"latencyTotal_percentile_25": 0,
		"countSemaphoreRejected": 0,
		"latencyExecute_percentile_5": 0,
		"propertyValue_circuitBreakerForceOpen": false,
		"latencyTotal_mean": 0,
		"rollingCountResponsesFromCache": 0,
		"rollingCountTimeout": 0,
		"latencyExecute_percentile_995": 0,
		"rollingCountExceptionsThrown": 0,
		"countFallbackEmit": 0,
		"countFallbackFailure": 0,
		"latencyExecute_mean": 0,
		"isCircuitBreakerOpen": false,
		"latencyExecute_percentile_99": 0,
		"latencyTotal_percentile_995": 0,
		"propertyValue_circuitBreakerSleepWindowInMilliseconds": 2000,
		"latencyTotal_percentile_99": 0,
		"latencyTotal_percentile_50": 0,
		"rollingCountThreadPoolRejected": 0,
		"latencyExecute_percentile_90": 0,
		"latencyTotal_percentile_90": 0,
		"countFallbackSuccess": 0,
		"latencyExecute_percentile_50": 0,
		"propertyValue_fallbackIsolationSemaphoreMaxConcurrentRequests": 10,
		"countBadRequests": 0,
		"propertyValue_executionIsolationThreadTimeoutInMilliseconds":


For threadpool: 
"queueSize": 0,
		"largestPoolSize": ,
		"propertyValue_maxQueueSize": ,
		"currentTime":,
		"propertyValue_keepAliveTimeInMinutes": ,
		"threadActiveCount": ,
		"rollingMaxActiveThreads": ,
		"propertyValue_corePoolSize": ,
		"name": "",
		"rollingCountCommandsRejected": ,
		"totalTaskCount": 10,
		"completedTaskCount": 10,
		"propertyValue_queueSizeRejectionThreshold": 70,
		"countThreadsExecuted": 10,
		"rollingCountThreadsExecuted": 10

**Comment by mattrjacobs** [comment]
The window for rolling is a bounded amount of time (60s is the default).  The window for cumulative is infinite - it starts when the JVM starts and goes until the JVM stops.  Therefore, traffic leaving will not increase cumulative metrics anymore, just leave them at their current values.  Cumulative counters cannot go down.

**Comment by mukteshkrmishra** [comment]
Can't we reduce window for cumulative count as well? @mattrjacobs

**Comment by mattrjacobs** [comment]
Some metric systems use cumulative metrics and then back out what the rolling values are when displaying time-series.  If you don't want cumulative metrics, then you should use rolling metrics and set the window to your satisfaction.
