### ISSUE TITLE
How does hystrix cache work?

### ISSUE THREAD

**Issue by sandyjoins02** [Netflix/Hystrix#1337]
There is very little info given for Hystrix caching. Where does hystrix actually saves the cached data? How does the caching actually works? Any github code examples will be of great help.

@mattrjacobs

**Comment by mattrjacobs** [comment]
I'd love feedback on what is missing from your perspective in this doc: https://github.com/Netflix/Hystrix/wiki/How-To-Use#request-cache.

The Hystrix request cache uses a per-request in-memory cache to prevent commands with the same argument from being made multiple times.  Instead, the return value of the first command is shared by the 2nd-nth.

**Comment by 2BlackCoffees** [comment]
Hi, thanks for the good description. Just one question, it looks like caching can only be done for information that cannot be refreshed.
In all examples I could find the cached values is related to some parameters that will not change. 
Is there a way to cache information related to extracted information from another service ?
I would then expect that this other service would then inform the cache each time its information changed.
