### ISSUE TITLE
Shutting down Hystrix

### ISSUE THREAD

**Issue by mohan-mishra** [Netflix/Hystrix#1338]
Will there ever be a need to shutdown hystrix?? If yes, under what circumstances?
@mattrjacobs

**Comment by mattrjacobs** [comment]
I don't understand what you're attempting to do.  Hystrix is a library which will wrap existing calls you've got.

**Comment by mohan-mishra** [comment]
I have integrated hystrix.  I read at a few places that the best practice
is to shutdown hystrix as it creates threadpool. I want to know why and
when is shutdown required

**Comment by mattrjacobs** [comment]
Maybe pass along pointers to those sources?  I'm not clear on what you're trying to do.

**Comment by mohan-mishra** [comment]
What is the use of Hystrix.reset(). When is it supposed to be called. Is it
important to call this function?

**Comment by mattrjacobs** [comment]
The only place we use it is in unit tests to clear state between test runs

**Comment by mohan-mishra** [comment]
Okay. One more thing. There is a threadpool size for a command group which
means max concurrent requests that can be executed in that command group.

Is there any limitation on how many different commands(all belonging to
different group)  can be executed concurrently?

**Comment by mattrjacobs** [comment]
No, there's currently no global limit on how many commands can execute concurrently - just the bounded threadpool for the set of commands that run there.

**Comment by mohan-mishra** [comment]
Thanks Matt.

I just got over with integrating hystrix. The only thing I am unable to
follow is request caching. I get that we need to override one function in
hystrix command. But what should that function return? Should it return
always a same default hardcoded value?  And is there any other change
needed for enabling caching?

**Comment by mattrjacobs** [comment]
Please read this section of the Wiki: https://github.com/Netflix/Hystrix/wiki/How-To-Use#Caching.

If you have further questions, I'm happy to answer

**Comment by mohan-mishra** [comment]
Thanks. Exactly what I was looking for. Have posted two more questions as new issue. Will be glad if could find answers to them
