### ISSUE TITLE
Metrics Settings Doubt

### ISSUE THREAD

**Issue by kennedyoliveira** [Netflix/Hystrix#1339]
I'm using Hystrix with basically the default settings for metrics, but i want to understand it better, i'm not good at statistics so the configurations looks a little harsh to me, could someone explain what the settings are for, and how changing them affects the metrics and how to read better the information?

Maybe @mattrjacobs  could give a hand on this one? I like the way you elaborate your explanations.

**Comment by mattrjacobs** [comment]
For metrics, the main setting to be interested in is the window size:
https://github.com/Netflix/Hystrix/wiki/Configuration#metrics.rollingStats.timeInMilliseconds
https://github.com/Netflix/Hystrix/wiki/Configuration#metrics.rollingPercentile.timeInMilliseconds
https://github.com/Netflix/Hystrix/wiki/Configuration#metrics.healthSnapshot.intervalInMilliseconds

The first 2 control what scope the rolling metrics have.  So, for example, if you ask an instance of HystrixCommandMetrics for getRollingCount(SUCCESS), it will be the number of successes in the most recent window.  If you ask for the rollingExecutionLatencyPercentile(90), you will get the 90p latency over the most recent window size.

Does that help?

**Comment by kennedyoliveira** [comment]
@mattrjacobs a rolling window would be a period of time that the metrics will be recorded and after this period it would be reset?

**Comment by mattrjacobs** [comment]
Mostly yes, though there is also the notion of buckets within than rolling window.  If the window size is 60 seconds, and you have 10 buckets (of 6 seconds each), then every 6 seconds, a new rolling count gets calculated with the most recent 10 buckets

**Comment by kennedyoliveira** [comment]
@mattrjacobs i didn't understand the concept of buckets with the rolling window, could you elaborate a little more?

Also, could you answer some more doubts, like, how increasing the window size will affect the results? How increasing the number os buckets will affect the results?

Sorry if i'm asking noob questions, it's a new concept to me, and i hope you have patience to explain a little further.

**Comment by mattrjacobs** [comment]
No problem.  I think the graphics here are more illustrative of the concept: https://github.com/Netflix/Hystrix/wiki/Configuration#metrics

There is a larger window size that is the total amount of time for which we want to aggregate metrics for.  Within that, we divide it up so that we don't have to recalculate the metrics state on each new metric event.  Rather, we recalculate on bucket boundaries so that we bound the amount of work Hystrix has to do while still giving low-latency metrics

**Comment by kennedyoliveira** [comment]
Humm i guess i understand better now, so, based on your first example 60 secs with 10 buckets (6 secs per buckets), after passing 6 secs the last bucket will be dropped and a new one will be created, i got it right or still lost? haha

**Comment by mattrjacobs** [comment]
You got it 👍

**Comment by kennedyoliveira** [comment]
Thank you @mattrjacobs, so what happens with the aggregate metrics as i increase any of these settings? what are the implications? why would i need to increase the bucket size ou the window?

**Comment by mattrjacobs** [comment]
If you use a larger time window, then each individual metric affects the aggregate less.  So the system is slower to react to a change in the underlying state.  However, it is more robust against randomness  (Distributed systems can't work at 100%)

If you use more buckets, then the aggregate gets computed more frequently.  This is more precise, but more expensive in terms of CPU.

**Comment by kennedyoliveira** [comment]
got it, thank you very much @mattrjacobs!
