### ISSUE TITLE
Getting the response time in case of successful command execution

### ISSUE THREAD

**Issue by mohan-mishra** [Netflix/Hystrix#1343]
@mattrjacobs 

Any idea on how can we fetch the response time(execution time) of a successfully executed hystrix command. In the fallback I am using executionResult.getExecutionLatency(). This function returns -1 in the case of successful execution.

**Comment by mohan-mishra** [comment]
@benjchristensen

**Comment by mattrjacobs** [comment]
I'll have to dig a bit to understand that exact method call, but one method which should work within a fallback is:

`this.getExecutionTimeInMilliseconds()`

I added a println to the fallback of some of the unit-test commands, and this worked as expected.

**Comment by mohan-mishra** [comment]
getExecutionLatency is working in the fallback but not in case of
successful execution in the run() method

**Comment by mattrjacobs** [comment]
Right, the latency only gets recorded at the end of the run() method, since that when the latency is known.  How would you expect this to behave?

**Comment by mohan-mishra** [comment]
But inside the run method when the response object is available to us,
shouldn't the execution time be available?

Or is there any method to which execution goes when successful... Something
opposite to fallback.

Or the only option left is to calculate the time difference when control is
returned to the calling statement.

Your views on this?

**Comment by mattrjacobs** [comment]
The run() method is what's being measured.

If your use case is just to log the execution time of the command, just call cmd.getExecutionTimeInMilliseconds() anywhere outside of the command.

Individual command latency is also available in the HystrixRequestLog (which uses .getExecutionTimeInMilliseconds())

**Comment by mohan-mishra** [comment]
currentRequestLog is coming as null.

This is the way I have made my Setter

`Setter
                .withGroupKey(HystrixCommandGroupKey.Factory.asKey(commandGroup.getName()))
                .andCommandKey(HystrixCommandKey.Factory.asKey(commandGroup.getName() + "_" + commandKey.name()))
                .andCommandPropertiesDefaults(
                        HystrixCommandProperties.Setter().withMetricsRollingStatisticalWindowInMilliseconds(200000)
                                .withRequestLogEnabled(true));`

**Comment by mattrjacobs** [comment]
OK, this is a separate issue where you don't have your HystrixRequestContext setup.  Please see a previous answer I gave you around request-caching to get that set up properly.

In any case, the HystrixRequestLog is just an example.  Any time after the command executes, you can get its latency via .getExecutionTimeInMilliseconds().

**Comment by sanjibpramanick** [comment]
Hi Matt,

Could you please let me know the type of the reference used in this snip, cmd.getExecutionTimeInMilliseconds()

Also, how it would be available in the run method where I am overriding with my own logic.

Thanking in advance.
