### ISSUE TITLE
HystrixObservableCommand.Setter missing setter method for threadPoolKey?

### ISSUE THREAD

**Issue by vlad-tealium** [Netflix/Hystrix#1348]
At first glance it appears HystrixObservableCommand.Setter is missing setter method for protected class variable HystrixThreadPoolKey threadPoolKey? Note: HystrixCommand.Setter does have one "andThreadPoolKey".

If true, is the work around to create a HystrixCommand with a ThreadPoolKey and convert it to its Observable version?

**Comment by mattrjacobs** [comment]
Using thread-isolation for HystrixObservableCommand is not the right thing to do.  It will be deprecated and eventually removed (see #1200 / #1264 / #1228 for previous discussions)
