### ISSUE TITLE
Usage of hystrix

### ISSUE THREAD

**Issue by mohamedanees** [Netflix/Hystrix#1359]
@mattrjacobs 
I am new to Hystrix and would like to know the possibility of configuring hystrix in such a way to suit my scneario. If yes,Kindly advise

Starting many threads at point A which individually has many API calls.(Using Future)

While any Thread X is executing,I have used Hystrix for short-circuiting an API call (say create session with a specific CommandKey and Login with another CommandKey etc. but all API calls inside a particular thread is in same CommandGroup)

Now when a particular API call is failing (say,create session call alone. Login and other API calls are working just fine),Is it possible to short circuit the creation of thread itself at point A by implementing Hystrix there?

**Comment by mohamedanees** [comment]
Or...Is it possible to shortcircuit an entire CommandGroup if a specific commandKey(s) fail?

**Comment by mattrjacobs** [comment]
Let me restate your question to make sure I understand...

You're creating application threads and on each of them, doing I/O work like CreateSession/Login that hits another service.  Your question is if you can prevent the creation of the thread in the first place.

Let me know if I got that right.

If I did, then I would suggest that you let Hystrix manage the threads for you.  If you do that, then a short-circuit never runs on a Hystrix thread.  As a concrete example, we often write code in which application threads (like a Tomcat thread) calls command.queue() or command.observe() to get back a nonblocking handle on the work done by the command.  If the command gets latent, the Tomcat thread is protected.  If the command short-circuits, then the I/O work never gets run, and the Hystrix thread does not get involved.

Hope that helps!

**Comment by mohamedanees** [comment]
Awesome @mattrjacobs !! Thank you 👍
