### ISSUE TITLE
Keys in Hystrix Collapser metrics

### ISSUE THREAD

**Issue by mukteshkrmishra** [Netflix/Hystrix#1361]
Hi,

I wanted to know what all keys are been exposed by Hystrix Collapser metrics as of now.

(For eg: Hystrix Threadpool throws following keys:
"name", "currentTime","threadActiveCount", "completedTaskCount", "largestPoolSize", "totalTaskCount", "queueSize","rollingMaxActiveThreads", "countThreadsExecuted", "rollingCountThreadsExecuted","rollingCountCommandsRejected", "propertyValue_corePoolSize", "propertyValue_keepAliveTimeInMinutes","propertyValue_queueSizeRejectionThreshold", "propertyValue_maxQueueSize" via Rolling or cumulative data).

**Comment by mattrjacobs** [comment]
```
name
currentTime
rollingCountRequestsBatched
rollingCountBatches
rollingCountResponsesFromCache
batchSize_mean
batchSize
propertyValue_requestCacheEnabled
propertyValue_maxRequestsInBatch
propertyValue_timerDelayInMilliseconds
```

**Comment by mukteshkrmishra** [comment]
Thanks!
