### ISSUE TITLE
Configuring hystrix thread pool for a system with high RPS and 99%ile response time ~500ms

### ISSUE THREAD

**Issue by sahil441** [Netflix/Hystrix#1362]
As per hystrix docs thread pool should be configured using below formula :

ThreadPoolSize = requests per second at peak when healthy × 99th percentile latency in seconds + some breathing room

We have an external service whose 99%ile response time is ~500ms and expected RPS is 200. so with the formulae the thread pool size comes out to be 100. I don't think it is a good idea to configure thread pool with such a high number.

Please suggest what can be done in this scenario. What should be the ideal value for thread pool size and queue.

**Comment by mattrjacobs** [comment]
Consider what you would do without Hystrix.  You didn't provide the mean response time, so I'll guesstimate and say it is 100ms.  In that case, by [Little's Law](https://en.wikipedia.org/wiki/Little%27s_law), your mean utilization = (0.1 s) * (200 rps) = 20 requests.  That's just the mean, so it will burst much higher than 20.  So you'll be using a large number of threads, whether they are Hystrix or not.

The formula above is just an estimate.  You can always just move the number around until you get to a rejection rate you're comfortable with.  Making up a few numbers - maybe you're OK with a threadpool of 30 and a rejection rate of 4%, or maybe you need to increase it to 80 to get it down to 1%.  Your specific circumstances dictate that decision.

**Comment by sahil441** [comment]
Thanks for the response ! But let's say i made the thread pool size for the particular service to 100 and my other external calls are also wrapped using hystrix, having thread pool configured for each group. Will it impact my system in a bad way to have multiple thread pools with combined core pool size on the higher end ?

**Comment by mattrjacobs** [comment]
It's impossible for me to say without knowing more about your system.  For you, it's probably worth evaluating system performance with and without Hystrix and determining the answer for yourself.

One other note, I'm working on #1242, which will provide the capability to set different core/maximum threadpool sizes.  Once this lands in a release, you'll be able to do something like set up a pool of coreSize=10, maximumSize=100.  Then you would start with 10 threads, and burst up to 100 when necessary.  If those threads were unnecessary, they would be cleaned up.

**Comment by sahil441** [comment]
Thanks Matt!

Regards,
Sahil Gupta
