### ISSUE TITLE
Cleaner error propagation in hystrix core

### ISSUE THREAD

**Issue by tjuchniewicz** [Netflix/Hystrix#1366]
This is continuation of https://github.com/Netflix/Hystrix/issues/241 which was implemented only in Javanica? Why not in Hystrix core?

**Comment by mattrjacobs** [comment]
1.  No one has asked for it, and it's not a use-case we've needed internally
2. Javanica is annotation-based and annotations are a natural fit for a solution here.

**Comment by tjuchniewicz** [comment]
OK. So now we have one person asking for it ;-)
I've prepared fix in my private branch which solves my problem but I'm not sure if it is right place for this enhancement.

**Comment by mattrjacobs** [comment]
I'm happy to take a look at a PR and we can see how it would work within hystrix-core.

**Comment by tjuchniewicz** [comment]
Please take a look at PR: https://github.com/Netflix/Hystrix/pull/1379

**Comment by mattrjacobs** [comment]
I think this has been addressed via a review of #1379, which was eventually subsumed by #1414.  Please reopen if there's more to discuss

**Comment by tjuchniewicz** [comment]
Yes. https://github.com/Netflix/Hystrix/pull/1414 fixed my case. Special thanks to @tbvh !
