### ISSUE TITLE
Fate of idle threads when thread pool size is changed

### ISSUE THREAD

**Issue by mohan-mishra** [Netflix/Hystrix#1367]
@mattrjacobs Let's say we had assigned a core size of 100 to a particular hystrix command. And all the 100 have been consumed atleast once. Now say there are 20 requests being served so the rest 80 threads are in idle state. Now if I change the core size to 20 (without server restart), what will happen to the 80 threads which were in idle state

**Comment by mattrjacobs** [comment]
This calls `ThreadPoolExecutor.setMaximumPoolSize`.

According to the Javadoc there:

```
Sets the maximum allowed number of threads. This overrides any
value set in the constructor. If the new value is smaller than
the current value, excess existing threads will be
terminated when they next become idle.
```
