### ISSUE TITLE
Question: Failure percentage

### ISSUE THREAD

**Issue by aliostad** [Netflix/Hystrix#1374]
Hi,

It is not clear from the documentation whether the failure threshold is for buckets (i.e. percentage of buckets that are deemed failed) or total requests - and if it is for buckets, then does Hysterix trip open on the first bad bucket or applies extra logic.
 
If I get the answer, I can send a PR for an update in documentation clarifying this point.

Thanks for great work

**Comment by mattrjacobs** [comment]
Thanks for the kind words, @aliostad .  

The failure percentage is determined by looking at all current buckets, and then summing successes/failures across all buckets.

Happy to review a PR for the docs - much appreciated!

**Comment by aliostad** [comment]
Thank you so much! 

Now I am afraid there is another question here, why even bother about having buckets? Is this an implementation detail mainly to help with performance and rolling active stats?

**Comment by mattrjacobs** [comment]
Yes, exactly.  Rather than recalculate the aggregate error percentage every time a metrics gets added, we recalculate only when the timer elapsed, and one bucket leaves the set and a new one gets added.  Purely a performance optimization.

**Comment by aliostad** [comment]
Awesome. I will close the issue and send a PR to docs.

**Please do not feel obliged to accept it**. Feel free to accept, reject or accept and modify. Once again thank you for all the work.

**Comment by aliostad** [comment]
Ah... I do not seem to be able to send a PR for wiki :/
I forked but wiki is empty.

**Comment by mattrjacobs** [comment]
Are you able to clone via: https://github.com/Netflix/Hystrix.wiki.git, and submit a PR on that?  I got that link from https://github.com/Netflix/Hystrix/wiki
