### ISSUE TITLE
Hystrix properties inside a jee server

### ISSUE THREAD

**Issue by tdit** [Netflix/Hystrix#1378]
I'm using hystrix inside a jboss eap 6 and set different properties for different hystrix commands:
Command 1:
```
private static final Setter cachedSetter = Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("commandOne"))            
.andCommandPropertiesDefaults(HystrixCommandProperties.Setter().withExecutionTimeoutInMilliseconds(1000))
            
.andThreadPoolPropertiesDefaults(HystrixThreadPoolProperties.Setter().withCoreSize(20))
      .andThreadPoolPropertiesDefaults(HystrixThreadPoolProperties.Setter().withMaxQueueSize(20));
```
Command 2:
```
private static final Setter cachedFallbackSetter = Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("commandTwo"))
            .andCommandPropertiesDefaults(HystrixCommandProperties.Setter().withExecutionTimeoutInMilliseconds(4000))
            .andThreadPoolPropertiesDefaults(HystrixThreadPoolProperties.Setter().withCoreSize(10))
            .andThreadPoolPropertiesDefaults(HystrixThreadPoolProperties.Setter().withMaxQueueSize(10));
```

When i deploy it, there is no difference in timeout, core size and maxQueueSize... The Pool Size (equivalent to core size, i think) is shown in my dashboard with the value 1 and the queue size with 5. Is something missing or why does it not work?

**Comment by mukteshkrmishra** [comment]
It is working, try increasing load and then ramping ip your threads. You will see some difference.  Also you can verify by curling stream data directly.

**Comment by tdit** [comment]
The dashboard increases the numbers of queue and pool size with increasing load?
The differences in timeout behavoir was my fault, it is working now. Thank you :)

**Comment by mukteshkrmishra** [comment]
Glad it worked. What was the issue??

**Comment by tdit** [comment]
I never noticed that the value is always increasing when i call my remote service. The fallback settings was 4 seconds but i forgot that i first wait 3 seconds before i call again my remote service. So 1+3 = 4 seconds (timeout was 4 seconds) and that was the reason why the second command also failed
