### ISSUE TITLE
Hystrix Javanica - Reactive async execution - How to use Hystrix thread pool so that it shows up in dashboard

### ISSUE THREAD

**Issue by codependent** [Netflix/Hystrix#1384]
I am using Hystrix Javanica in a plain Spring Boot application this way:

	@RequestMapping(value="/hystrix/data", method=RequestMethod.GET, produces="application/json")
	@ApiOperation(value = "Gets data hystrix", notes="Gets data asynchronously with hystrix")
	@ApiResponses(value={@ApiResponse(code=200, message="OK")})
	public Single<List<Data>> getDataHystrix(){
		Observable<List<Data>> observable = dataService.loadDataHystrix();
		return observable.toSingle().subscribeOn(Schedulers.io());
	}

The service is as follows:

	@HystrixCommand(observableExecutionMode=ObservableExecutionMode.LAZY, fallbackMethod="loadDataHystrixFallback")
	@Override
	public Observable<List<Data>> loadDataHystrix() {
		double random = Math.random();
		return Observable.fromCallable(() -> generateData( random < 0.5 ? false : true ));
	}

Apart from being reactive (using observable) I want the execution to be asynchronous, so I need to subscribeOn a scheduler.

The point is that since I am using Schedulers.io(), in the hystrix dashboard I see the information regarding the circuit but not the thread pool. I haven't seen in the documentation how to make the reactive invocation use the hystrix thread pool.

**Comment by mattrjacobs** [comment]
See https://github.com/Netflix/Hystrix/wiki/FAQ%20:%20Operational.  If you are using reactive execution, the assumption is that the work you're wrapping with Hystrix is already async.  If that's the case, then using a threadpool doesn't get you anything, therefore it is not supported.

**Comment by codependent** [comment]
@mattrjacobs thanks for the link, perfectly clear now. It's a pity we can't monitor the Observable's thread pools with the dashboard, but can't have it all :-)

**Comment by mattrjacobs** [comment]
Just to be clear, those Observables may not have a threadpool.  They may come directly from Java NIO, for example.  For a `HystrixObservableCommand`, the idea is that Hystrix will let you provide the asynchronicity however you would like, and then apply the bounded worst-case semantics that comprise Hystrix.

**Comment by codependent** [comment]
> If you are using reactive execution, the assumption is that the work you're wrapping with Hystrix is already async

The most usual scenario I'm facing is wrapping an Observable that invokes a REST service using a RestTemplate. Since this invocation is blocking and I had to provide the asynchronicity with subscribeOn using Schedulers.io()'s thread pool I wondered if we could asign instead the [thread pool used by Hystrix commands](http://netflix.github.io/Hystrix/javadoc/index.html?com/netflix/hystrix/HystrixThreadPool.html) taking advantage of its configuration options and so on.

Anyway I get your point and appreciate your explanation.
