### ISSUE TITLE
Performance problema in EnvUtils.isCompileWeaving()

### ISSUE THREAD

**Issue by ricardoletgo** [Netflix/Hystrix#1387]
I have done some performance test and maybe I found a little problem in EnvUtils.isCompileWeaving(). 

`

    public static WeavingMode getWeavingMode() {
        String wavingModeParam = System.getProperty("weavingMode", WeavingMode.RUNTIME.name()).toUpperCase();
        try {
            return WeavingMode.valueOf(wavingModeParam);
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("wrong 'weavingMode' property, supported: " + Arrays.toString(WeavingMode.values()) + ", actual = " + wavingModeParam, e);
        }
    }

    public static boolean isCompileWeaving() {
        return WeavingMode.COMPILE == getWeavingMode();
    }

`
Each time "@HystrixCommand" is invoked, EnvUtils.isCompileWeaving () reads a System.property and my profile program shows that is a bottleneck.

Maybe a better option is to read this property only one time, inside a static initializer block for example.

`

    private static String wavingModeParam;	 
static {
		 wavingModeParam = System.getProperty("weavingMode", WeavingMode.RUNTIME.name()).toUpperCase();
	 }
`

Next a screenshot from my profiler tool, showing the problem.

![captura de pantalla de 2016-10-18 12-55-33](https://cloud.githubusercontent.com/assets/22148155/19474989/393431c0-9532-11e6-9dea-7f309d1e585d.png)

**Comment by mattrjacobs** [comment]
Thanks for raising the issue, @ricardoletgo.  Your analysis seems sound to me.  Are you willing to submit a PR with this change?

**Comment by mukteshkrmishra** [comment]
👍 from my side, as this would be a small and a good change for me.

**Comment by dmgcodevil** [comment]
CTW is supported and works fine but we have some problems to release separate artifact with the aspects compiled using ajc. Removing those logic might be tricky so @ricardoletgo's solution is better.

**Comment by ricardoletgo** [comment]
I made a pull request:
https://github.com/Netflix/Hystrix/pull/1393

**Comment by dmgcodevil** [comment]
@ricardoletgo could you please share your performance test project? I was reasoning about performance measurement, it's really important to know javanica performance vs. vanilla hystrix. with eyes closed I can mention a couple of places for performance optimizations but it would be great to know the numbers first.

**Comment by mattrjacobs** [comment]
Closed via #1393
