### ISSUE TITLE
Why buckets in metrics

### ISSUE THREAD

**Issue by LucasHCruz** [Netflix/Hystrix#1394]
Hi, I'm new in Hystrix and all concepts about resilient software, bulkhead, circuit breaker and etc...

I read the wiki and I'm in doubt with buckets within metrics!!

Why use buckets and not total value at all?
Why Hystrix used buckets?

Ps.: I don't know if I need to put some tag or simbol in subject.. so I apologize.

**Comment by mattrjacobs** [comment]
In our system, writes to metrics happen at the volume of command executions, which is in the 1000s of executions/second on a single instance.  If we were to re-calculate the aggregate view of metrics every time a single metric was received, this would be prohibitively expensive.  Instead, we've found that putting metrics into time-buckets allows us to only recalculate aggregate metrics on bucket boundaries without sacrificing much accuracy.  So this is purely a performance optimization (though necessary in our case)

**Comment by LucasHCruz** [comment]
Thanks for the answer... so I can put 360000/1 to recalculate after 1 hour is this right?

But I believe this isn't a good practice.... is this right too?

**Comment by mattrjacobs** [comment]
The reason that these metrics exist is to provide insight into the running system.  An hour is too late to be operationally useful.  We find the defaults of metrics updating every second or so to be adequate for alerting purposes.

**Comment by LucasHCruz** [comment]
Ok.. thanks man

**Comment by mattrjacobs** [comment]
Closing unless you've got more to discuss.  Please re-open if so.
