### ISSUE TITLE
Why is Hystrix not stopping server process even after timeout

### ISSUE THREAD

**Issue by gauravkandpal** [Netflix/Hystrix#1398]
I've used javanica and hystrix to put circuit breaker on the dependencies that my REST service calls. I've put a timeout of 1 sec which works just fine i.e the service returns gateway timeout if the response doesn't come back in 1 sec. However, I see that even though the response (HTTP 504) is returned to the client (REST client), the code execution continues till the last line in the class. Is Hystrix not supposed to stop the server process or am I missing something here?

**Comment by mattrjacobs** [comment]
I'm not exactly sure of what you're asking here.  Hystrix exists on the client-side of an interaction, and makes the client as resilient as possible in the face of errors/latency.

Here's a concrete example that I think matches your description:

Service A has an HTTP call to Service B.  You wrap that call in Hystrix and apply a 1000 milli timeout.

When the call gets made, it may succeed, fail, or timeout.  If it times out, then the call from A->B gets made, and then Hystrix returns control away from the thread doing the I/O to the application thread.  The I/O thread will be interrupted by default, but there's no guarantee that that call respects an interruption.  Service B is never aware that Hystrix even exists.

**Comment by gauravkandpal** [comment]
Thank you for your response, Matt. I am a newbie to this circuit breaker world. After going through the documentation and examples, I've implemented circuit breaker in my code. Here is how its laid out:

**Controller Layer**
@Autowired
private TestService testService;

@RequestMapping(value = "/test", method= RequestMethod.GET)
@ResponseBody
    public String getName() {
        testService.doThis();
        return "blahblah";
    }

**Service Layer**
@HystrixCommand( commandProperties = {
         @HystrixProperty(name="execution.isolation.thread.timeoutInMilliseconds", value = "50")})
    public String doThis(){
        System.out.println("Inside the method");
        :
       // Make call to the dependency
        System.out.println("Shouldn't be printed as the call should've timed out");
        :
        System.out.println("Shouldn't be printed at all");
        System.out.println("Exiting method");
        return "blahblah";
    }

As expected, when I hit **/test** endpoint, it times out and returns the error code, which is fine.
However, in the code, I see these statements being printed (last 3 sys outs) despite the call timing out. Am I doing something wrong here?

**Comment by mattrjacobs** [comment]
The code contained in `doThis` are what gets wrapped by Hystrix.  When Hystrix sees the timeout, the application thread walks away (returning the error code in your case).  Simultaneously, it throws an `InterruptedException` on the code in`doThis`.  Since that code does not handle an `InterruptedException`, that has no effect.  If you'd like work to get interrupted, then you need to handle the thrown `InterruptedException`.

**Comment by gauravkandpal** [comment]
Thank you Matt! It works as expected now.
