### ISSUE TITLE
Failed to processed fallback error

### ISSUE THREAD

**Issue by gauravkandpal** [Netflix/Hystrix#1409]
I've a method wrapped in Hystrix command and I've defined a fallback method in which there are 2 conditions - 1) For a certain criteria, I do something 2) For rest of the cases, I just throw an exception. Code snippet below:
public String reliable(Foo foo, Throwable throwable) throws Exception
    {
        if()
        {
            // Do further processing
        }
        System.out.println("Throw the exception "+throwable.getMessage());
        throw new Exception("Dependency down");
    }

In my logs, I see "Throw the exception ..." and then I see, "failed to processed fallback is the method: reliable". What am I doing wrong in this case?

**Comment by mattrjacobs** [comment]
I need some more details to answer this accurately.  Are you using `hystrix-javanica` or just vanilla Hystrix?  Can you provide the body of your `HystrixCommand`?  How are you invoking the command, and what are you expecting to happen?

**Comment by tatini1** [comment]
Hi ,My use case is to propagate the error from Observable to subscriber,but the same error is not visible to onError() method of subscriber ,instead it always shows
onError Must subsriber is called --- com.netflix.hystrix.exception.HystrixRuntimeException: CommandSR timed-out and no fallback available.
Below goes my code from where i throw the real exception

 @Override
    protected Observable<String> construct() {
    	System.out.println("I am in construct of "+name+"::thread name: "+Thread.currentThread().getName());
        return Observable.create(new Observable.OnSubscribe<String>() {
        	
            @Override
            public void call(Subscriber<? super String> observer) {
                try {
                    if (!observer.isUnsubscribed()) {
                    	String response = HTTPClientHelper.searchSR("https://stg-step.am.health.ge.com/service/v2/service-event11/search/SHOWROOM24", "gJc1Ts8PWBrCmi5PcTtZJTk6JmyS", "212469169");
                        // a real example would do work like a network call here
                      
                    	observer.onNext(response + "!");
                        observer.onCompleted();
                        
                    }
                } catch (Exception e) {
                	System.out.println("Exception+++++++++++++++"+e.getMessage());
                    observer.onError(new RuntimeException("graceful onError"));
                }
            }
         } );

**Comment by mattrjacobs** [comment]
It looks like you should be using a `HystrixCommand` instead of a `HystrixObservableCommand`.  Only use `HystrixObservableCommand` if you've got work that is already async (like NIO).

Once you do that, what is the behavior you're seeing?

**Comment by tatini1** [comment]
Hi Jacob,
Sorry for not explaining the problem clearly .
In below code  HTTPClientHelper.searchSR() throws 404 error ,which i want to capture in  onError(Throwable e)  implementation of subscriber .
 @Override
        public void call(Subscriber<? super String> observer) {
            try {
                if (!observer.isUnsubscribed()) {
                	String response = HTTPClientHelper.searchSR("https://stg-step.am.health.ge.com/service/v2/service-event11/search/SHOWROOM24", "gJc1Ts8PWBrCmi5PcTtZJTk6JmyS", "212469169");
                    // a real example would do work like a network call here
                  
                	observer.onNext(response + "!");
                    observer.onCompleted();
                    
                }
            } catch (Exception e) {
            	System.out.println("Exception+++++++++++++++"+e.getMessage());
                observer.onError(e);
            }
        }
     } );
But each time it throws me below message in onError block of subscriber ,**Real 404 Error message i am not able to get**
 **com.netflix.hystrix.exception.HystrixRuntimeException: CommandSR timed-out and no fallback available.** 
Even if i am implementing fallback method and throwing an exception from the same stilli am not able to get the same **onError block of subscriber**
 @Override
   protected rx.Observable<String> resumeWithFallback() {
	   System.out.println("Inside resumeWithFallback");
	   return Observable.error(new RuntimeException("graceful onError11"));
   };
Instead i am getting below error message in **onError block of subscriber**
 com.netflix.hystrix.exception.HystrixRuntimeException: CommandSR failed and fallback failed.

So my intention is how to propagate 404 error message(thrown by http client) to onError block of subscriber,so that all hystrix error handling i can manage in **onError block of subscriber**

**Comment by mattrjacobs** [comment]
Again, I will repeat that your blocking call should be in a `HystrixCommand`, not a `HystrixObservableCommand`.

If you inspect the `getCause()` of the received exception, you should see the exception instance thrown by the actual work

**Comment by tatini1** [comment]
Thanks for the reply and showing the right direction for using HystrixCommand. And also i am getting the proper exception.
So please clarify my doubt ,if i am doing a blocking call ,then i should use HystrixCommand and similarly for non blocking HystrixObservableCommand,right??
Here my use case is to do again network call for each of Id received from the network call asynchronously.

Means my onNext implemention logic includes Looping through the response and do nework call for each Id,asynchronously and putting the data in cache. Can i use HystrixObservableCommand in that case??

**Comment by mattrjacobs** [comment]
Correct, if you're wrapping synchronous work, you should use a `HystrixCommand` and if you're wrapping async work, you should use a `HystrixObservableCommand`.  

If I'm understanding your last use-case right, then you would wrap the network call in a `HystrixCommand`, and each of the `n` async cache puts in a `HystrixObservableCommand` each.
