### ISSUE TITLE
Separate hystrix queue per route

### ISSUE THREAD

**Issue by GauravAjmera25** [Netflix/Hystrix#1420]
Let's say, we have three different service id (routes) and each service id calls some 3rd party service function (common for all service id). How do we make separate hystrix queue (to call 3rd party service) for each service id, so as to provide uniform resource allocation to each service. Otherwise, it might happen that calls to one route is more, making all other service starve.

**Comment by mattrjacobs** [comment]
Hystrix provides the ability to choose a threadpool for each command, so that you have control over which resources are shared, and which are not.  Please see https://github.com/Netflix/Hystrix/wiki/How-To-Use#command-thread-pool for details on how to configure this.
