### ISSUE TITLE
I use 2 thread to submit task, and the hystrix execute threadsize is 3, but go to fallback.

### ISSUE THREAD

**Issue by liufybj** [Netflix/Hystrix#1422]
My test code is below:
```
public class HelloWorldCommand3 extends HystrixCommand<String> {
    private final String name;
    public HelloWorldCommand3(String name) {
        super(Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("ExampleGroup"))
                        .andCommandKey(HystrixCommandKey.Factory.asKey("HelloWorldCommand3"))
                        .andCommandPropertiesDefaults(HystrixCommandProperties.Setter()
.withExecutionIsolationStrategy(HystrixCommandProperties.ExecutionIsolationStrategy.THREAD))
                        .andThreadPoolPropertiesDefaults(HystrixThreadPoolProperties.Setter()
                                .withCoreSize(3))
        );
        this.name = name;
    }

    @Override
    protected String run() throws Exception {
        Thread.currentThread().sleep(100L);
        return "Hello " + name + " thread:" + Thread.currentThread().getName();
    }

    public static void main(String[] args) throws Exception {
        ExecutorService executorService = Executors.newFixedThreadPool(2);
        for (int i = 0; i < 100; i++) {
            executorService.submit(new Task(i));
        }

        executorService.shutdown();
        executorService.awaitTermination(10, TimeUnit.SECONDS);
    }

    @Override
    protected String getFallback() {
        return "excute Falled";
    }

    static class Task implements Runnable {
        int i;

        public Task(int i) {
            this.i = i;
        }

        @Override
        public void run() {
            HelloWorldCommand3 command = new HelloWorldCommand3("test_" + i);
            String result = null;
            try {
                result = command.execute();
            } catch (Exception e) {
                e.printStackTrace();
            }
            System.out.println("result=" + result);
        }
    }
}
```
------------------------------
The output is:
.....
result=Hello test_53 thread:hystrix-ExampleGroup-1
result=excute Falled
result=Hello test_54 thread:hystrix-ExampleGroup-3
result=Hello test_56 thread:hystrix-ExampleGroup-1
......

**Comment by mattrjacobs** [comment]
From the output you posted, it's not clear what failure is occurring.  A simple way to determine this would be to (temporarily) remove the `getFallback` method, which would let the exception propagate to the caller.  Then the exception would get printed.  Can you post that, so I can understand more about what's happening?

**Comment by liufybj** [comment]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1301ecc8 rejected from java.util.concurrent.ThreadPoolExecutor@c6367c7[Running, pool size = 3, active threads = 1, queued tasks = 0, completed tasks = 21]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$ThreadPoolWorker.schedule(HystrixContextScheduler.java:171)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$HystrixContextSchedulerWorker.schedule(HystrixContextScheduler.java:106)
	at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:45)
	at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)

**Comment by liufybj** [comment]
the version of hystrix-core is 1.5.5， jdk 1.8

**Comment by tatini1** [comment]
I  tried similar usecase and getting below error after 10th thread executes
onError is called --- com.netflix.hystrix.exception.HystrixRuntimeException: CommandSR could not be queued for execution and no fallback available.

**Comment by tatini1** [comment]
package com.ge.tatini.hystrix;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.CountDownLatch;

import org.codehaus.jackson.JsonNode;
import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;

import rx.Observable;
import rx.Subscriber;

public class AppTest {

	public static void main(String[] args) throws InterruptedException {
		final CountDownLatch latch = new CountDownLatch(1);
		Observable<String> ho = new CommandSR("SR","SHOWROOM24").observe();
		 ho.subscribe(new Subscriber<String>() {
				
    		 @Override
			public void onCompleted() {
				System.out.println("My onCompleted is called...");
				latch.countDown();
			}
    		 @Override 
			public void onError(Throwable arg0) {
				System.out.println("onError is called --- " + arg0);
				latch.countDown();
			}

			@Override
			public void onNext(String arg0) {
				System.out.println("My onNext is called..." + arg0+Thread.currentThread());
				final CountDownLatch latch = new CountDownLatch(100);
				for(int i=0;i<=12;i++)
				{
								Observable<String> ho = new CommandSR("SR","SHOWROOM24").observe();
								 ho.subscribe(new Subscriber<String>() {
										
						    		 @Override
									public void onCompleted() {
										System.out.println("My onCompleted is called...");
										latch.countDown();
									}
						    		 @Override 
									public void onError(Throwable arg0) {
										System.out.println("onError is called --- " + arg0);
										latch.countDown();
									}

									@Override
									public void onNext(String arg0) {
										System.out.println("My onNext is called..." + arg0+Thread.currentThread());
									}
								 });
								
				}
				try {
					latch.await();
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
			}
			
			
		});
		 latch.await();
	    System.out.println("exiting......");
	}

}

**Comment by tatini1** [comment]
And here goes my hystrix class
package com.ge.tatini.hystrix;

import com.netflix.hystrix.HystrixCommandGroupKey;
import com.netflix.hystrix.HystrixCommandProperties;
import com.netflix.hystrix.HystrixCommandProperties.ExecutionIsolationStrategy;
import com.netflix.hystrix.HystrixObservableCommand;
import com.netflix.hystrix.HystrixThreadPoolProperties;

import rx.Observable;
import rx.Subscriber;
import rx.schedulers.Schedulers;

public class CommandSR extends HystrixObservableCommand<String> {

    private final String name;
    private final String systemId;

    public CommandSR(String name,String systemId) {
      //  super(HystrixCommandGroupKey.Factory.asKey("ExampleGroup"));
    	super(Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("default"))
    			 .andCommandPropertiesDefaults(HystrixCommandProperties.Setter()
    	               .withExecutionTimeoutInMilliseconds(10000000).withExecutionIsolationStrategy(ExecutionIsolationStrategy.THREAD))
    			 );
        this.name = name;
        this.systemId=systemId;
        HystrixThreadPoolProperties.Setter().withCoreSize(15);
        HystrixThreadPoolProperties.Setter().withMaxQueueSize(-1);
    }
    
     

    @Override
    protected Observable<String> construct() {
    	System.out.println("I am in construct of "+name+"::thread name: "+Thread.currentThread().getName());
        return Observable.create(new Observable.OnSubscribe<String>() {
        	
            @Override
            public void call(Subscriber<? super String> observer) {
                try {
                    if (!observer.isUnsubscribed()) {
                    	String response = HTTPClientHelper.searchSR("https://stg-step.am.health.ge.com/service/v2/service-event/search/SHOWROOM24", "gJc1Ts8PWBrCmi5PcTtZJTk6JmyS", "212469169");
                        // a real example would do work like a network call here
                      
                    	observer.onNext(response + "!");
                        observer.onCompleted();
                        
                    }
                } catch (Exception e) {
                    observer.onError(e);
                }
            }
         } );
    }
}

**Comment by mattrjacobs** [comment]
I'm still not 100% sure what's going on, but a couple points:

1) In your latest example, you're using a `HystrixObservableCommand` with a blocking Observable.  If you've got blocking I/O, just use a `HystrixCommand`.

2) I tried this out locally and left the threadpools the same (2 for task submission, 3 for Hystrix thread pool).  Under a lot of variations of number of tasks and thread-sleep time, I was not able to reproduce the error you're seeing.

**Comment by liufybj** [comment]
@mattrjacobs I pushed my test code to GitHub. Please clone https://github.com/liufybj/netflix-test.git and try to run the main of HelloWorldCommand3. It will throw the exception occasionally.

**Comment by liufybj** [comment]
@mattrjacobs The issue is resolved after I set the maxQueueSize. Thank you.

**Comment by seetharamani** [comment]
@liufybj Can you please let me know what is the maxQueueSize you ended up with? Because I am facing the same issue here. Like for example if your application is expected 1500 request per minute and you have 2 asynchronous hystrix commands reaching out to 2 clients,  and the timeout has been set out to 2500 milliseconds, then what could be the ideal value for mazQueueSize and queueRejectionThreashold ?

**Comment by mattrjacobs** [comment]
There are a couple things going on here @seetharamani .

If the work that it getting wrapped is asynchronous, then you should be using `HystrixObservableCommand` and SEMAPHORE isolation (not thread pools).  In that case, the only setting is the semaphore size.

If the work that is getting wrapped is synchronous, then you should be using `HystrixCommand` and THREAD isolation.  In that case, you must configure which thread pool holds which commands, the thread pool size, and the thread pool queue size.

From your description, you also need to provide the observed latency of the commands - the timeout tells nothing about how the utilization of those commands

**Comment by kolapkardhaval** [comment]
@mattrjacobs I got the error "could not acquire a semaphore for execution and no fallback available" when using semaphores.
