### ISSUE TITLE
Hystrix thread pool queue size doesn't get set correctly

### ISSUE THREAD

**Issue by tungpham** [Netflix/Hystrix#1426]
Hello,

I'm trying to increase the "wait" queue in the thread pool, but the queue size appear to remain the same (by default 5 I think). In the unit test below, I expect no `RejectedExecutionException` to be thrown because the maxQueueSize is set to 20. The idea is to have the client send a bunch of requests to Hystrix pool to be processed asynchronously. The client doesn't care about the result.

From this, what's the difference between the maxQueueSize parameter and queueSizeRejectionThreshold? If I set the queueSizeRejectionThreshold instead of maxQueueSize, i don't get the RejectedExcecutionException anymore

```
    @Test
    public void shouldNotThrowRejectedException() {

        final int threadPoolCoreSize = 2;
        final boolean fallBackEnabled = false;
        final boolean circuitBreakerEnabled = false;
        final int executionTimeoutInMilliseconds = 20000;
        final int maxQueueSize = 20;

        String groupKey = "sendMail";
        HystrixCommandKey commandKey = HystrixCommandKey.Factory.asKey(groupKey);
      
        HystrixCommand.Setter setter = HystrixCommand.Setter.withGroupKey(com.netflix.hystrix.HystrixCommandGroupKey.Factory.asKey(groupKey)).andCommandKey(commandKey)
                .andThreadPoolPropertiesDefaults(HystrixThreadPoolProperties.Setter()
                                .withAllowMaximumSizeToDivergeFromCoreSize(true).withMaximumSize(maxQueueSize)
                                .withCoreSize(threadPoolCoreSize)
                                .withMaxQueueSize(maxQueueSize)
                )
                .andThreadPoolKey(new HystrixThreadPoolKey() {
                    @Override
                    public String name() {
                        return "ThreadPoolForSendMail";
                    }
                })
                .andCommandPropertiesDefaults(HystrixCommandProperties.Setter()
                        .withCircuitBreakerEnabled(circuitBreakerEnabled)
                        .withFallbackEnabled(fallBackEnabled)
                        .withExecutionTimeoutInMilliseconds(executionTimeoutInMilliseconds));


        for(int i = 0; i < 10; i++) {
            HystrixCommand cmd = new HystrixCommand(setter) {
                @Override
                protected Object run() throws Exception {
                    try {
                        MDC.setContextMap(MDC.getCopyOfContextMap());
                        System.out.println(Thread.currentThread().getName() + " starts work " + new Date());
                        Thread.sleep(2000);
                        System.out.println(Thread.currentThread().getName() + " finnish work " + new Date());
                    } finally {
                        MDC.clear();
                    }
                    return null;
                }
            };

            cmd.queue();
        }

        assertTrue(true);
    }
```

**Comment by liufybj** [comment]
The queueSizeRejectionThreshold default is 5. Please try to set this property as the same as maxQueueSize.

**Comment by tungpham** [comment]
As I mentioned in the post, if I set the queueSizeRejectionThreshold to a large enough value, the problem goes away. My question is, what's the difference between maxQueueSize vs. queueSizeRejectionThreshold?

**Comment by mattrjacobs** [comment]
The `maxQueueSize` value is what gets read to set up the static data structure used by the first invocation of the thread pool.  The `queueSizeRejectionThreshold` is the value of the queue length that triggers rejection.  By definition, `queueSizeRejectionThreshold <= maxQueueSize`.  Having 2 values allows some amount of dynamic behavior without a restart, since `queueSizeRejectionThreshold` may be adjusted anywhere between 0 and `maxQueueSize`.

**Comment by tungpham** [comment]
I see. Thank you
