### ISSUE TITLE
ThreadPool statistics not displaying for HystrixCommandObservable

### ISSUE THREAD

**Issue by kishore25kumar** [Netflix/Hystrix#1427]
I am trying hystrix with a sample application. In the hystrix dashboard I am seeing the command statistics but not thread statistics. The thread statistics show Loading... but not displaying anything.

This is happening only for HystrixObservableCommand. The thread pool dashboard is working fine for HystrixCommand.

Any one knows why it is happening only for HystrixObservableCommand.

**Comment by mattrjacobs** [comment]
HystrixObservableCommands do not use thread pools by default.

**Comment by kishore25kumar** [comment]
@mattrjacobs Can we configure to use it thread pools?

**Comment by mattrjacobs** [comment]
HystrixObservableCommands should not use thread pools.  They are designed to take work that is already asynchronous (like Java NIO) and wrap Hystrix semantics around it.  If you have blocking work, then isolating it in a thread pool is the only way to get a guaranteed of bulkheading - that is why HystrixCommands are designed to do synchronous work and run in a thread pool.

**Comment by kishore25kumar** [comment]
Thanks now I got clarity on the two commands.
