### ISSUE TITLE
How can hystirx dashboard work on no-web application?

### ISSUE THREAD

**Issue by notatent** [Netflix/Hystrix#1432]
hi, How can hystirx dashboard work on no-web application?

**Comment by kennedyoliveira** [comment]
Hey!

You can use [hystrix-vertx-metrics-stream](https://github.com/kennedyoliveira/hystrix-vertx-metrics-stream), it'll start a embedded very lightweight http server and you can consume from it.

**Comment by mukteshkrmishra** [comment]
@notatent : What do you mean by no web app hystrix dashboard. (Dashboard is a web application).

If you are talking about the data which Hystrix provides @kennedyoliveira raised a correct point in above comment and data can be consumed by any means once it is thrown.

**Comment by notatent** [comment]
I'm mean how HystrixMetricsStreamServlet can running in a no-web application, and I have find a way. Embed jetty server to enable metrics stream.
