### ISSUE TITLE
Question around circuit open and close

### ISSUE THREAD

**Issue by ahmednasir91** [Netflix/Hystrix#1433]
Our service is running on AWS elastic beanstalk behind a load balancer there are 3 instances. The circuit was open probably the remote service went down, but one 2 of the instances the circuit was closed again.

However for the third instance, the circuit remained open, for more than 2 hours until i manually restarted the instance. Following configuration we are using

```
"hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds": 400,
"hystrix.command.default.circuitBreaker.requestVolumeThreshold": 60,
"hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds": 60000,
"hystrix.command.default.circuitBreaker.errorThresholdPercentage": 50,
```

So my question is, how calculating if the circuit can be closed again, does it require to meet `requestVolumeThreshold`? Because to me it looks like the requests were below threshold.

Thanks

**Comment by mukteshkrmishra** [comment]
It is not dependent upon requestVolumeThreshold. Rather it is dependent upon errorVolumeThreashholdPercentage.

**Comment by ahmednasir91** [comment]
@mukteshkrmishra thanks for your reply. Any other suggestion what could have been the issue? as i restarted the app server and it started working. Also the other 2 instances were also working at the same time. So definitely the remote service was healthy.

**Comment by mattrjacobs** [comment]
Specifically, the circuit transitions back from OPEN -> CLOSED when a single request is successful.  This occurs after the circuit-breaker sleep window expires, and repeats on that interval for as long as the wrapped call fails.  It's worth looking at metrics to see if that trickle of traffic was successful or not.  Based on how the circuit-breaker works, I suspect that those calls were all failures.  If so, then it's worth understanding why that is.  Perhaps some sort of bad state gets cached in the client?

**Comment by ahmednasir91** [comment]
@mattrjacobs Thanks for the explanation, we don't have caching on that layer. I checked logs for an hour and all i saw was only circuit open exceptions. I'm closing this issue for now, will reopen it, in case i see the behavior again.

**Comment by ahmednasir91** [comment]
The issue happened again twice on different instances, the problem is same, one of the instance starts throwing circuit open exception, although the other two were healthy.

Any idea what i should look for in case this happens again? I checked the Hystrix Dashboard of that instance it was showing all the requests are failure.

**Comment by mattrjacobs** [comment]
A persistent open circuit means that the failure threshold was reached at a point in time, and after that point, none of the later requests succeeded.  If you've got some ability to find executions after the initial circuit open, then you should try to understand why they're failing.

**Comment by pavradev** [comment]
@mattrjacobs we noticed an interesting behavior of circuit breaker in hystrix: ones circuit is open, then it does not differentiate between HystrixBadRequestException and other types of exception. 
It is a bit counterintuitive because HystrixBadRequestException should never open the circuit, but once it is opened, HystrixBadRequestException will reopen it on the first retry. Is this behavior by design?

**Comment by mattrjacobs** [comment]
That sounds like an oversight.  I agree with your logic - if an exception should not trigger a circuit-open initially, it should also not prolong a circuit-open.

However, the implementation would be trickier - you would have to have retry logic that would retry in the case of a BadRequest, or relax the requirement that only 1 request be outstanding.

**Comment by pavradev** [comment]
@mattrjacobs thanks for your answer

**Comment by mattnelson** [comment]
> That sounds like an oversight. I agree with your logic - if an exception should not trigger a circuit-open initially, it should also not prolong a circuit-open.

This is the opposite of what was previously communicated.

https://github.com/Netflix/Hystrix/issues/674#issuecomment-163141304

**Comment by mattrjacobs** [comment]
@mattnelson Thanks for bringing that back to my attention.  Never ideal when I disagree with myself!  It's a grey area and there's no obviously correct thing to do.

@pavradev Can you take a look at the linked comment and see what you think?

Considering both sides, I think I agree more with the 2015 comment: We should have evidence of healthiness before we close the circuit.  If you strongly disagree with this, would be happy to have that discussion.

**Comment by pavradev** [comment]
@mattrjacobs I find logic behind both arguments. My question was more about if this is intended :) I would say not prolonging the circuit in this case is a more consistent solution, but added implementation complexity does not worth it.

**Comment by mattrjacobs** [comment]
Yeah, I'll add something to the docs, since I confused myself on this one, and I'm sure others may have the same question.
