### ISSUE TITLE
Question regarding maximumSize and coreSize

### ISSUE THREAD

**Issue by mohamedanees** [Netflix/Hystrix#1436]
I have set the maximum size of thread pool to be 10 and the core size as 2. The requests are getting queued(if more than 2 requests are made) instead of creating a new thread on the threadpool.

As far as my knowledge, the thread pool must support 10 threads to the maximum and then queue the subsequent requests. If the number of requests is less, and the other 8 threads on the threadpool are not assigned any tasks,then they must wait for utmost 1 minute to get destroyed (But the thread pool will still contain 2 daemon threads even if no requests are made). But this is not happening in my case. Kindly advise if my understanding is right!

**Comment by mattrjacobs** [comment]
Can you retry with 1.5.9 (just released)?  If the issue still exists, I can dig in.

**Comment by mohamedanees** [comment]
@mattrjacobs  Still this issue is persisting. I tried using 1.5.9. Kindly suggest.

**Comment by mattrjacobs** [comment]
Can you inspect the configuration of the running system to see what values are being used?  You can use the [Hystrix configuration stream](https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#configuration-stream) or do something manual by inspecting Hystrix objects and logging values out.

**Comment by mohamedanees** [comment]
Hi @mattrjacobs,

Thanks for your help all the way,its working fine with latest version. I forgot to reconfigure after updating the hystrix jar to 1.5.9. Closing this issue 👍

**Comment by karteeksaragad** [comment]
@mohamedanees : I have the same problem with dynamic hystrix thread pool settings, not working expected. I am using hystrix 1.5.12 (maximumSize=100, coreSize=60 and allowMaximumSizeToDivergeFromCoreSize=true). Can you let me know what is that you forgot to reconfigure to fix the issue???

**Comment by prakhar241** [comment]
@karteeksaragad - I'm facing similar issue with 1.5.12. Did it work for you?

**Comment by prakhar241** [comment]
+ @mattrjacobs
