### ISSUE TITLE
problem about static files urls of dashboard

### ISSUE THREAD

**Issue by mmobini** [Netflix/Hystrix#1437]
Hi guys

I can enable hystrix dashboard successfuly.

But in production environment, my service is after zuul with this domain "http://sample_domain/service_name/..." which cause static files like jquery.js don't load successfully.
(It wants to download files for example from http://sample_domain/jquery.js instead of http://sample_domain/service_name/jquery.js)

Is there any way to fix this issue by for example overriding base urls of static files or ...?

Thanks.

**Comment by mukteshkrmishra** [comment]
For me it looks like a zuul problem instead of Hystrix. Does anybody in community has any other thoughts on this.

cc : @mattrjacobs @dmgcodevil

**Comment by spencergibb** [comment]
your backend app has to know that it is behind a proxy and react accordingly, or zuul has to know how to map `/jquery.js` to the right backend.

**Comment by mmobini** [comment]
Thanks @spencergibb @mukteshkrmishra. As you may know, my backend app is a spring-boot server.
Then how can I inform my backend app that it is behind proxy?

**Comment by spencergibb** [comment]
"As you may know", nope, how would I? Are you using vanilla zuul or using spring cloud? If spring cloud, let's move the conversation.

**Comment by mmobini** [comment]
i'm using spring cloud.
