### ISSUE TITLE
Dependency has its own thread pool, how to turn off hystrixcommand isolation feature?

### ISSUE THREAD

**Issue by legatoo** [Netflix/Hystrix#1438]
Dependencies in my application maintains their own thread pool, where the potential thread risk is already isolated. So, is it possible to turn off the hystrixcommand thread pool feature? I only want to use circuit break and recovery feature.

**Comment by mattrjacobs** [comment]
Use semaphore isolation: https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.strategy
