### ISSUE TITLE
Hystrix config error

### ISSUE THREAD

**Issue by vamsykv** [Netflix/Hystrix#1450]
ERROR [http-nio-50077-exec-11] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service()
for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.netflix.hystrix.exception.Hystrix
RuntimeException: search failed and no fallback available.] with root cause
feign.FeignException: status 500 reading Service#search(String); content:

is this something related to hystrix property values defined.

**Comment by mattrjacobs** [comment]
The only piece here which involves Hystrix is 

```
com.netflix.hystrix.exception.HystrixRuntimeException: search failed and no fallback available.
```

This means that the Hystrix command failed and there was no fallback.  More concretely, the `run()` method threw an exception and the `getFallback()` method was not defined.  You should examine why the exception was thrown
