### ISSUE TITLE
XSS and HTML Injection in title field and stream URL field

### ISSUE THREAD

**Issue by onlineaccount** [Netflix/Hystrix#1456]
![imagen](https://cloud.githubusercontent.com/assets/16137380/21840815/c859115a-d7df-11e6-96b4-4a4c51a141ea.png)

When you click in Add Stream button the injection will be executed:
![imagen](https://cloud.githubusercontent.com/assets/16137380/21840830/e63e773c-d7df-11e6-9dc8-e9bf5516a3c9.png)

You have to click in the injected title or url field to view the JavaSript alert.

**Comment by mattrjacobs** [comment]
Thanks for the report @onlineaccount .  Would you or anyone else be interested in submitting a PR to fix this?

**Comment by jack17529** [comment]
@mattrjacobs if PR-welcome means one can submit a PR ?
I would love to submit one!

**Comment by mattrjacobs** [comment]
@jack17529 Yes, absolutely.  I'm happy to review whenever you're ready
