### ISSUE TITLE
How to test circuitbreaker without time side effect?

### ISSUE THREAD

**Issue by narusas** [Netflix/Hystrix#1466]
Hystrix is based on 1-seconds timed bucket.
CircuitBreaker read only lastest 1 seconds bucket.

I write some test 

for(int i=0; i<100;i++){
 try {
  cbAppliedService.doService();
 } catch(HystrixRuntimeException ex) {

  log.info("Trial {} ", i, ex);
 }
}

I run this test, it threw runtime exception( "java.lang.RuntimeException: Hystrix circuit short-circuited and is OPEN" ) randomly. Trial at 44, 25, 33,76...

How to write test without time side effect?

**Comment by mattrjacobs** [comment]
Unfortunately, there's no notion of a time abstraction in Hystrix.  If there were, then you could override it with virtual time in unit tests, and wall clock time in the real world.  It's possible, but a fair amount of work.
