### ISSUE TITLE
How to shutdown HystrixCommand thread pools

### ISSUE THREAD

**Issue by sanjay070783** [Netflix/Hystrix#1467]
Hi,

We are beginner on Hystrix and need some help. We are using HystrixCommands for making external REST API calls. For each user request there can be more than 20 such calls. We want to specify a different Thread Pool Key for each user request and will have a default core size and max queue size. On analyzing it through profiling tool, we see that for each different key it created a separate thread pool and thread pool is never shut down. So have two questions:
1. How to shutdown these pools when needed? Can I get a hook by keyname and shut down specific pool?
2. Is there any way to pass an external thread pool to Hystrix Command? If yes, then will it use core size and max queue properties?

Also, to add why I want different key name because if we have same key name then we would have a common thread pool and won't be able to equally distribute threads for different user request. It may happen one request consumes all available threads where as other request has to wait completely.

Thanks in advance.

**Comment by mattrjacobs** [comment]
A couple points to make here:

* It's usually ideal to have commands share a threadpool.  Our rule of thumb is to group commands together at the granularity of the service being called.  So if Commands A1 and A2 are separate operations against Service A, and Commands B1 and B2 are separate operations against Service B, then I would recommend 2 thread pools: one containing A1/A2 and one containing B1/B2.  The insight here is that a service often fails as a whole.  Consuming 1 threadpool if often better for the caller than consuming 1 per command.

* There's not a fine-grained way to shutdown threadpools.  There's a heavy hammer (`Hystrix#reset()`) which clears all state associated with Hystrix and is only intended to be used in unit tests.  Why do you want such a capability?

* There's no way to pass in a threadpool to Hystrix.  If you choose Thread-based isolation, then Hystrix will control setting up the threadpool for you.  If you choose Semaphore-based isolation, then the command runs on the caller thread.  You're, of course, free to use whatever thread pool to call commands if you wish to go that route.

**Comment by sanjay070783** [comment]
Thanks Matt. It really helps.

**Comment by houqingrong** [comment]
Why (Hystrix#reset()) only intended to be used in unit tests? in the online environment, if don't use it, how to solve when main process restart or killed , but the tasks in the thread pool is still running.
