### ISSUE TITLE
[wiki] Default metrics publisher does nothing

### ISSUE THREAD

**Issue by sslavic** [Netflix/Hystrix#1473]
Documentation on https://github.com/Netflix/Hystrix/wiki/Plugins#metrics-publisher claims that

> The default implementation publishes them to Servo ...

Looking at the code, HystrixMetricsPublisherDefault doesn't override any of the methods from abstract HystrixMetricsPublisher that it inherits, and default implementations return no-op implementations like HystrixMetricsPublisherCommandDefault which does nothing.

In contrib there's implementation which does publish Hystrix metrics to Servo (see [here](https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-servo-metrics-publisher)), but AFAIK it has to be explicitly configured.

If default implementation doesn't publish metrics anywhere, please have wiki page updated.

**Comment by mattrjacobs** [comment]
Nice catch.  Just updated the Wiki page
