### ISSUE TITLE
[question] Will the underlying thread be stopped immediately if timeout occurs?

### ISSUE THREAD

**Issue by xiaoshuang-lu** [Netflix/Hystrix#1474]
Assuming that there is a time-consuming command.

When timeout occurs, will the thread which is executing the task be stopped immediately?

```
execution.isolation.strategy = THREAD;
execution.timeout.enabled = true;
execution.isolation.thread.interruptOnTimeout = true;
```

**Comment by mattrjacobs** [comment]
In the JVM, threads cannot be forcefully stopped.  If the configuration is set to interrupt on timeout (as you showed above), then the Hystrix thread will get interrupted.  It's up to the implementation of the work if that interrupt is respected or not.

**Comment by xiaoshuang-lu** [comment]
Thank you, @mattrjacobs.
