### ISSUE TITLE
Cleaner error propagation in hystrix core v2

### ISSUE THREAD

**Issue by mNantern** [Netflix/Hystrix#1478]
I have exactly the same issue as in #1414 (fix works great btw, thx!) but for `HystrixBadRequestException`.

I tried to implement a `HystrixCommandExecutionHook` but all the methods are executed before `decomposeException` so I don't know how to make it work.

Any idea ?

Thank you !

**Comment by mattrjacobs** [comment]
I'm not sure I follow.  `HystrixRuntimeException` is generated by the Hystrix execution mechanism.  In that case, having the option to wrap with or without it is reasonable.  `HystrixBadRequestException` is never added by Hystrix, only by user code.  So if you don't want callers to get `HystrixBadRequestException`, then you should de line to use it in your code.

**Comment by mNantern** [comment]
My use case is pretty simple:

my HTTP clients are throwing functional exceptions that are catch in different places in my code. I don't want Hystrix to count some of the exception as server error (for example: bad parameters) and so I wrapped them in `HystrixBadRequestException`.
But now I'm forced to change all my `catch` to check for `HystrixBadRequestException` instead of my functional exceptions.

A possible workaround would be to check for the same interface (`ExceptionNotWrappedByHystrix`) in order to unwrap `HystrixBadRequestException` too.

What do you think ?

**Comment by mattrjacobs** [comment]
OK, got it, thanks for clarifying - that does make sense to me now.  For next steps, I can imagine the following implementations:

- User can wrap business exception with HystrixBadRequestException and ExceptionNotWrappedByHystrix.  Hystrix knows both should get unwrapped
- We invent a new exception type: HystrixUnwrappedBadRequestException that has the proper semantics w.r.t. circuit-breaking but is handled by not propagating this Hystrix-internal type
- We add configuration that decides whether to drop a HystrixBadRequestException or propagate it.

Any thoughts on which of these makes sense from your perspective?

**Comment by mNantern** [comment]
Clearly the first one. I really like the fact that you can just add to your exception an `implements ExceptionNotWrappedByHystrix` and that's it everything works as expected !

**Comment by mattrjacobs** [comment]
My schedule is jammed at the moment.  Would you like to submit a PR with an implementation of this?

**Comment by mNantern** [comment]
Sure !

I will change the method `decomposeException` in `AbstractCommand` to return the original exception when it is wrapped with HystrixBadRequestException and ExceptionNotWrappedByHystrix.

I don't know Hystrix very well but does it sound good for you ?

**Comment by mukteshkrmishra** [comment]
My :+1 for above approach. HowyI would like to have a look on it once ✅
