### ISSUE TITLE
Hook to use Weblogic WorkManagers instead of Hystrix Thread Pool

### ISSUE THREAD

**Issue by navneetthakur99** [Netflix/Hystrix#1480]
Hi Team, 

We are planning to use Hystrix in our application deployed on weblogic. The application currently uses Weblogic workmanagers to implement the bulk head pattern. We wanted to replace the code with Hysterix but want to use the existing configured workmanagers in Hysterix as they are managed by the contained. We could not find any hook to implement a customised threadpool or thread factory in Hysterix to replace internal threadpool. Any help in this regard is appreciated.

Regards,
Navneet

**Comment by mattrjacobs** [comment]
You may provide your own threadpool via this plugin: https://github.com/Netflix/Hystrix/wiki/Plugins#concurrencystrategy

**Comment by navneetthakur99** [comment]
Thanks Matt...will check and revert
