### ISSUE TITLE
hystrix-servo-metrics-publisher is in conflict with spring-boot-starter-actuator

### ISSUE THREAD

**Issue by hystrixFan** [Netflix/Hystrix#1485]
After adding the dependency 
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
```

the `hystrix-servo-metrics-publisher` doesn't work. `com.netlix.servo` is not available at JMX MBeans/attributes.

Here is a small sample project with the disabled `spring-boot-starter-actuator` dependency:
https://github.com/hystrixFan/hystrix-servo-metrics-publisher-jmx-example

If the dependency is enabled `hystrix-servo-metrics-publisher` doesn't work.

**Comment by mattrjacobs** [comment]
Is there anything that needs to change with the Hystrix libraries, or is the issue in the Spring Boot libraries?  It's not clear to me what change needs to happen

**Comment by hystrixFan** [comment]
I don't know. We use dropwizard instead of hystrix-servo-metrics-publisher now.
