### ISSUE TITLE
Expose isCircuitBreakerOpen as 0 and 1 instead of boolean string

### ISSUE THREAD

**Issue by billyy** [Netflix/Hystrix#1487]
We are using a KPI that can accept number only for KPI.   Can you change the code to expose 0 and 1 instead of boolean string true/false in the HystrixServoMetricsPublisherCommand.java?  I can also contribute with a pull request.  Let me know.  Thanks.

**Comment by billyy** [comment]
I am referring to the following class.

HystrixServoMetricsPublisherCommand.java

**Comment by mattrjacobs** [comment]
Changing it is not an option, as that breaks any current consumers.

If I were you, I wouldn't consume this data at all.  The number of commands that get executed and short-circuited is already available, and is a generally more useful metric.  Do you agree with that?

**Comment by billyy** [comment]
Got it.   I can monitor the short-circuited count to get the same info.   That will work.  Thanks.

**Comment by mattrjacobs** [comment]
To be clear, it's not the same.  The `isCircuitBreakerOpen` measures the amount of time that a circuit is open, while comparing `countSuccess` and `countShortCircuited` measures the command invocations which passed through the circuit-breaker or got short-circuited.  IMO, the latter is more useful.

**Comment by billyy** [comment]
Got it.   In this case, I am looking for "rate of change" with countShortCircuited to detect anomaly.   So it will work for us.   Thanks for the clarification.
