### ISSUE TITLE
hystrix-metrics-event-stream implementation using JAX-RS instead of Servlet API

### ISSUE THREAD

**Issue by justinjose28** [Netflix/Hystrix#1490]
Right now, hystrix-metrics-event-stream module is dependent on Servlet API. But, I think there are applications that depend only on JAX-RS without any Servlet dependency. Does it make sense to add a module here based on JAX-RS which publishes metrics stream? It is fairly easy and I have created one for our application. I can contribute it if this is the right place to keep it.

**Comment by mattrjacobs** [comment]
Sure, that does sound like a reasonable addition.  I'm happy to review a PR for it.  Thanks!

**Comment by justinjose28** [comment]
@mattrjacobs I have opened a [PR](https://github.com/Netflix/Hystrix/pull/1495)for this issue. Can you please review it?
