### ISSUE TITLE
The overridden wrapCallable method in a CustomConcurrencyStrategy is not getting called

### ISSUE THREAD

**Issue by ss315** [Netflix/Hystrix#1493]
Hi,
    We are introducing Hystrix in our application and we are using javanika.
The application has multi-threading, in which each thread does some function (ex:call a different webservice) and I wanted pass the thread local values to all the new threads created in multi-threaded workflow.
I tried using a Custom HystrixConcurrencyStrategy implementation and registered it using the command
HystrixPlugins.getInstance().registerConcurrencyStrategy(new CustomConcurrencyStrategy());

When i sys out of HystrixPlugins.getInstance().getConcurrencyStrategy().toString() , the class name is printed correctly( the custom class name), but the overridden wrapCallable method is never called.

1. Even when the HystrixCommand is executed, wrapCallable method is not getting called. When will this method will be called?
2. Is there any **annotation** in javanika that i have to use to enable the use of CustomConcurrencyStrategy class?
3. Basically i want to pass the thread-local values to all the threads in multi-threading, how should i do this?

Code below
`import com.netflix.hystrix.strategy.concurrency.HystrixConcurrencyStrategy;
import java.util.concurrent.Callable;

public class CustomConcurrencyStrategy extends HystrixConcurrencyStrategy {
    @Override
    public Callable wrapCallable(Callable callable) {
        return new HystrixCallable(callable);
    }
}
`
-------------------------------------------------------------------------------------------------------------------
`
import org.slf4j.MDC;
import java.util.Map;
import java.util.concurrent.Callable;

public class HystrixCallable<A> implements Callable<A>{
    private final Callable<A> actual;
    private final Map parentMDC;

    public HystrixCallable(Callable<A> actualCall){
        this.actual = actualCall;
        parentMDC = MDC.getCopyOfContextMap();
    }

    @Override
    public A call() throws Exception {
        Map childMDC = MDC.getCopyOfContextMap();
        try {
            MDC.setContextMap(parentMDC);
            return actual.call();
        } finally {
            MDC.setContextMap(childMDC);
        }
    }
}
`

**Comment by mattrjacobs** [comment]
The method `HystrixConcurrencyStrategy#wrapCallable` is called by `com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction` (sic).

This is used in the internal machinery that schedules command execution onto an Rx Scheduler (which eventually ends up in a threadpool somewhere).

So it should be getting called, assuming it's being properly registered.

**Comment by ss315** [comment]
HystrixPlugins.getInstance().registerConcurrencyStrategy(new CustomConcurrencyStrategy());

Hope the above statement will do the registration of the CustomConcurrencyStrategy.
When i sys out of HystrixPlugins.getInstance().getConcurrencyStrategy().toString() , the class name is printed correctly( the custom class name), which indicates that its registered properly.

**Comment by mattrjacobs** [comment]
I just added a `println` to an existing unit test to demonstrate this works as expected.

Please run `HystrixCommandTestWithCustomConcurrencyStrategy#testCommandRequiresContextConcurrencyStrategyProvidesItContextSetUpCorrectly` in this branch: https://github.com/mattrjacobs/Hystrix/tree/demonstrate-custom-concurrency-strategy

**Comment by mabn** [comment]
@mattrjacobs I've noticed the same problem, `wrapCallable` is not called when using `HystrixObservableCommand` and created command is completed. If it times out then `wrapCallable` is invoked. I've tested with 1.5.12 version.

Here's a test (no assertions though, but it doesn't print anything when run with `HystrixObservableCommand`):

```java
    @Test
    public void testObservableCommandCallsWrapCallable() {
        HystrixConcurrencyStrategy strategy = new CustomConcurrencyStrategy(false);
        HystrixPlugins.getInstance().registerConcurrencyStrategy(strategy);

        // works
        // HystrixObservable<Boolean> cmd = new TestCommand(false, false);

        // does not work
        TestObservableCommand cmd = new TestObservableCommand();

        assertTrue(cmd.observe().toBlocking().firstOrDefault(true));
    }


    public static class TestObservableCommand extends HystrixObservableCommand<Boolean> {
        TestObservableCommand() {
            super(HystrixCommandGroupKey.Factory.asKey("hystrix_cmd"));
        }

        @Override
        protected Observable<Boolean> construct() {
            return Observable.just(true);
        }
    }
```

**Comment by mattrjacobs** [comment]
@mabn What are you attempting to do?  `HystrixConcurrencyStrategy` is only invoked when a new thread is created, such that context can be shared between the threads.

If you need information around command execution, you are likely better served by the [command execution hooks](https://github.com/Netflix/Hystrix/wiki/Plugins#command-execution-hook)

**Comment by mabn** [comment]
I'm experimenting with opentracing and I've put into `wrapCallable` creating new span for the command and it surprised me `wrapCallable` is not called. 
But from what you're writing it seems that I should create spans inside execution hook and use `wrapCallable` only to propagate "parent span" across threads.

**Comment by mattrjacobs** [comment]
Yeah, we do something similar internally where we use the execution hooks to keep track of spans.
