### ISSUE TITLE
hystrix-javanica-ctw artifact

### ISSUE THREAD

**Issue by tol** [Netflix/Hystrix#1499]
Hi!

How can I get the hystrix-javanica-ctw?
I am trying this, but it didn't work...

<dependency>
    <groupId>com.netflix.hystrix</groupId>
    <artifactId>hystrix-javanica-ctw</artifactId>
    <version>1.5.10</version>
</dependency>

**Comment by mattrjacobs** [comment]
I've already answered this here: https://github.com/Netflix/Hystrix/issues/907#issuecomment-286807723.  Closing this one as a duplicate
