### ISSUE TITLE
Blocking when all threads in a pool are busy

### ISSUE THREAD

**Issue by monmohan** [Netflix/Hystrix#1501]
Is there a way to configure the caller thread to block for certain time, if all the the threads in the hystrix thread pool are busy. I don't want to add the call to a Queue and using a SynchronousQueue immediately throws a ExecutionRejectionException. I guess handling the exception and sleeping could be one way but something like configuring http://javadox.com/org.springframework.integration/spring-integration-core/3.0.8.RELEASE/org/springframework/integration/util/CallerBlocksPolicy.html on the thread pool.
Thanks for your time
Monmohan

**Comment by mattrjacobs** [comment]
Answered in the Google Group: https://groups.google.com/forum/#!topic/hystrixoss/GuQLZAWTlkI
