### ISSUE TITLE
More flexible hystrix-javanica configuration for ignored exceptions

### ISSUE THREAD

**Issue by matlik** [Netflix/Hystrix#1505]
Would it be reasonable to enhance hystrix-javanica to support inverting the exception inclusion/ignore logic?  What I mean is, Hystrix includes any exception as relevant for the Circuit Breaker. I would like to allow Hystrix to ignore all exceptions instead.  

We have had a few cases where this default behavior had a broader negative impact than it should have.  Our more recent event involved one rogue client submitting bad data that resulted in an immediate SQLException due to a database constraint conflict. This one client ended up taking down the service for everyone because of the circuit breaker.  Certainly the bugs that triggered the exceptions shouldn't have been there, but you know... complex evolving systems aren't always perfect. 

For our needs, it seems that the timeout alone could be sufficient to drive the circuit breaker's state changes.  However, it would be nice to also selectively include individual exception types or even exception types that fit a particular predicate (e.g. SQLException with specific SQL status codes). 

The mental picture I have is something akin to the htaccess way of declaring access control where the default is to Allow (include) all exceptions and Deny (exclude) individual types; however, you have the option to switch the order to Deny (exclude) all exceptions but Allow(include) a select few.  Granted, there would be special case exceptions (HystrixBadRequestException and HystrixRuntimeException) that would be handled the same regardless of this configuration.  

I believe this requirement can be accomplished by allowing the logic within `com.netflix.hystrix.contrib.javanica.command.AbstractHystrixCommand#isIgnorable(Throwable throwable)` to be pluggable, possibly by passing in a new "ignoreExceptionsPredicate" builder parameter that accepts a Class containing the desired predicate logic.

Technically this appears feasible to me, unless I am missing something.  My real question is if I were to create a pull request, would such a change be accepted?

**Comment by mattrjacobs** [comment]
I'm not sure I follow.  Are you talking about:

1) The types of errors which trigger a circuit-breaker to OPEN
or
2) The types of errors that get returned to the caller

What's the kind of code you want to write to achieve your desired change in behavior?

**Comment by matlik** [comment]
I was referring to 1: The types of errors which trigger a circuit-breaker to OPEN.

I was thinking of implementing something like the following:
    
    @HystrixCommand(ignoreExceptionsPredicate = MyAlwaysTruePredicate.class)
    public User getUserById(String id) {
        return userResource.getUserById(id);
    }

where there is a no-args constructable class:

    public class MyAlwaysTruePredicate extends HystrixThrowablePredicate {
        public boolean test(Throwable t) {
            /* More complicated stuff than could be done */
            return t insatanceof Exception;
        }
    }

Since this needs to support Java < 8, a custom HystrixThrowablePredicate would be needed as the parent type.  This predicate, if provided, would effectively replace the collection of exception types that can be provided via the `ignoreExceptions` annotation attribute.  It should also be possible to set it at the class level for all commands to leverage implicitly.

Then, when hystrix-javanica checks to see if an exception should be ignored, it would need to first handle the Hystrix wrapper exceptions (behavior of these should remain constant) and then subsequently use the predicate to decide if the exception should be wrapped in a HystrixBadRequestException or not.

Unless I've misunderstood the code, a configuration like this could allow all application level exceptions to pass through the circuit breaker without making it transition to OPEN, but the exceptions could still be handled appropriately by the business logic.

**Comment by mattrjacobs** [comment]
At the moment, the type of errors that trigger circuit-breaking are not configurable.  It's not clear to me that making this configurable is useful.

If you want circuit-breaking to happen less frequently (or not at all), then you can disable it with a boolean flag or raise the threshold to a point where it's very hard to trigger.

**Comment by matlik** [comment]
Understood.  After further discussion within our team, we opted to address this in a way that does not enhance hystrix-javanica's configurability.

Thank you.
