### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by Nyamiou** [Netflix/Hystrix#1519]
Hello,

So a colleague of mine was testing timeout on some of our applications and got very inconsistent results, so I tested with some very simple applications and I also have very inconsistent results. 

Here is a simple Spring Application using Hystrix that use Hystrix annotations to define a timeout of 200ms on a method which code takes always more than 200ms (at least on my PC)

`@SpringBootApplication
@EnableCircuitBreaker
public class HystrixPocAnnotationApplication {

	public static void main(String[] args) {
		SpringApplication.run(HystrixPocAnnotationApplication.class, args);
	}

	@Component
	public static class HystrixPocRunner implements CommandLineRunner {

        @Autowired
        private TestService testService;

        @Override
        public void run(String... args) throws Exception {
            for (int i = 0; i < 10; i++) {
                long start = System.currentTimeMillis();
                System.out.println("Outside before call");
                System.out.println("Result: " + testService.longRunningCall(UUID.randomUUID().toString()));
                System.out.println("Outside after call: " + (System.currentTimeMillis() - start));
            }
        }
    }

    public interface TestService {
        boolean longRunningCall(String testStr);
    }

    @Service
    public static class TestServiceImpl implements TestService {

        @HystrixCommand(
                commandKey = "longRunningCall",
                threadPoolKey = "longRunningCall",
                commandProperties = {
                        @HystrixProperty(name = HystrixPropertiesManager.EXECUTION_ISOLATION_THREAD_TIMEOUT_IN_MILLISECONDS, value = "200"),
                },
                fallbackMethod = "longRunningCallFallback"
        )
        @Override
        public boolean longRunningCall(String testStr) {
            System.out.println("Normal method: " + testStr);
            Map<Integer, List<Integer>> map = new HashMap<>();
            for (int i = 0; i < 5000; i++) {
                map.put(i,new ArrayList<>());
                for (int j = 0; j < 5000 ; j++) {
                    map.get(i).add(j);
                }
            }
            return true;
        }

        private boolean longRunningCallFallback(String testStr) {
            System.out.println("Fallback method: " + testStr);
            return false;
        }
    }
}`

Here is the result I get:

> Outside before call
Normal method: a6e5aa63-0127-48d3-a23d-2ff93e1e0dc1
Fallback method: a6e5aa63-0127-48d3-a23d-2ff93e1e0dc1
Result: false
Outside after call: 533
Outside before call
Normal method: 1dc7db58-c2d2-4e62-8960-30ca2a939bbf
Fallback method: 1dc7db58-c2d2-4e62-8960-30ca2a939bbf
Result: false
Outside after call: 1222
Outside before call
Normal method: 34b66124-ccb8-4797-ac63-786a5ece4ef7
Fallback method: 34b66124-ccb8-4797-ac63-786a5ece4ef7
Result: false
Outside after call: 1317
Outside before call
Normal method: d6be6ce0-d681-47e9-b2cf-c8fe33bbe732
Fallback method: d6be6ce0-d681-47e9-b2cf-c8fe33bbe732
Result: false
Outside after call: 8272
Outside before call
Normal method: 6e257487-902f-4bd7-9be2-615e11e33b7d
Fallback method: 6e257487-902f-4bd7-9be2-615e11e33b7d
Result: false
Outside after call: 11914
Outside before call
Normal method: 55046796-1e81-41e7-8692-e4f2089237ce
Fallback method: 55046796-1e81-41e7-8692-e4f2089237ce
Result: false
Outside after call: 7359
Outside before call
Normal method: 9c8587fd-5312-48a1-9403-be7a584b0c6e
Fallback method: 9c8587fd-5312-48a1-9403-be7a584b0c6e
Result: false
Outside after call: 5797
Outside before call
Fallback method: 81c76b14-cb69-4a96-a898-ea8f40cf2dd2
Result: false
Outside after call: 4237
Outside before call
Normal method: d2a9e8b9-5476-49bd-9aca-f5eb107b794f
Fallback method: d2a9e8b9-5476-49bd-9aca-f5eb107b794f
Result: false
Outside after call: 6423
Outside before call
Fallback method: 757922a2-da64-4860-ad06-b85ab9f4ef3f
Result: false
Outside after call: 6541

You can see that  the method does go into the fallback, but the execution time is way longer than 200ms and is even sometime very long (> 10s), longer than the execution time of the method without Hystrix (between 3 to 5 seconds on my PC). 

I have also this code which use HystrixCommand instead of annotations with similar inconsistent results:

`@SpringBootApplication
@EnableCircuitBreaker
public class HystrixPocCommandApplication {

    public static void main(String[] args) {
        SpringApplication.run(HystrixPocAnnotationApplication.class, args);
    }

    @Component
    public static class HystrixPocRunner implements CommandLineRunner {

        @Autowired
        private HystrixPocAnnotationApplication.TestService testService;

        @Override
        public void run(String... args) throws Exception {
            for (int i = 0; i < 10; i++) {
                long start = System.currentTimeMillis();
                System.out.println("Outside before call");
                System.out.println("Result: " + new TestCommand(UUID.randomUUID().toString()).execute());
                System.out.println("Outside after call: " + (System.currentTimeMillis() - start));
            }
        }
    }

    public static class TestCommand extends HystrixCommand<Boolean> {

        private String testStr;

        public TestCommand(String testStr) {
            super(
                    Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("SystemX"))
                            .andCommandKey(HystrixCommandKey.Factory.asKey("TestCommand"))
                            .andThreadPoolKey(HystrixThreadPoolKey.Factory.asKey("TestCommand"))
                            .andCommandPropertiesDefaults(
                                    HystrixCommandProperties.Setter().withExecutionTimeoutInMilliseconds(200))
            );
            this.testStr = testStr;
        }

        @Override
        protected Boolean run() throws Exception {
            System.out.println("Normal method: " + testStr);
            Map<Integer, List<Integer>> map = new HashMap<>();
            for (int i = 0; i < 5000; i++) {
                map.put(i,new ArrayList<>());
                for (int j = 0; j < 5000 ; j++) {
                    map.get(i).add(j);
                }
            }
            return true;
        }

        @Override
        protected Boolean getFallback() {
            System.out.println("Fallback method: " + testStr);
            return false;
        }
    }
}`

I would expect the execution time to be around 200ms. Is that a bug? If not, what I am doing wrong?

**Comment by mattrjacobs** [comment]
Here's a commit where I add a unit test demonstrating interrupting compute-bound work via timeout: https://github.com/mattrjacobs/Hystrix/commit/57e9b44ed92a63e90b1efc64a86d1e0bba5ae50d

2 issues with your previous setup
1) You need to check for thread interruption every time you're about to attempt work
2) There's a non-trivial cost to setting up a HystrixCommand for the first time.

When I solved those issues (by checking for thread-interrupt, and doing a warm-up command before i measure, respectively), I get a command execution time right above 200ms

Example:
```
Normal method: warmup
Fallback method: warmup
Normal method: real
Fallback method: real
Got : false after : 205
```

**Comment by Nyamiou** [comment]
It's not a very satisfying answer, this was just an example, if I have a call to a library I can't change or a native call I can't add the "!Thread.currentThread().isInterrupted()" checks. What can I do in those cases?  Can't I have a reliable timeout without those checks?

**Comment by mattrjacobs** [comment]
This is just the way Java works.  There's no way to force a thread to stop - you can just attempt to interrupt it (which Hystrix does) and hope that it handles the InterruptedException.
