### ISSUE TITLE
Replacement call for a deprecated API

### ISSUE THREAD

**Issue by billyy** [Netflix/Hystrix#1520]
We are upgrading one of the project and they are using the following deprecated method.  Is that a replacement for this method?

HystrixPropertiesManager.setCommandProperties(hystrixCommandProperties, command)

**Comment by mattrjacobs** [comment]
The only class named `HystrixPropertiesManager` is `com.netflix.hystrix.contrib.javanica.conf.HystrixPropertiesManager` and it doesn't have that method (in master).

Can you clarify what method you're calling, and what you intend to replace it with?

**Comment by billyy** [comment]
We ended up removing that old code all together so you can close this
issue.  Someone was using this method to override behavior and I told them
to use archiaus instead.
