### ISSUE TITLE
The security of dashboard

### ISSUE THREAD

**Issue by jordandandan** [Netflix/Hystrix#1542]
I have deployed the hystrix in my on-line project and configured the hystrix dashboard servlet. Is it security enough to exposure the path :"/hystrix.stream"to the users ?

**Comment by mattrjacobs** [comment]
There's not much that any consumer of that endpoint can do beyond view the data (and concurrency is capped at 5 simultaneous streams).  

Your question is not very specific, but generally speaking, the fewer internals you expose about your system, the better off you are.  So I would expect you would want to limit access to that data to internal consumers (systems + human operators)

**Comment by sharadholani** [comment]
Can there be any sort of limitation on who can access this endpoint ? Maybe using some token .
