### ISSUE TITLE
Difference between circuitBreaker.enabled vs fallback.enabled

### ISSUE THREAD

**Issue by avirkar** [Netflix/Hystrix#1557]
What is the difference between the hystrix command properties circuitBreaker.enabled vs fallback.enabled.

I am able to validate that fallback.enabled property helps to direct the requests to the fallback method. But I dont see any change for the request when I change the value of circuitBreaker.enabled.

Can some one explain the exact difference between the two properties.

**Comment by mattrjacobs** [comment]
Does the Wiki page answer your questions?

https://github.com/Netflix/Hystrix/wiki/Configuration#fallback.enabled
https://github.com/Netflix/Hystrix/wiki/Configuration#circuitbreakerenabled

**Comment by avirkar** [comment]
Yeh, I did read this with 
fallback.enabled : I understand and see it working, using the boolean flag I can enable / disable the fallback method.

circuitbreaker.enabled : I assume that the open / close functionality of the circuit should be enabled / disabled but it does not work. Even if I have the flag false the circuit opens when I test my application with heavy load. 

Hence unable to figure out exactly what this (circuitbreaker.enabled) property does.

**Comment by mattrjacobs** [comment]
This property works by configuring the circuit-breaking policy for a command.  If enabled, it uses the default circuit-breaker impl, which will open the circuit after reaching a threshold of failure percentage.  If disabled, the circuit is permanently closed.

Please note that, at the moment, the property is only being read on startup, so you'll have to restart your application after changing this configuration.

Does that help explain what you're observing?

**Comment by avirkar** [comment]
Yeh, I got the therotical understanding of both the command properties.  I used Jmeter to send almost 10000 request so that I can test the circuit breaker property (Currently set to false). In this scenario the circuit should remain open even if the application is bombarded with failing requests. But once the threshould is crossed the circuit opens. I even restarted the application as you mentioned. 

The following is my policy.
@HystrixCommand(fallbackMethod = "reliableCommand", commandProperties = {
			@HystrixProperty(name = "fallback.enabled", value = "true"),
			@HystrixProperty(name = "circuitBreaker.enabled", value = "false"),
			@HystrixProperty(name = "circuitBreaker.requestVolumeThreshold", value = "200")

	})

**Comment by mattrjacobs** [comment]
A note on terminology: circuit being OPEN implies requests fail-fast, and circuit being CLOSED implies requests execute normally.

When you set `circuitBreaker.enabled` to false, that should mean that the circuit is perpetually CLOSED, and never returns a status of SHORT_CIRCUITED.

What command outcomes are you encountering?

**Comment by avirkar** [comment]
Hello Matt, Today I tried test it with a good amount of load using jmeter and seems like the flag is working as expected. 
I think we can close this issue.

**Comment by ysheikh245** [comment]
If a circuit is SHORT_CIRCUITED or in other words (fail-fast), does it call the fallBackMethod() or rejects the request directly w/o touching the fallBackMethod(). Rejecting the request as 'Internal Server Error'.

**Comment by Ubunfu** [comment]
> If a circuit is SHORT_CIRCUITED or in other words (fail-fast), does it call the fallBackMethod() or rejects the request directly w/o touching the fallBackMethod(). Rejecting the request as 'Internal Server Error'.

I think that depends on whether you have [```hystrix.command.default.fallback.enabled```](https://github.com/Netflix/Hystrix/wiki/Configuration#fallback.enabled) set to ```true``` or ```false```.
