### ISSUE TITLE
improve documentation on how execution timeouts work and pitfalls with commands not catching InterruptedException

### ISSUE THREAD

**Issue by jack-kerouac** [Netflix/Hystrix#1562]
I spent quite some time understanding that Hystrix commands that execute longer than the configured `executionTimeoutInMilliseconds` are canceled from 'a client's perspective', but only an `InterruptedException` is thrown on the executing thread. Most HTTP libraries ignore this exception and thus, the command keeps on executing. Without setting proper timeouts on the HTTP client, the Hystrix thread pool might get saturated very quickly.

I think this behavior should be better documented in the wiki. Related is e.g. this issue: #1519 or other where people opened issues for not understanding this behavior.

**Comment by mattrjacobs** [comment]
Thanks for the feedback @jack-kerouac .  I added a couple sentences here: https://github.com/Netflix/Hystrix/wiki/How-it-Works#6-hystrixobservablecommandconstruct-or-hystrixcommandrun

**Comment by jack-kerouac** [comment]
Thanks, sounds good already! May I suggest the following extension in its own paragraph:

Please note that there's no way to force the latent thread to stop work - the best Hystrix can do on the JVM is to throw it an `InterruptedException`. If the work wrapped by Hystrix does not respect `InterruptedExceptions`, the thread in the Hystrix thread pool will continue its work, though the client already received a `TimeoutException`. This behavior can saturate the Hystrix thread pool, though the load is 'correctly shed'. Most Java HTTP client libraries do not interpret `InterruptedExceptions`. So make sure to correctly configure connection and read/write timeouts on the HTTP clients.

Feel free to change. Thanks a lot!

**Comment by mattrjacobs** [comment]
Your version was more helpful to a consumer of the doc, so I hope you don't mind that I just used yours as-is.  Thanks for the contribution!

**Comment by jack-kerouac** [comment]
Not at all. Thanks!
