### ISSUE TITLE
Dashboard Type Error in tmpl.js:40

### ISSUE THREAD

**Issue by pparth** [Netflix/Hystrix#157]
Hello,

After some hours of working, Dashboard starts not showing everything that has to do with numbers and metrics in some of the commands presented. The line and circle though are active as usual. Image attached.
![2013-07-24 06 37 46 00001](https://f.cloud.github.com/assets/2901293/846937/a98b583c-f42b-11e2-80e2-d626a18a2c09.png)

I also get the following error in javascript. Dont know if this has to do with the cropped image though.

TypeError in tmpl.js:40
get stack: function () { [native code] }
message: "Object #<error> has no method 'replace'"
set stack: function () { [native code] }
**proto**: Error

**Comment by syamsathyan** [comment]
Yes, this issue still exists in org.springframework.cloud:spring-cloud-starter-parent:Angel.SR4

TypeError: isCircuitBreakerOpen.replace is not a function(…)
tmpl.js:40 TypeError: isCircuitBreakerOpen.replace is not a function(…)
tmpl.js:40 TypeError: isCircuitBreakerOpen.replace is not a function(…)
tmpl.js:40 TypeError: isCircuitBreakerOpen.replace is not a function(…)
