### ISSUE TITLE
Are there any future plans to migrate hystrix from java 6 to java 8 (sourceCompatibility) ?

### ISSUE THREAD

**Issue by sajjusajuu** [Netflix/Hystrix#1582]
I have seen that hystrix uses JDK 6 platform. Are there any plans to change the platform to JDK 8
and there by updating all other old dependencies like updating servlet-api from 2.5 to 3.0 and many others like these?

**Comment by spencergibb** [comment]
jdk 8 and the servlet api aren't related are they?

**Comment by sajjusajuu** [comment]
Sorry for my vague question. 

I see that the jetty [implementation](http://www.eclipse.org/jetty/documentation/9.4.5.v20170502/what-jetty-version.html
) of servlet api 3.1 are build for java 7 or higher and we use jetty 9. And so I thought that we could not use it for java 6. 
But as the travis build uses jdk 8, I don't think there would be an issue. But I think as the gradle checks for source compatibility of java 6, we would not be able to use java 8 features like lambdas or stream. Or could we? 


My actual intension of the question is:
I see we are using web.xml in web apps. If we could change the servlet specs to 3.1 or more than we can use annotations on top of servlet classes or filter classes instead of these configuration files. I wanted to implement these. Can I do that?

Thanks!

**Comment by mattrjacobs** [comment]
There was a decent amount of pushback from Hystrix users in updating from JDK 1.6 -> 1.8 within the Hystrix 1 series.  

As far as Servlet 3.1 goes, what specific bits of Hystrix relate to servlets?
