### ISSUE TITLE
Update documentation on allowMaximumSizeToDivergeFromCoreSize

### ISSUE THREAD

**Issue by JasonMathison** [Netflix/Hystrix#1583]
The documentation indicates that the allowMaximumSizeToDivergeFromCoreSize configuration option is available in 1.5.7.
https://github.com/Netflix/Hystrix/wiki/Configuration#allowMaximumSizeToDivergeFromCoreSize

Please update the documentation to reflect that allowMaximumSizeToDivergeFromCoreSize first became available in 1.5.9.

The reason for this change is that allowMaximumSizeToDivergeFromCoreSize configuration was being ignored, and hence completely non-functional until 1.5.9.  Here is the bug for this issue: https://github.com/Netflix/Hystrix/issues/1434

**Comment by mattrjacobs** [comment]
Done.  Thanks for the report
