### ISSUE TITLE
Wrong hystrix event type for fallback missing

### ISSUE THREAD

**Issue by JagmohanSharma** [Netflix/Hystrix#1600]
In my annotated hystrix command I have not defined any fallback method. But when my command execution gets fail due to force fully open circuit, it gives me 

     eventNotifier.markEvent(HystrixEventType.FALLBACK_FAILURE, commandKey);

But I think this should be 

     eventNotifier.markEvent(HystrixEventType.FALLBACK_MISSING, commandKey);

which has a check for if (fe instanceof UnsupportedOperationException) {} before making event for FALLBACK_MISSING.

Can somebody confirm whether this is expected? Any help would be appreciated.

**Comment by mattrjacobs** [comment]
@dmgcodevil Do you know if it is possible to support FALLBACK_MISSING in Javanica?

**Comment by dmgcodevil** [comment]
@mattrjacobs will take a look shortly

**Comment by dmgcodevil** [comment]
https://github.com/Netflix/Hystrix/pull/1616

**Comment by JagmohanSharma** [comment]
@dmgcodevil I also found the cause and tested yesterday. I was about to provide information here to seek possibilities to contribute :)

**Comment by JagmohanSharma** [comment]
@mattrjacobs  in which release we can expect to be available ? :)

**Comment by mattrjacobs** [comment]
This is released in v1.5.13 now
