### ISSUE TITLE
Invalid configuration key in the Wiki

### ISSUE THREAD

**Issue by geczirobert** [Netflix/Hystrix#1608]
In the last [section](https://github.com/Netflix/Hystrix/wiki/Configuration#metricsrollingstatsnumbuckets-1) of the configuration wiki the configuration key is invalid
Instead of `hystrix.threadpool.default.metrics.rollingPercentile.numBuckets` and `hystrix.threadpool.HystrixThreadPoolProperties.metrics.rollingPercentile.numBuckets` should be `hystrix.threadpool.default.metrics.rollingStats.numBuckets` and `hystrix.threadpool.HystrixThreadPoolProperties.metrics.rollingStats.numBuckets`.

**Comment by geczirobert** [comment]
in [HystrixThreadPoolProperties.java](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java#L92):
` this.threadPoolRollingNumberStatisticalWindowBuckets = getProperty(propertyPrefix, key, "metrics.rollingStats.numBuckets", builder.getMetricsRollingStatisticalWindowBuckets(), default_threadPoolRollingNumberStatisticalWindowBuckets);`

**Comment by mattrjacobs** [comment]
Thanks @geczirobert !  Just fixed the referenced Wiki page
