### ISSUE TITLE
Observable.flatMap() multiple executions when multiple subscribers

### ISSUE THREAD

**Issue by badbob** [Netflix/Hystrix#1609]
Hi, everyone. 

I have a sample project illustrating issue I'm working in commercial project: https://github.com/badbob/hystrix-test

The issue is about `Observable.flatMap()` calling N-times when Observable has N subscribers. In my case there is a Hystrix command creation into flatMap() lambda argument. So, I have N same Hystrix command creation and execution with the same parameters. 

Is there a way to avoid/workaround this issue?

**Comment by mattrjacobs** [comment]
Reading some RxJava docs may be helpful.  In this case, you can use `command.observe().cache().flatMap(...)`.

The [cache operator](http://reactivex.io/documentation/operators/replay.html) only executes the cached computation a single time, then allows multiple subscribers to get the same value without a recomputation.

**Comment by badbob** [comment]
@mattrjacobs 

Here is an workaround of this issue: https://github.com/badbob/hystrix-test/commit/1cbd65809e7f90554aa0581e28713be731657ebe#diff-db81be2143f1208884ae96e548f74d12 based of new `ReplaySubject` creation.

And here is an implementation suggested by you: https://github.com/badbob/hystrix-test/commit/09f1721efb4778180bf01d44104e33a9e33981d3#diff-db81be2143f1208884ae96e548f74d12

And it doesn't work - test fails occurs. Can you please investigate? Bug is possible.
