### ISSUE TITLE
localhost:port/hystrix.stream not working

### ISSUE THREAD

**Issue by sathesherode** [Netflix/Hystrix#1619]
I am trying to configure the hystrix.stream in my spring boot web application. I have added the below dependency.

		<dependency>
		    <groupId>com.netflix.hystrix</groupId>
		    <artifactId>hystrix-metrics-event-stream</artifactId>
		    <version>1.5.12</version>
		</dependency>

Then I have created web.xml in the **src/main/webapp/WEB-INF** folder and the content of my web.xml is below:

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://java.sun.com/xml/ns/javaee" xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
	version="2.5">

	<servlet>
		<description>Hystrix</description>
		<display-name>HystrixMetricsStreamServlet</display-name>
		<servlet-name>HystrixMetricsStreamServlet</servlet-name>
		<servlet-class>com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet</servlet-class>
	</servlet>

	<servlet-mapping>
		<servlet-name>HystrixMetricsStreamServlet</servlet-name>
		<url-pattern>/hystrix.stream</url-pattern>
	</servlet-mapping>

</web-app>
```

But when I enter the url **http://localhost:8082/hystrix.stream** I am getting 404 error. I am struggling to fix this for 2 days. Could anyone can help on this?

**Comment by mattrjacobs** [comment]
It's hard to say without having access to your project.  There's a sample webapp that includes the metrics stream at: [https://github.com/Netflix/Hystrix/tree/master/hystrix-examples-webapp](https://github.com/Netflix/Hystrix/tree/master/hystrix-examples-webapp).  Can you try that out and see where yours differs?

**Comment by sathesherode** [comment]
Hi @mattrjacobs I have my project here [https://github.com/sathesherode/HystrixLS.git](url). When I get exception, the fallback method is not at all executed.

**Comment by mattrjacobs** [comment]
@sathesherode Are you reporting a new problem around executing commands, or are you still chasing down how to get the metrics stream working?

**Comment by sathesherode** [comment]
Hi mattrjacobs, I got this working. Thanks.

**Comment by minghuiliu2008** [comment]
Can you share how you fixed the issue

**Comment by minghuiliu2008** [comment]
I am having the same issue.

**Comment by asgs** [comment]
@minghuiliu2008 see if [my comment](https://github.com/Netflix/Hystrix/issues/1566/issuecomment-324619231) on a similar issue helps you.
