### ISSUE TITLE
Use custom circuit breaker resolution strategy

### ISSUE THREAD

**Issue by jkubrynski** [Netflix/Hystrix#1620]
Currently, Hystrix allows determining circuit breaker only by command name. It would be useful to be able to inject custom resolution strategy. For example, when you want to have circuit-breaker per target host, the only way is to append hostname to the command name. But it leads drives us to autonomously open all circuits. If I know that host is not responding it makes sense to open all circuits related the particular host, which is not possible at the moment. I could manage the circuit-breaker instances on my own, but it's not possible to inject it into the `HystrixCommand`.

**Comment by mattrjacobs** [comment]
Is this a duplicate of #9?

**Comment by jkubrynski** [comment]
Sorry, I missed this issue.
