### ISSUE TITLE
always download the gradle-4.0-all.zip when using the gradlew jettyRun for dashboard

### ISSUE THREAD

**Issue by rony13** [Netflix/Hystrix#1642]
when use the gradlew jettyRun to run the dashborad,  it always show me that downloading the gradle-4.0-all.zip and nothing happend. So i use wget to download the zip and put it to the gradle/wrapper/dists/. But it seems not work when i redo the gradlew jettyRun

**Comment by wickerlabs** [comment]
How did you resolve this?
