### ISSUE TITLE
Defining Hystrix configuration in application.yml does not work

### ISSUE THREAD

**Issue by deepi2003** [Netflix/Hystrix#1691]
I defined the Hystrix timeout configuration in application.yml but during runtime Hystrix still picks up default configuration. 

I am using Hystrix-javanica and define the hystrix configuration as below:
hystrix:
  command:
    <commandkey>:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000

I want to define all the configuration in application.yml to have different values for different environments.

Can you please let me know if I am missing something or is it not possible?

**Comment by spencergibb** [comment]
`application.yml` is part of spring-boot/spring-cloud

**Comment by deepi2003** [comment]
So does that mean I cannot define hystrix configuration in application.yml for hystrix?
Is there any other way I can define different values for  these properties based on environment which is recommened?

**Comment by spencergibb** [comment]
It does, but you need to be using spring-cloud-netflix and this isn't the place to ask about it.

**Comment by deepi2003** [comment]
Thanks for the response
