### ISSUE TITLE
HystrixSampleSseServlet not sending data when ShallowEtagHeaderFilter is used

### ISSUE THREAD

**Issue by dsfratila** [Netflix/Hystrix#1726]
There's an issue when calling hystrix's `/hystrix.stream` endpoint and the Spring's `ShallowEtagHeaderFilter ` is used that basically caches the response content indefinitely and no response is sent to the client. Also the connection is kept alive and not terminated if the client cancels the request so that if more than the `numberConnections` request are made, a response with 503 (MaxConcurrentConnections reached) will be returned.

To reproduce, activate the filter as a bean in the spring context:

```
    @Bean
    public Filter shallowETagHeaderFilter() {
        return new ShallowEtagHeaderFilter();
    }
```

**Comment by spencergibb** [comment]
This is not the spring cloud Netflix repository
