### ISSUE TITLE
socket connection and response timeout

### ISSUE THREAD

**Issue by colossal20** [Netflix/Hystrix#1740]
How to set socket connection and response timeout in hystrix? 
I haven't seen any example or way of doing it. The only thing available is setting [thread timeout](https://github.com/Netflix/Hystrix/wiki/Configuration#executionisolationthreadtimeoutinmilliseconds). I want to set different response timeout to my dependencies in different situations.

**Comment by spencergibb** [comment]
Hystrix doesn't have sockets. It wraps things that might.

**Comment by mmaredia** [comment]
So does it tell if socket connection timed out or response timed out?
