### ISSUE TITLE
Help:why we create fallback method name and parameter same with controller name?

### ISSUE THREAD

**Issue by sagarjadhav968** [Netflix/Hystrix#1791]
@HystrixCommand(fallbackMethod = "authenticateFallBack")
	@RequestMapping(value = "/authenticate", method=RequestMethod.POST, produces=MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<ResponseBean> authenticate(@RequestBody Object object){
		org.springframework.http.HttpHeaders headers = new org.springframework.http.HttpHeaders();
		headers.setAccept(Arrays.asList(MediaType.APPLICATION_JSON));
		headers.setContentType(MediaType.APPLICATION_JSON);
		HttpEntity request = new HttpEntity(object, headers);
		ResponseEntity response = this.restTemplate.exchange("http://authservice/auth/authenticate", HttpMethod.POST,request,ResponseBean.class);
		return response;
	}
	
	public ResponseEntity<ResponseBean> authenticateFallBack(Object object){
		ResponseBean response = new ResponseBean(false, "Unable to connect to requested Auth Service, please try after some time", "error", null);
		return new ResponseEntity<ResponseBean>(response, HttpStatus.OK);
	}

**Comment by TomCools** [comment]
Sorry, it is pretty unclear what your actual question is here?
