### ISSUE TITLE
how can caller thread walkaway? if not, what is the difference between thread isolation and semaphore isolation?

### ISSUE THREAD

**Issue by ayumiono** [Netflix/Hystrix#1823]
Hi everyone, i am new to Hystrix, and got a question,
I read a description from wiki it says "Clients (libraries, network calls, etc) execute on separate threads. This isolates them from the calling thread (Tomcat thread pool) so that the caller may “walk away” from a dependency call that is taking too long."

Can someone tell me more detail about the "walk away". How can the calling thread walk away, cause at the end, we always have to wait for the dependency result (Future.get()), as a result you will consume as many Tomcat thread pool (or other resources)  as the  hystrixcommand thread pool size.  In my opinion, the thread isolation just the same as semasphore isolation, both two can just shed load. 

maybe i misunderstand somewhere, hope someone can help me

THX!!!

**Comment by indraneelb1903** [comment]
You are right , that in the end you will have to do `future.get()` to get the result . I think the key difference between the both is in thread isolation you can wait for a certain time for a task to finish executing. If it does not finish executing in that time , then simply cancel it . Look at the method `future.get(timeout,TIMEUNIT)` . You can read more about it here . You won't be able to do this in semaphore isolation and will have to wait for a task to complete executing.
https://docs.oracle.com/javase/8/docs/api/?java/util/concurrent/Future.html

**Comment by ayumiono** [comment]
thanks @indraneelb1903 , I misunderstood the thread isolation features of hystrix. I thought the thread isolation means that you can let the isolate thread pool process the rest business of a cmd, and the call thread can walk out and process the other requests(just like what netty nio does) to bring me an increase in throughput. 
And i read a description in hytrix wiki, it generally says "if you believe the thirdpart dependency library that it can deal timeout perfectly, you can use semaphore isolation instead" , i finally  understood that thread isolation just do the automatic timeout job.
thank you anyway @indraneelb1903
