### ISSUE TITLE
executionType(async or sync..) determined by methed return type not by annotation

### ISSUE THREAD

**Issue by ailinzhou** [Netflix/Hystrix#1847]
**This issue is useless, Please close this issue.**
Currently, in javanica the method annotated by ```@HystrixCommand```  is executed async or sync determined by the method return type. 
```
    public static ExecutionType getExecutionType(Class<?> type) {
        if (Future.class.isAssignableFrom(type)) {
            return ExecutionType.ASYNCHRONOUS;
        } else if (isRxType(type)) {
            return ExecutionType.OBSERVABLE;
        } else {
            return ExecutionType.SYNCHRONOUS;
        }
    }
```
This is no convenience in situation when sometimes I want to be asynchronous, sometimes I want to synchronize. Can we determine executionType by annotation and return type?  e.g. add a element  in ```@HystrixCommand```。
```
    public @interface HystrixCommand {
              ...
              ExecutionType executeType();
              ...
```

**Comment by Zalion** [comment]
I realized that use the return type is the correct way. we can't process the method annotated with ASYNCHRONOUS but the return type is not a future and we no need ExecutionType element in HystrixCommand annotation.

**Please close this issue.**
