### ISSUE TITLE
Hystrix release cycle and maintain

### ISSUE THREAD

**Issue by amizurov** [Netflix/Hystrix#1876]
Hi everyone, anybody can provide information about Hystrix release cycle and who is major maintainer ? Latest release was 1 year ago, we have a lot of issues (( and we would like to fix them.

**Comment by andystanton** [comment]
Sharing these sentiments - it would be good to know the status of the project!

I've also reached out via Google groups (https://groups.google.com/forum/#!topic/hystrixoss/-R-SXCFlldc) and Twitter (https://twitter.com/andy_stanton/status/1057580045336641536).

**Comment by YevgenyDrozdov** [comment]
Hello @timbozo, could you advise on the above questions, please? We are really looking forward to news about the Hystrix future. Thank you!

**Comment by andystanton** [comment]
Looks like #1783 and #1822 have been open for many months without response as well :(

**Comment by timbozo** [comment]
We apologize for the slow response to this question.  Hystrix has now been transitioned into maintenance mode, and we have updated the Readme with the new details.
