### ISSUE TITLE
Re-release Hystrix 1.5.11 

### ISSUE THREAD

**Issue by elandau** [Netflix/Hystrix#1891]
The current Netflix internal usage of Hystrix is pinned to version 1.5.11. There are issues and instabilities to Hystrix 1.5.13 that make it problematic to use. For Netflix, the primary goal at this point is maintaining Hystrix stability, even if that means accepting known issues that need to be worked around. To this end, Hystrix 1.5.11 should be re-released to Maven Central as Hystrix 1.5.14 so that the latest version of Hystrix in Maven Central is at a known-stable state.

**Comment by andystanton** [comment]
> For Netflix, the primary goal at this point is maintaining Hystrix stability, even if that means accepting known issues that need to be worked around.

@elandau thanks, this helps shed a bit of light on Netflix's internal approach to Hystrix. Can you confirm if the project is going to be maintained in the future e.g. as asked #1876?
