### ISSUE TITLE
Readme.md file has link to 'medium' (medium.com) site

### ISSUE THREAD

**Issue by Pavitrag** [Netflix/Hystrix#2010]
Hi,

This is about the readme file having link to Medium (medium.com) website instead of direct link to Netflix engineering blog (netflixtechblog.com)

Medium is a site where content is not freely viewable. For a particular user, apart from initial few articles being freely available to view the rest are not freely viewable. Once you exhaust your free quota, you need to pay to view anymore articles that you want to view.

Given above, I see that readme.md @ https://github.com/Netflix/Hystrix has following link: https://medium.com/@NetflixTechBlog/performance-under-load-3e6fa9a60581

Is it not better to have direct link to the Netflix engineering blog  (https://netflixtechblog.com/toward-a-better-quality-metric-for-the-video-community-7ed94e752a30) embedded in the readme file instead of the link to Medium site?

Thanks if you have change the readme file accordingly.

- Pavi

**Comment by emrecosar** [comment]
Hi @Pavitrag 
I see that "Netflix Technology Blog" user blog posts in Medium are all free to view. I also see that Netflix Tech Blog website is also served under Medium and free too.

**Comment by Pavitrag** [comment]
Hi @emrecosar 
I'm happy as long as all the engineering blogs are all freely viewable. 
Thanks! for letting me know.
