### ISSUE TITLE
It doesn't work, configuration in 'application-xxx.yml' 

### ISSUE THREAD

**Issue by alibbbian** [Netflix/Hystrix#2024]
_org.springframework.cloud:spring-cloud-starter-netflix-hystrix_:**2.2.6.RELEASE**
_org.springframework.boot:spring-boot-starter-parent_:**2.5.7**
_spring-cloud.version_=**2020.0.4**

application-dev.yml : 
`hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 8000`

**not work**

`System.setProperty("hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds", "8000");`

**it works, and any other way?**

**Comment by retozigerlig** [comment]
I'm facing the same issue. Defining the value via yaml does not work, defining it via environment variable works.

**Comment by alibbbian** [comment]
> I'm facing the same issue. Defining the value via yaml does not work, defining it via environment variable works.

my problem is less this:
```
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-netflix-archaius</artifactId>
```
add this, now it works
