### ISSUE TITLE
Hystrix Command should be cancellable

### ISSUE THREAD

**Issue by panterose** [Netflix/Hystrix#220]
At the moment, if you call .queue() on a command and get a future, you cannot call the cancel() method and abort its execution. This is true for the current 1.3.XX version (it seems to work if you don't use the cache for some reason) but also in the upcoming 1.4 version.

I can supply a reduced code sample if needed, but it's very easy to reproduced. It's an issue for me as we have some long running command.

We also have the case where we encapsulate child command inside main command, ideally the cancel() should be cascading.

**Comment by mattrjacobs** [comment]
Talked to @benjchristensen about this.  Since the semantics are slightly different than ```Subject.refCount()```, it will take some time/care to do this properly.  As a result targeting this for 1.4 series, but not gating RC7 on it.

**Comment by mattrjacobs** [comment]
This is fixed in #1204.  Will be released in 1.5.3
