### ISSUE TITLE
About the lastHealthCountsSnapshot

### ISSUE THREAD

**Issue by jlming6** [Netflix/Hystrix#235]
Hey Ben, one question:
Once the HystrixCircuiBreaker is open, all requests will be SHORT_CIRCUITED (one of the failure), then after circuitBreakerSleepWindowInMilliseconds, will try 1 time, if it is successful, will call metrics.resetCounter();
But the lastHealthCountsSnapshot is not be reseted. and when other request comes, and find the health.getErrorPercentage() > properties.circuitBreakerErrorThresholdPercentage().get()(because all requests in last several seconds are SHORT_CIRCUITED, so in lastHealthCountsSnapshot, all are failure)  , so comes in another short circuit, and so on and so on.

So my question is why metrics.resetCounter() not clear lastHealthCountsSnapshot, and why SHORT_CIRCUITED is one of failure when calculate getErrorPercentage?

Thanks very much.

**Comment by mattrjacobs** [comment]
Confirmed via code review that this issue was fixed in #236.  @jlming6 Please re-open if you see any evidence that demonstrates otherwise.
