### ISSUE TITLE
Random SynchronousQueue Rejection

### ISSUE THREAD

**Issue by jdh9862** [Netflix/Hystrix#237]
I have some code that periodically uses HystrixCommand.execute() to request data from a remote service. In my program, only a single thread will ever call this command, but I occasionally get a RejectedExecutionException. it seems like execute() is returning to the calling thread before the execute thread is released from the thread pool. Reproducing this in production code has been inconsistent at best, but I believe this unit test mirrors what I am seeing.

```
	@Test
	public void testExecuteLoop() throws Exception {
		int i = 0;
		try {
			for (; i < 100000; i++ ) {
				new FetcherCommand<Integer>( "testExecuteLoop", 1, 1000 ) {
					@Override
					protected Integer run() throws Exception {
						return null;
					}
				}.execute();
			}
		} catch ( Exception e ) {
			// Report how many iterations were executed
			System.err.println( i );
			throw e;
		}
	}

	private abstract class FetcherCommand<cT> extends HystrixCommand<cT> {
		public FetcherCommand( String commandName, int poolSize, int timeout ) {
			super(
					HystrixCommand.Setter.withGroupKey(
							HystrixCommandGroupKey.Factory.asKey( commandName ) )
							.andThreadPoolKey( HystrixThreadPoolKey.Factory.asKey( commandName ) )
							.andCommandKey( HystrixCommandKey.Factory.asKey( commandName ) )
							.andCommandPropertiesDefaults( HystrixCommandProperties.Setter()
									                               .withExecutionIsolationStrategy( THREAD )
									                               .withExecutionIsolationThreadTimeoutInMilliseconds( timeout ) )
							.andThreadPoolPropertiesDefaults( HystrixThreadPoolProperties.Setter().withCoreSize( poolSize ) )
			);
		}
	}
```

**Comment by mattrjacobs** [comment]
@jdh9862 I confirmed this behavior via your unit test, thanks for providing that!  Here's what I think is happening:

Your thread pool of size 1 and a SynchronousQueue is the most rejection-prone way to configure the system.  Increasing the pool size or using a non-zero queue size would both give you a buffer to tolerate the raciness of the command execution.

When your command finishes up (in the Hystrix thread), it invokes either ```onCompleted()``` or ```onError()```.  The calling thread is waiting for this, and as soon as this thread gets scheduled by the OS, it cycles through to the next iteration of the unit test.  Note that this is racing against anything which runs after the ```onCompleted```/```onError``` on the Hystrix thread.  

I can't see any code which Hystrix is adding after these events, but the Java standard library has to, at a minimum, do thread-pool bookkeeping.  My guess is that that's what you're seeing.

Also, note that a HystrixCommand that experiences a timeout will consume a thread until it finishes naturally or respects a thread interruption, so your calling code will have to handle the case of an ```execute()``` returning while the underlying Hystrix thread is still busy anyway.

**Comment by mattrjacobs** [comment]
AFAICT, there's nothing to do in the Hystrix code for this issue.  Closing.  @jdh9862, please re-open if you want to discuss this further.
