### ISSUE TITLE
Explore use of backup requests to handle long-tail latency

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/Hystrix#25]
I would like to explore the use of backup requests and adding them to Hystrix as an optional tool for dealing with latency.

It has been discussed in several places (particularly referencing Google) such as these:

http://highscalability.com/blog/2012/3/12/google-taming-the-long-latency-tail-when-more-machines-equal.html
http://highscalability.com/blog/2012/6/18/google-on-latency-tolerant-systems-making-a-predictable-whol.html
http://www.bailis.org/blog/doing-redundant-work-to-speed-up-distributed-queries/
http://static.googleusercontent.com/external_content/untrusted_dlcp/research.google.com/en/us/people/jeff/Stanford-DL-Nov-2010.pdf

**Comment by mattrjacobs** [comment]
I think this belongs in Ribbon or Ocelli.
