### ISSUE TITLE
Additional "openCircuitHostNames" metric in HystrixMetricsPoller?

### ISSUE THREAD

**Issue by regunathb** [Netflix/Hystrix#271]
We have a Hystrix dashboard deployment that aggregates metrics from 100s of servers. While the dashboard shows counts of hosts where circuit is open, it would also be useful for it to provide host names. Is this a requirement for other deployments? How does Netflix identify hosts where circuits are open?

One approach that we implemented was to extend HystrixMetricsPoller to expose a "openCircuitHostNames" metric. This gets aggregated across hosts and is available in the dashboard for display. Is this additional metric worthy of adding to HystrixMetricsPoller?

Will be happy to submit a pull request with this code, if the idea is acceptable: https://github.com/Flipkart/phantom/blob/master/runtime/src/main/java/com/flipkart/phantom/runtime/impl/hystrix/HystrixMetricsPoller.java

**Comment by mattrjacobs** [comment]
@regunathb is this still something you're interested in?  i'm trying to understand what you would do with this information if it was available.  in general, when we see circuits trip in production, we like to know how many requests get shortcircuited but getting into the instance-level doesn't help us solve anything.  can you help me understand?

**Comment by regunathb** [comment]
@mattrjacobs thanks for asking. Knowing the host names is pretty useful for us when failures are localized to hosts. We run a proxy (called Phantom) that wraps all outgoing calls with Hystrix commands, including those to other local daemons that are smart clients(shard aware) to distributed data stores. There have been instances when these daemons degrade on the data access path. Having just a cluster view on no. of failing calls makes debugging hard.

**Comment by mattrjacobs** [comment]
This is not something that would be useful to us at Netflix.  If there's a way to implement this feature in a way that would solve your need and allow others to not use this feature, I'm happy to review it.  For now, marking as 'wontfix'
