### ISSUE TITLE
1.4: RequestLog with streaming results

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/Hystrix#302]
Now that we support an Observable we can have a stream of results. The RequestLog currently will mark SUCCESS for each onNext rather than the terminal event. 

Everything behaves fine for scalar responses, just need to fix it for a use case where the Observables returns more than 1 value.

**Comment by mattrjacobs** [comment]
The plan here is to add 2 new states to the HystrixRequestLog: ```EMIT``` and ```FALLBACK_EMIT```.  These represent the ```construct()``` and ```resumeWithFallback()``` methods invoking ```onNext()```.

Some possible new RequestLog strings:
[EMITx10, SUCCESS]
[EMITx3, FAILURE]
[EMITx4, FAILURE, FALLBACK_EMITx3, FALLBACK_SUCCESS]
[EMITx1, FAILURE, FALLBACK_EIMTx10, FALLBACK_FAILURE]

**Comment by mattrjacobs** [comment]
One question which I'm not sure about is if we want these new event types in the RequestLog of a ```HystrixCommand```.  It doesn't give any info, as we will always see an ```onNext```/```onCompleted``` pair (```EMIT```/```SUCCESS```) together.

But it also feels a little strange to special-case this.

My initial inclination is to only present these events for ```HystrixObservableCommand```, both to preserve the RequestLog as-is for this case, and because it's not especially meaningful

**Comment by benjchristensen** [comment]
I agree it should not be on the existing HystrixCommand, only ObservableCommand.

**Comment by mattrjacobs** [comment]
To make this concrete, here are some sample request logs for HystrixObservableCommand.  HystrixCommand request logs are unchanged, as described above.

* ```TestCommandWithMultipleValues[EMITx3, SUCCESS][30ms]```
* ```TestPartialSuccess[EMITx3, FAILURE][39ms]```
* ```TestPartialSuccessWithFallback[EMITx3, FAILURE, FALLBACK_EMITx4, FALLBACK_SUCCESS][39ms]```

**Comment by mattrjacobs** [comment]
Done in #604
