### ISSUE TITLE
Dashboard Circuit is not coming up for Host Name with HTTPS  port.( Example : https://hostname:9081).

### ISSUE THREAD

**Issue by contactarjun** [Netflix/Hystrix#313]
Hi ,
         I started implementing Hystrix for one of our REST(JSON) based service and found that Dash board circuit is not coming for host name with HTTPS port . Host Name with HTTP port is good though.

Does any of this community implemented for  Host name with HTTPS port, please do help me.

Thanks in Advance.

**Comment by maxx83git** [comment]
Hi Ben,
               I resolved the bug in Hystrix dash board's source code to make the circuit work with https protocal URL . 

Class Name : com.netflix.hystrix.dashboard.stream.ProxyStreamServlet
i wrote below new method to get Httpclient object based on the Protocal.

 /**
     * This Method returns the HttpClient object based on the protocol (Http or https)
     *
     * @param uri of type String
     *
     * @return  HttpClient
     */
    private HttpClient getHttpClient(String uri) throws Exception {
        HttpClient client = null;

        if ((uri != null) && (uri.trim().length() > 0) && uri.startsWith("https")) {
            SSLContext sslContext = SSLContext.getInstance("SSL");

            sslContext.init(null,
                new TrustManager[] {
                    new X509TrustManager() {
                        public X509Certificate[] getAcceptedIssuers() {
                            return null;
                        }

                        public void checkClientTrusted(X509Certificate[] certs, String authType) {
                        }

                        public void checkServerTrusted(X509Certificate[] certs, String authType) {
                        }
                    }
                }, new SecureRandom());

            SSLConnectionSocketFactory socketFactory = new SSLConnectionSocketFactory(sslContext,
                    SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);

            client = HttpClientBuilder.create().setSSLSocketFactory(socketFactory).build();
        } else {
            client = ProxyConnectionManager.httpClient;
        }

        return client;
    }



Thanks.

**Comment by mattrjacobs** [comment]
ACK that I saw this.  I'll get to this change in the next couple of days and get in in the next release for both 1.3.x and 1.4

**Comment by maxx83git** [comment]
Ben and Matt, thank you.

**Comment by mattrjacobs** [comment]
Isn't this bit: ```SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER``` just unconditionally ignoring any sort of certificate?  

I believe that if support for the HTTPS protocol is offered, it should actually offer security.

**Comment by mattrjacobs** [comment]
Closing due to age.  Please re-open if you'd like to continue the discussion
