### ISSUE TITLE
ObservableCommand with Multiple Values

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/Hystrix#315]
Should a `HystrixObservableCommand` be allowed to `onNext` more than 1 value?

I would like it to, but it has some challenges.

The `execute()` and `queue()` methods on `HystrixObservableCommand` expect a single value, whereas `observe()/toObservable()` can handle multiple.

This means the generic type `T` is wrong if the `Observable` chooses to return more than one.

A `HystrixObservableCommand<T>` would actually need to return like this:

- `List<T> execute()`
- `Future<List<T>> queue()`
- `Observable<T> observe()`

But most of the time this would not be wanted, so it would almost necessitate the generics defining it like this: `HystrixObservableCommand<T, List<T>>` or `HystrixObservableCommand<T, T>` to keep it scalar.

I'm not a fan of either of these.

So should we prohibit multi-valued responses? If so that defeats one of the benefits of `Observable` and the ability to stream a response back, such as using SSE. 

That said, multi-valued streaming responses also make the concept of timeout a little more confusing ... is it a timeout for the start of a response, or the entire response. I think it should be the entire response (and that's what it is right now).

Right now the code assumes a single generic like `HystrixObservableCommand<T>` and allows multi-valued responses when using `observe()/toObservable()` but will blow up if `execute()` or `queue()` are used like this (shortened):

```
Caused by: java.util.concurrent.ExecutionException: Observable onError
	at rx.internal.operators.BlockingOperatorToFuture$2.getValue(BlockingOperatorToFuture.java:120)
	at rx.internal.operators.BlockingOperatorToFuture$2.get(BlockingOperatorToFuture.java:112)
	at com.netflix.hystrix.HystrixExecutableBase$1.performBlockingGetWithTimeout(HystrixExecutableBase.java:488)
	at com.netflix.hystrix.HystrixExecutableBase$1.get(HystrixExecutableBase.java:387)
	at com.netflix.hystrix.HystrixExecutableBase.execute(HystrixExecutableBase.java:296)
	... 27 more
Caused by: java.lang.IllegalArgumentException: Sequence contains too many elements
```

I'd appreciate input on what direction to take this.

**Comment by mattrjacobs** [comment]
Where this stands:

* ```HystrixCommand<T>``` supports ```T execute()```, ```Future<T> queue()```, ```Observable<T> observe()```, and ```Observable<T> toObservable()```.  This always represents a scalar value.
*```HystrixObservableCommand<T>``` supports ```Observable<T> observe()``` and ```Observable<T> toObservable()```.  This represents a stream of values.

There's a new issue, scheduled for 1.5, tracking the ```HystrixFutureCommand```/```HystrixAsyncCommand```
