### ISSUE TITLE
Partial Success Fallback - HystrixObservableCommand

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/Hystrix#317]
A `HystrixObservableCommand` can stream [multiple values](https://github.com/Netflix/Hystrix/issues/315). This makes fallback a little more nuanced.

If it fails immediately, then nothing has been emitted via `onNext` and the `getFallback()` is easy to reason about.

If some values are emitted via `onNext()` but then it fails with `onError` (for any reason, including timeout) then it is partially successful. 

The `fallback()` will then be applied with `Observable.onErrorResumeNext` which means the partially successful `onNext` already emitted are still there, then the fallback applies.

The question is ... what does this mean for a user? for the developer of the fallback?

It is far more nuanced than a scalar response (using `HystrixCommand` or `HystrixAsyncCommand`).

I think we should at least rename `getFallback` to `resumeWithFallback` or something that communicates it's not an either-or, but additive (by resuming).

An implementation of a command should maintain state internally if needed so the fallback can know about partial success. I don't want to make that part of the `HystrixObservableCommand` itself though, as some will possibly want to cache the results to know what has been sent, but that's expensive to do all the time when not needed.

I'd appreciate further thoughts on how this should behave and be implemented.

**Comment by mattrjacobs** [comment]
This has already been implemented and unit-tested as ```resumeWithFallback()```
