### ISSUE TITLE
Fully resetting hystrix during testing to avoid exceptions

### ISSUE THREAD

**Issue by mboyers** [Netflix/Hystrix#319]
I'm using my own metrics publisher that I've registered.  When running tests, exactly one of them will succeed, and all of the others will fail due to the following:

     Caused by: java.lang.IllegalStateException: Another strategy was already registered.
        at com.netflix.hystrix.strategy.HystrixPlugins.registerMetricsPublisher(HystrixPlugins.java:180) ~[hystrix-core-1.3.18.jar:na]

In googling, I found other people with the same issue: https://groups.google.com/forum/#!topic/hystrixoss/Z7NKlGMr1PA

In that topic, they suggest the following.  It works, and I realize I don't need it all in my particular case.  But would it be possible to encapsulate all of the following into a single helper method to fully reset the hystrix state between tests?

    Hystrix.reset() 
    HystrixPlugins.getInstance().@concurrencyStrategy.set(null);
    HystrixPlugins.getInstance().@metricsPublisher.set(null);
    HystrixPlugins.getInstance().@notifier.set(null);
    HystrixPlugins.getInstance().@propertiesFactory.set(null);
    HystrixPlugins.getInstance().@commandExecutionHook.set(null);

**Comment by mattrjacobs** [comment]
PR in #452 adds the method ```HystrixPlugins.reset()```.  You may call this method, or ```Hystrix.reset()```, which also invokes it.

**Comment by mabn** [comment]
I don't think the solution from #452 works for HystrixMetricsPublisher. HystrixMetricsPublisherFactory has  a static INSTANCE field with static initializer which stores "current" HystrixMetricsPublisher.
Currently it's not possible to reset HystrixMetricsPublisher - it would require unloading HystrixMetricsPublisherFactory class (the INSTANCE can't be null, which means that there must be some HystrixMetricsPublisher in use).

Reasonable solution would be to alter HystrixMetricsPublisherFactory - to remove HystrixMetricsPublisherFactory.strategy and always call HystrixPlugins.getInstance().getMetricsPublisher() instead.

**Comment by himnabil** [comment]
Hello I maight have a similar problem 
I am trying to write an integrations tests for an rest service "A" with restAssured and SpringBootTest , and the A service  is calling an other Service "B" in an Hystrix command , I would like to rest hystix after eche  test from my test
