### ISSUE TITLE
Pushing metrics from Hystrix to Turbine?

### ISSUE THREAD

**Issue by carlanton** [Netflix/Hystrix#330]
Hi!

We're trying to use Hystrix and Turbine on Heroku. On Heroku, you can't connect to a specific "Dyno" (application instance) and therefore it's tricky to pull the metrics from all Hystrix endpoints into Turbine.
Is it possible to configure Hystrix to push the metrics to Turbine instead? We want to use the dashboard, so I guess we at least need to send SSE from Turbine.

Any ideas of how to solve this?

Thanks,
Anton

**Comment by kishorebattula** [comment]
Does this feature exists in the latest version?
