### ISSUE TITLE
HystrixMetricsStreamServlet.destroy() not invoked until container timeout

### ISSUE THREAD

**Issue by codependent** [Netflix/Hystrix#346]
__Scenario:__
1. JEE App with hystrix + hystrix-metrix-event-stream (v1.3.18). 
2. Hystrix dashboard requesting data to the App.
3. When we stop App in our server we see that the following loop doesn't stop: 

    HystrixMetricsStreamServlet.handleRequest(){
    ...  
       while (poller.isRunning() && !isDestroyed) {

The servlet's destroy() method is not called, thus **isDestroyed is not modified until timeout**. This makes sense since, according to the servlet spec: *void destroy() - Called by [...] This method is only called once all threads within the servlet's service method have exited or after a timeout period has passed.*

The problem is that since there is a running request, whenever we want to republish/stop our application, we have to wait 60 seconds until our container (Websphere Application Server 8) forces the destruction of the servlet.

**Comment by mattrjacobs** [comment]
@jboyd01 I don't have a great way of testing this, as I'm not familiar with Websphere or WAS.  Are you (or anyone else) still interested in submitting a pull request?

**Comment by mattrjacobs** [comment]
Moving this out of RC6.  I'm happy to merge in a PR from someone who experiences this issue, but don't have enough context to work on it myself.

**Comment by codependent** [comment]
@mattrjacobs I could (and will) submit jboyd01's solution as a PR. We are planning to implement Hystrix-enabled services in the next months and will definitely need that workaround.

**Comment by mattrjacobs** [comment]
Great, thanks @codependent!

**Comment by lasselasse** [comment]
We also just hit this issue running the metrics stream servlet from within embedded Jetty.
Very excited to see this being addressed soon!

**Comment by mattrjacobs** [comment]
@codependent / @lasselasse I just merged this into master.  Are you able to test @jboyd01 's solution currently or do you need an official RC release?

**Comment by codependent** [comment]
@mattrjacobs I don't really need a RC thanks. I'll test it tomorrow (out of the office right now) and let you know if it's OK.

**Comment by mattrjacobs** [comment]
Great, thanks @codependent

**Comment by codependent** [comment]
@mattrjacobs I just tested it, and it works OK. Thanks to @jboyd01 for this workaround.

**Comment by lasselasse** [comment]
@mattrjacobs tested the patch and it works great, thanks!

May I suggest the doGet method to be modified as follows so the servlet will directly reject requests once it has been shutdown? (At the moment it would still start a new HystrixMetricsPoller only to shut it down again.)

```
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        if (isDestroyed) {
            response.sendError(503, "Service is shut down.");
        } else {
            handleRequest(request, response);
        }
    }
```

**Comment by codependent** [comment]
I'd like to point out one important thing: jboyd01 suggested using another servlet's destroy() to invoke `HystrixMetricsStreamServlet.shutdown()` but **this won't work** under Websphere. 

The reason is that WS doesn't invoke any servlet.destroy() until all requests have finished. Yet, it does destroy JSPs (which is a kind of servlet, WTH?)

The only way I found to invoke `HystrixMetricsStreamServlet.shutdown()` is through a startup bean EJB. As simple as this:
```
import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.ejb.Singleton;
import javax.ejb.Startup;

import com.netflix.hystrix.Hystrix;
import com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet;

@Singleton
@Startup
public class HystrixStopper {

	@PostConstruct
	public void init(){
		System.out.println("init");
	}
	
	@PreDestroy
	public void preDestroy(){
		//Stops the metrics servlet
		HystrixMetricsStreamServlet.shutdown();
		//Shuts down all threads started by Hystrix
		Hystrix.reset();
	}
}
```

**Comment by lasselasse** [comment]
Since we run a Spring application I'm triggering the shutdown from a ContextClosedEvent-listener which is invoked before the embedded Jetty is shutdown.

**Comment by jboyd01** [comment]
@codependent I'm late replying, but wanted to note that I'm successfully exercising the shutdown of the stream servlet from a 2nd servlet under WebSphere 8.5.5.2 ND.  I have a HystrixControl servlet with just two methods:

```javascript
    public void destroy() {
        HystrixMetricsStreamServlet.shutdown();
        Hystrix.reset();
    }

    public void init(){
        // invoke code to set configuration source & register concurrency strategy
    }
```
and its registered via web.xml:
```javascript
    <servlet>
        <servlet-name>HystrixControl</servlet-name>
        <servlet-class>
            com.acme.projectx.init.HystrixControl
        </servlet-class>
        <load-on-startup>2</load-on-startup>
    </servlet>
```
I exercise my application, then hit the hystrix.stream with curl and let it stream away.  When I stop the application via admin console I get immediate shutdown - - the streaming stops and WebSphere reports the app as stopped in the logs within seconds of the stop attempt. 

I do like the options of doing this via an EJB and ContextClosedEvent listener.  I think it may be wise to start a doc page that details App Server specific implementation details.

**Comment by codependent** [comment]
@jboyd01 thanks for the feedback :-) Right now it doesn't work for us but it must be something container related so I'll take it into account when we move from 8.0.x.x to 8.5.

**Comment by mattrjacobs** [comment]
@codependent I'm inclined to close this issue and let you open a new issue with details specific to your case.  Does that sound OK to you?

**Comment by codependent** [comment]
@mattrjacobs It's alright to me.

**Comment by dsukner** [comment]
https://github.com/Netflix/Hystrix/pull/530 does not seem to have fixed the client disconnect detection on WebSphere
