### ISSUE TITLE
Mocking hystrix commands for unit-testing

### ISSUE THREAD

**Issue by alakshminarayanan** [Netflix/Hystrix#349]
In our unit-test suite, we have some unit-tests that
(a) explicitly test a hystrix command. Here I call the constructor of the command with mocked input params and call execute() on the command and verify behavior.
(b) we also have a unit-test in which a hystrix command is mocked, to test a different component.

These two tests run fine if I run them as stand-alone in eclipse, but when I run the full test-suite in gradle, the test #b fails due to an init error.

      Caused by:
        java.lang.IllegalStateException: Another strategy was already registered.
            at com.netflix.hystrix.strategy.HystrixPlugins.registerConcurrencyStrategy(HystrixPlugins.java:130)
            at com.netflix.nfhystrix.plugins.NFHystrixPlugins.<clinit>(NFHystrixPlugins.java:12)
            ... 15 more

Test #a run first and finished successfully. In test #b we use Mockito to mock a hystrix command. That causes the static block within NFHystrixPlugins to initialize which calls into HystrixPlugins::registerConcurrencyStrategy(). This fails because this was already initialized once in the JVM when test #a ran.

How do we get around this issue and be able to mock hystrix commands?

**Comment by bltb** [comment]
@alakshminarayanan, is the use of

```
new HystrixPlugins.UnitTest().reset()
```

going to leak an object? I am just *guessing* that it should not because (hopefully) there are no references to this object.

**Comment by alakshminarayanan** [comment]
Should not hopefully. Ideally reset should be just a static method, since it just resets a bunch of static variables.

**Comment by mattrjacobs** [comment]
#319 modified ```Hystrix.reset()``` to clear out all HystrixPlugins, allowing you to set a new one.  @bitb, @alakshminarayanan, I don't have a release with this functionality out yet, but you can build from master and test locally if you want to check it out.

**Comment by mattrjacobs** [comment]
Closing, since #319 should address this concern.  If there are more problems are testability, please re-open.

**Comment by alakshminarayanan** [comment]
This issue is now fixed. Thanks a bunch Matt for taking care of it.

**Comment by mattrjacobs** [comment]
Glad to hear it @alakshminarayanan .  Thanks for the feedback
