### ISSUE TITLE
Registering a HystrixEventNotifier

### ISSUE THREAD

**Issue by demian0311** [Netflix/Hystrix#355]
Is there an alternative way to give a `HystrixCommand` an instance of `HystrixEventNotifier`?

This JavaDoc leads me to believe it's on `HystrixCommand.Setter` but I don't see it implemented there.

```
     *  Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("GroupName"))
                .andCommandKey(HystrixCommandKey.Factory.asKey("CommandName"))
                .andEventNotifier(notifier);
```

https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java#L160

I'd like to log events and possibly send to Graphite.

Thanks!

**Comment by RakeshAMore** [comment]
hi @mattrjacobs , sorry for commenting on the closed issue. Need help to registered hystrx event notifier. I am using springboot and I want to send email alert if circuit is opened. I have some Custom notifier and planing to send email alert when HystrixEventType.SHORT_CIRCUITED in method markEvent of HystrixEventNotifier.  I am registering my event notifier using below line in my application class, but it seems, it is not getting called. Can you please assist me in this

HystrixPlugins.getInstance().registerEventNotifier(CustomHystrixEventNotifier.getInstance());
