### ISSUE TITLE
Limit memory consumption by removing cancelled tasks from thread pool

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#372]
Thanks to @galak for pointing out the issue.  I believe the correct solution is identical to the one made by @akarnokd in https://github.com/ReactiveX/RxJava/pull/1922.  This will compile with Java 6/7 but only take effect with a Java7 runtime.

**Comment by mattrjacobs** [comment]
I've done some preliminary investigation into this fix, and it requires replacing the use of ```ThreadPoolExecutor``` with ```SchedulerThreadPoolExecutor```, since that's the only concrete implementation that contains the ```removeOnCancelPolicy``` configuration.

That comes with some other side-effects: From what I can tell, threads get created eagerly, never get killed by idleness, and come with a default unbounded queue.  I'll need to do some more evaluation on this aspect.

**Comment by akarnokd** [comment]
The upcoming RxJava 1.0.5 has a solution for JDK 6 ScheduledThreadPoolExecutors as well by calling purge periodically (the functionality is there and [here](https://github.com/akarnokd/RxJava/blob/PublicAPIScheduledAction/src/main/java/rx/internal/schedulers/NewThreadWorker.java) I added some documentation on configurability just recently).

**Comment by mattrjacobs** [comment]
Thanks for calling that out, @akarnokd .  That looks like it would remove the plumbing around different JDKs from Hystrix, which would be nice.

**Comment by mattrjacobs** [comment]
Punting to 1.4.x - not blocking 1.4.0
