### ISSUE TITLE
Caching feature for javanica.

### ISSUE THREAD

**Issue by dmgcodevil** [Netflix/Hystrix#380]
Recently I was looking around javanica in order to find what hystrix features aren't implemented yet. For now I see only one feature to implement:  building cache keys using annotations and I have several approaches to implement it, so I would like to discuss it first.

Initially I thought about adding an ability to annotate each method parameter using @Cache annotation, for instance:
```java
@HystrixCommand
User getUserByParams(@Cache String id, String name, @Cache Integer age)
```
Each parameter annotated @Cache annotation will be used to build cache key. Algorithm is pretty simple: for each parameter annotated with @Cache annotation the toString() method will be invoked 
Basically this approach looks fine, but isn't convenient if you deal with complex arguments, for example:
```java
@HystrixCommand
User getUserByParams(@Cache Profile profile);
//...
class Profile {
private String email;
private boolean active;

public String toString(){
// all properties are used here
}
```
Thus if you need only 'active' property to build cache key then first approach wouldn't work.
Second approach is that Spring provides, namely [Cacheable ](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/cache/annotation/Cacheable.html) annotation, for example:
```java
@HystrixCommand
@Cacheable(key="{  #profile?.active}")
User getUserByParams(Profile profile);
```
But this approach requires to have some library to work with EL, such as SpringEL and etc.

What approach looks better for you? WDYT ?

**Comment by dmgcodevil** [comment]
I finished with implementation. You can take a look at this [test](https://github.com/dmgcodevil/Hystrix/blob/iss380/hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/cache/Jsr107CacheTest.java). Just put your comments here if you have any points or objections. I will wait for it for a while before I make pull request. Thanks.

**Comment by davidkarlsen** [comment]
What caching feature in hystrix are you referring to? https://github.com/Netflix/Hystrix doesn't seem to mention one?

**Comment by dmgcodevil** [comment]
https://github.com/Netflix/Hystrix/wiki/How-To-Use#request-cache

**Comment by dmgcodevil** [comment]
Variant with jsr107 looks very complicated for current goals and I decided to add custom annotations that look like jsr107 but have only required properties.
