### ISSUE TITLE
Dashboard: Dynamically Determine Scale of Circle Radius

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/Hystrix#45]
Right now the circles are hardcoded to size themselves within a domain of 0-400rps. 

They should instead dynamically set this domain to a floor/ceiling derived from the data being streamed -- or at least be easily configurable if that doesn't work well.

**Comment by mattrjacobs** [comment]
Closing this out due to inactivity.  If someone would like to take ownership of the dashboard roadmap, please re-open.
