### ISSUE TITLE
[hystrix-contrib/hystrix-clj] Are there objections to going to clojure 1.6.0

### ISSUE THREAD

**Issue by rspieldenner** [Netflix/Hystrix#468]
While updating the build plugin to use a viable version of clojuresque I'm getting 

    Exception in thread "main" java.io.FileNotFoundException: Could not locate clojure/edn__init.class or clojure/edn.clj on classpath

Moving to `org.clojure:clojure:1.6.0` fixes the issue

**Comment by daveray** [comment]
How about `1.5.1`? hystrix-clj will work fine with that version and it also has `clojure.edn`.

**Comment by mattrjacobs** [comment]
Looks like hystrix-clj is properly referring to ```1.5.1```.
