### ISSUE TITLE
onRunSuccess/onThreadComplete hooks called in timeout flow

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#510]
In 1.3.x, under thread isolation, when a HystrixCommand times out, the ```onRunSuccess```/```onThreadComplete``` hooks are invoked by the Hystrix thread eventually, even if the calling thread has already moved through the fallback flow.

In master/1.4, only the ```onThreadComplete``` hook is invoked (eventually).  

/cc @benjchristensen, @KoltonAndrus What should the semantics be?  I'd like to decide that and then enforce it in both 1.3.x and master

**Comment by benjchristensen** [comment]
I think it should call eventually whenever it does complete. A thread always ends (unless it's an infinite loop). 

It is clearer for it to eventually be called than to have cases where it only starts but never "ends". Also I don't want to break 1.3 behavior.

**Comment by mattrjacobs** [comment]
Yeah, that's the way I was leaning, but didn't want to bias your response :)  This will be a change in master only then.  I'll also add some Javadoc to clarify this case, as it's not obvious.

**Comment by mattrjacobs** [comment]
Added Javadoc in #512
