### ISSUE TITLE
Rolling Metric for Max Concurrent Requests

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/Hystrix#54]
We already have this for thread executions but it would be good to have for the command in general (thread or semaphore isolated).

The value of this is in tracking down bursts. Even though we are generally tracking metrics at the second or subsecond level the concurrent bursts at the millisecond level can be missed and make it hard to determine where rejections are coming from.

**Comment by mattrjacobs** [comment]
Addressed by #667
