### ISSUE TITLE
Wiki spam

### ISSUE THREAD

**Issue by hgschmie** [Netflix/Hystrix#545]
you may want to clean that out: e.g. https://github.com/Netflix/Hystrix/wiki/Service-air-panas-081291315510--

**Comment by mattrjacobs** [comment]
Deleted.  Thanks @hgschmie

**Comment by hgschmie** [comment]
Uhm, that was just an example. There are ~200 additional pages that look the same....

**Comment by mattrjacobs** [comment]
Think I got them this time.
