### ISSUE TITLE
Hystrix Dashboard is not showing up Rejected count

### ISSUE THREAD

**Issue by ramkarna** [Netflix/Hystrix#574]
Hi,
Hystrix Dashboard is not showing up rejected count, though the hystrix stream json response has rejected count. We are tried Hystrix Dashboard version hystrix-dashboard-1.3.18 and hystrix-dashboard-1.4.0-RC5. We tried deploying on Tomcat 8 
![untitled](https://cloud.githubusercontent.com/assets/10726012/5919818/5b19d0ce-a605-11e4-9ad3-5817260fd41c.jpg)
and Liberty profile.
Hystrix Stream output:
{"type":"HystrixCommand","name":"operation","group":"WebService","currentTime":1422043075322,"isCircuitBreakerOpen":false,"errorPercentage":5,"errorCount":2,"requestCount":39,"rollingCountCollapsedRequests":0,"rollingCountExceptionsThrown":2,
"rollingCountFailure":0,"rollingCountFallbackFailure":0,"rollingCountFallbackRejection":0,"rollingCountFallbackSuccess":0,"rollingCountResponsesFromCache":0,"rollingCountSemaphoreRejected":2,"rollingCountShortCircuited":0,"rollingCountSuccess":37,"rollingCountThreadPoolRejected":0,"rollingCountTimeout":0,"currentConcurrentExecutionCount":0,"latencyExecute_mean":115,"latencyExecute":{"0":85,"25":106,"50":114,"75":124,"90":133,"95":138,"99":188,"99.5":190,"100":191},"latencyTotal_mean":116,"latencyTotal":{"0":85,"25":106,"50":115,"75":124,"90":133,"95":138,"99":188,"99.5":190,"100":191},"propertyValue_circuitBreakerRequestVolumeThreshold":20,"propertyValue_circuitBreakerSleepWindowInMilliseconds":5000,"propertyValue_circuitBreakerErrorThresholdPercentage":75,"propertyValue_circuitBreakerForceOpen":false,"propertyValue_circuitBreakerForceClosed":false,"propertyValue_circuitBreakerEnabled":true,"propertyValue_executionIsolationStrategy":"SEMAPHORE","propertyValue_executionIsolationThreadTimeoutInMilliseconds":1000,"propertyValue_executionIsolationThreadInterruptOnTimeout":true,"propertyValue_executionIsolationThreadPoolKeyOverride":null,"propertyValue_executionIsolationSemaphoreMaxConcurrentRequests":1,"propertyValue_fallbackIsolationSemaphoreMaxConcurrentRequests":1,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":10000,"propertyValue_requestCacheEnabled":true,"propertyValue_requestLogEnabled":true,"reportingHosts":1}

Please let us know the solution if any.

**Comment by mattrjacobs** [comment]
I'll take a look, @ramkarna

**Comment by dsukner** [comment]
Have the same problem. Is there a soution?

**Comment by mattrjacobs** [comment]
@ramkarna / @dsukner I'm focusing on getting the command internals working before focusing on the dashboard.  In all likelihood, I will try to get an RC out with just internal changes so that I can get testing started on that before I turn my attention to the dashboard.  I'm happy to review any changes you make, though.

**Comment by ramkarna** [comment]
Is failure types like SHORTCIRCUIT, REJECTED_SEMAPHORE_EXECUTION are treating as an errors?

**Comment by ramkarna** [comment]
In hystrixCircuit.html rejected count displaying only for THREAD strategy.
<% if(propertyValue_executionIsolationStrategy == 'THREAD') { %>
				<a href="javascript://" title="Timed-out Request Count" class="line tooltip timeout"><%= addCommas(rollingCountTimeout) %></a>
				<a href="javascript://" title="Threadpool Rejected Request Count" class="line tooltip rejected"><%= addCommas(rollingCountThreadPoolRejected) %></a>
			<% } %>
If you add the below code then it will fix the issue and rejected count will show it up for SEMAPHORE
			<% if(propertyValue_executionIsolationStrategy == 'SEMAPHORE') { %>
				<a href="javascript://" title="Threadpool Rejected Request Count" class="line tooltip rejected"><%= addCommas(rollingCountSemaphoreRejected) %></a>
			<% } %>

**Comment by mattrjacobs** [comment]
Thanks for investigating, @ramkarna.  Once I get around to the dashboard set of tasks, I'll include your change

**Comment by mattrjacobs** [comment]
I believe this is fixed in #728.  @ramkarna / @dsukner - Can you confirm this looks the way you expect?

**Comment by ramkarna** [comment]
Sure will take a look at it and confirm.

**Comment by ramkarna** [comment]
Fix is working.
