### ISSUE TITLE
Remove Yammer metrics from hystrix-contrib?

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#575]
From what I can tell, the Yammer metrics library is no longer maintained and has been superseded by both the CodaHale and DropWizard metrics libraries.  @fkjellberg / @benjchristensen - any objection to removal of this module?

**Comment by benjchristensen** [comment]
I don't know enough about it to comment. Does it cost us anything to maintain it for backwards compatibility for people using it still?

**Comment by mattrjacobs** [comment]
It doesn't have to cost anything if we stop adding new features to it (like collapser metrics as in #576).
