### ISSUE TITLE
Dashboard: Detail View

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/Hystrix#59]
Add detail view (didn't make it from internal Netflix build to opensource version yet) that contains:

- current properties and realtime view of when they change across cluster
- other metrics that don't show on the summary
- hooks into historical datasources for line graphs of various metrics
   - need to determine the right way to provide this hook that is abstract yet simple to make work
- per instance view to help isolating if an issue is happening on all instances or just some
   - a prototype of a visualization for displaying a large cluster of instances in a single place is here: http://bl.ocks.org/1488375 (I played with it a full year ago and haven't yet gotten to implementing it)

**Comment by mattrjacobs** [comment]
Closing this out due to inactivity.  If someone would like to take ownership of the dashboard roadmap, please re-open.
