### ISSUE TITLE
Remove duplicate Jenkins builders

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#605]
Currently there are 2 Jenkins builds firing.  One of them always fails, as it has an old version of Java7 that plays poorly with PowerMock.  We should delete that Jenkins build

**Comment by mattrjacobs** [comment]
@quidryan / @rspieldenner are you able to remove this Jenkins build: https://netflixoss.ci.cloudbees.com/job/Hystrix-pull-requests/ ?

**Comment by quidryan** [comment]
@mattrjacobs When you're logged into CloudBees, do you see the "Delete Project" link?

**Comment by mattrjacobs** [comment]
When I attempt to login, it uses some SSO logic and determines I'm not a member of netflixoss.

**Comment by quidryan** [comment]
You should be able to log using just your email, no password, then get sent
to OneLogin. Once in there, you'll be logged into CloudBees. Then access
netflixoss.ci.cloudbees.com, and click login AGAIN. Can you drop by today?

**Comment by mattrjacobs** [comment]
I got @benjchristensen's help on this
