### ISSUE TITLE
hystrix-dashboard: Publish single executable JAR distribution

### ISSUE THREAD

**Issue by mhurne** [Netflix/Hystrix#606]
It'd be nice if there were a hystrix-dashboard distribution in the form of a single executable JAR file (à la Dropwizard, Spring Boot, Ratpack, etc). That would allow folks to get the dashboard up in running without having to install a container such as Tomcat first.

https://github.com/commercehub-oss/jvmboost might be a good fit for this. This would be a particular way of taking the "embedded Jetty app with existing code" approach.

Other ideas that have been proposed:
* Port to embedded Netty
* Port to Ratpack
* Eliminate the need to run the dashboard by relying on CORS. I believe this has been decided against as it would exclude older browsers. It would also require the addition of one or more CORS-related headers to existing Hystrix stream deployments.

We want to continue providing a WAR distribution as well.

**Comment by mattrjacobs** [comment]
I'm certainly open to this.  At the moment, my highest priority is getting all of the blockers to a 1.4.0 release complete, but I can evaluate all of the options you proposed once that's done.  I took a look at the jvmboost docs, and if it's as simple as adding some gradle config and a YAML config file, that seems pretty tractable.

**Comment by benjchristensen** [comment]
:+1: on a modernized executable jar solution. The simplest solution right now would be the embedded Jetty app, but I'm open to the other ideas as well.

**Comment by mattnelson** [comment]
I have been using jetty runner for hystrix and turbine.

https://wiki.eclipse.org/Jetty/Howto/Using_Jetty_Runner

**Comment by spencergibb** [comment]
[Spring Cloud](https://github.com/spring-cloud/spring-cloud-netflix) uses spring-boot which takes care of the embedded jetty for you.

**Comment by mattrjacobs** [comment]
@mhurne / @mattnelson / @spencergibb Any interest in submitting a PR for this?  I haven't had time to get to it yet.  I still think this is valuable addition, but this is not my area of expertise.

**Comment by mattrjacobs** [comment]
Closing this out due to inactivity.  If someone would like to take ownership of the dashboard roadmap, please re-open.
