### ISSUE TITLE
Deprecate execution.isolation.thread.timeoutInMIlliseconds property name in favor of execution.timeoutInMilliseconds

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#673]
Given change in #664, make sure that both styles of naming the timeout property work, and setting both chooses the new-style

**Comment by mattrjacobs** [comment]
I still want to do this feature, but the revert in #675 makes it not critical for 1.4.0.  Will push to 1.4.x

**Comment by dmak** [comment]
`closed` = the new property will not get into master? Or is it already in 2.0.x branch?

**Comment by mattrjacobs** [comment]
Both properties are in master.  2.x branch is not active at this point

**Comment by dmak** [comment]
@mattrjacobs  As far as I can see the original commit 60e47c17ff246b06a851f20643272352e08fb258 was reverted by a2c5112356e69fead98ae28f9cf5ab47e7543967 on 15 Feb 2015. The code in master reads the property `execution.isolation.thread.timeoutInMilliseconds`, see [`HystrixCommandProperties:123`](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java#L123). Please forgive me if I have missed something... maybe you could point me the line where `execution.timeoutInMilliseconds` property is read? Thanks!

**Comment by mattrjacobs** [comment]
@dmak Apologies - you are correct.  The property is only configurable via the key `execution.isolation.thread.timeoutInMilliseconds` in master.

**Comment by dmak** [comment]
Then the questions is still opened: in what Hystrix version will this fix be available?

**Comment by mattrjacobs** [comment]
As of right now, no one is working on it.

**Comment by dmak** [comment]
Then this ticket should be re-opened, because the support of `execution.timeoutInMilliseconds` property is not applied.
