### ISSUE TITLE
HystrixRequestContext to implement java.lang.AutoCloseable

### ISSUE THREAD

**Issue by ikolomiets** [Netflix/Hystrix#708]
Any plans? Its usage pattern prompts for Java 7 try-with-resources.

**Comment by mattrjacobs** [comment]
Yes, good idea.  I'll get to this in one of the upcoming releases

**Comment by mattrjacobs** [comment]
Switched back to Java 6 (see #722 ).  Will hold off on this until I have firmed up a better migration plan for Java

**Comment by mattrjacobs** [comment]
Merged into 2.0.x branch in #1175
