### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by luan-cestari** [Netflix/Hystrix#714]
The wiki page https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds should be updated with the information about 1.4.x (https://github.com/Netflix/Hystrix/blob/master/CHANGELOG.md) (in summary, timeout now applies for semaphores as well). I would also recommend to rename that property (as it mislead to think it only applies to thread isolation as it used to be)

**Comment by DavidMGross** [comment]
I've fixed the wiki description, but am leaving the issue open to consider the renaming proposal.

**Comment by luan-cestari** [comment]
Thanks @DavidMGross

**Comment by mattrjacobs** [comment]
@luan-cestari I agree on the naming.  I've already got an open issue to deprecate the old name and move Hystrix consumers to the new name here: #673

**Comment by luan-cestari** [comment]
@mattrjacobs cool =) So we can close this issue (as teh wiki is updated and there is already an issue for the renaming ) right?

Thank you very much guys, it was awesome work you guys did creating and maintaining Hystrix. Also, thank you very much for the fast reply and consideration of the issue opened by someone which is not part of the team =)

Let me know if I can help with a minor issue or something else.

**Comment by infomaven** [comment]
I've enjoyed following all the discussions on this topic. Learned a lot of new things about Hystrix. 
Thanks for your diligence and attention to detail on this task. I'm sure it will help lots of people!


Date: Wed, 25 Mar 2015 19:21:55 -0700
