### ISSUE TITLE
Does Hystrix 1.4 still support a java 6 runtime environment?

### ISSUE THREAD

**Issue by dsukner** [Netflix/Hystrix#722]
Does Hystrix 1.4.x still support a java 6 runtime environment?

**Comment by mattrjacobs** [comment]
Not as of 1.4.0.  It's now Java 7+

**Comment by dsukner** [comment]
Is there no plan to make available it Java 6 compatible? I'm sure there are many users of Hystrix that are still on Java 6 and could really use the new features such as Semaphore timeout capability as well as any bug fixes. Please strongly consider that.

**Comment by mattrjacobs** [comment]
Given that Java 6 was EOLed 2 years ago, I'd strongly prefer to move forward through Java versions.  

Is there anything special about your case that requires Java 6?   Any dependencies which I should be aware of that prevent you from moving forward?

**Comment by mattrjacobs** [comment]
Also, more generally, if anyone has a strong desire for staying on Java 6, it would be very helpful to hear from you about what your reasons for that are.

**Comment by rhart** [comment]
I'm using Hystrix with an app running on Websphere 8.5 and we've just come across this problem too.  Whilst it is possible to upgrade the Java version to 7, it's an optional feature and we can't use it just yet.  I think with 8.0 it's not even optional, you're stuck with 6.

**Comment by dsukner** [comment]
Our environment is on Websphere 8 with no upgrade planned in the near term.
So we are stuck on java 6. I would not be surprised if many Hystrix users
are in a similar situation where for one reason or another an immediate
java version update is just not feasible.

**Comment by mattrjacobs** [comment]
OK, that sounds reasonable enough.  Thanks for the explanation.  

We don't get any real mileage out of JDK 7, though it would make #372 harder to implement, so the downside is fairly small.  I do want to target JDK8 at some point.  Will try and 

I'll get to work on targetting Hystrix 1.4.3 to JDK 6.

**Comment by dsukner** [comment]
That's great, thanks!

**Comment by mattrjacobs** [comment]
Code is merged.  Will go through the docs tomorrow to make sure everything is up-to-date with this change and then release 1.4.3.

**Comment by mattrjacobs** [comment]
This is now released in 1.4.3.  Can you give it a try and confirm that I've released it properly?

**Comment by rhart** [comment]
Awesome, many thanks!

Will take it for a spin soon as poss. Thanks again

**Comment by mattrjacobs** [comment]
Using javap, I see that these classfiles are major:50, minor:0 (JDK6), so this looks done to me.

Classfile /Users/mjacobs/debug/validate-jdk6/com/netflix/hystrix/Hystrix.class
  Last modified Mar 27, 2015; size 3471 bytes
  MD5 checksum 5585031e2abcc1f6283bfb75372b9c6f
  Compiled from "Hystrix.java"
public class com.netflix.hystrix.Hystrix
  minor version: 0
  major version: 50
