### ISSUE TITLE
Add command-level flag to disable timeouts

### ISSUE THREAD

**Issue by vitalatron** [Netflix/Hystrix#737]
After updating to the last hystrix version I found that synchronous semaphore-isolated commands are affected by the ``hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds`` property.
Is there a way to disable timeout for such commands if it's not a bug?

**Comment by mattrjacobs** [comment]
@vitalatron - This is indeed a new feature of Hystrix 1.4.x.  

There's not a specific setting to disable the timeout, though of course you can set the timeout value as arbitrarily high as you'd like.

There are already settings per-command representing boolean enabled flags for other Hystrix features (request log, request cache, circuit-breaker, fallback), so I think it makes sense to add a flag for timeout as well.

I'll update the title of the issue to add this flag and then use it in command invocation.

**Comment by mattrjacobs** [comment]
Added in #742
