### ISSUE TITLE
HysterixCommandProperties.Setter().withExecutionIsolationThreadTimeoutInMilliseconds deprecated with no reason given and still used in the documentation

### ISSUE THREAD

**Issue by darklajid** [Netflix/Hystrix#740]
See the title.

I got some code that uses Hystrix, containing 

`super(Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("SomeKey"))
                .andCommandKey(HystrixCommandKey.Factory.asKey("AnotherKey" + Integer.toString(myTimeout)))
                .andCommandPropertiesDefaults(HystrixCommandProperties.Setter()
                        .withExecutionIsolationThreadTimeoutInMilliseconds(myTimeout)));
`

and I get compilation warnings with 1.4.3 about the last line calling a deprecated `withExecutionIsolationThreadTimeoutInMilliseconds`.

Sure enough, the javadocs have a deprecated tag. But no reason given and I wouldn't know if that code should be migrated to something else (what?).

It doesn't help that docs in the wiki still reference that method at least in one place:
https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.strategy

Should the configuration example be changed? Could you add a `@deprecated` JavaDoc comment to point people like me to a reason/migration path?

**Comment by mattrjacobs** [comment]
Thanks for the report, @darklajid .  The deprecation was intentional.  I'll get the documentation cleaned up.

**Comment by mattrjacobs** [comment]
Just added: https://github.com/Netflix/Hystrix/wiki/Configuration#execution.timeout.enabled

**Comment by mattrjacobs** [comment]
Just removed all references to this method in the Wiki

**Comment by mattrjacobs** [comment]
Just uploaded Javadoc in #744.

**Comment by darklajid** [comment]
Hey. Thanks for the quick turnaround. Not trying to hijack this bug, but it's the ~same~ javadoc subject.

HysterixCommandProperties.Setter has this example in the javadocs, for the class (i.e. right at the top of https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/HystrixCommandProperties.Setter.html

`HystrixCommandProperties.Setter()
           .setExecutionTimeoutInMilliseconds(100)
           .setExecuteCommandOnSeparateThread(true);
`

Can't find those. Could that need a s/setE/withE/ perhaps?

**Comment by mattrjacobs** [comment]
Yes, you're right.  Will get that fixed and re-uploaded.  Thanks for the
catch!

**Comment by mattrjacobs** [comment]
I just reuploaded in #747.  Can you take a look and see if you find any further issues?  I'd appreciate that.

**Comment by mattrjacobs** [comment]
I just reuploaded in #756 to fix the HystrixThreadPoolProperties.Setter s/with/set issue.

If you spot more Javadoc inconsistencies, please keep pointing them out.  It absolutely helps the project.

Is it OK to close this issue now, and any other Javadoc issues can get opened as a new issue?

**Comment by mattrjacobs** [comment]
Closing.  If there are further Javadoc issues, please open a new issue
