### ISSUE TITLE
HystrixCircuitBreakerImpl isOpen can return false incorrectly

### ISSUE THREAD

**Issue by mswintermeyer** [Netflix/Hystrix#745]
At the end of the method, after the `compareAndSet`, it should always be `return true`. `compareAndSet` sets the value to the given updated value if the current value == the expected value. If the method returns false, it means that the current value is *already* true, which means the circuit is open (another thread got here first in a race) and we should return true.

**Comment by mattrjacobs** [comment]
Thanks for the report @mswintermeyer , I'll look into it

**Comment by mattrjacobs** [comment]
Yes, I agree with your fix.  Nice catch!  I'm getting a PR ready right now...
