### ISSUE TITLE
hystrix-metrics-event-stream uses org.codehaus.jackson

### ISSUE THREAD

**Issue by piefel** [Netflix/Hystrix#761]
`org.codehaus.jackson:jackson-core-asl` is the old version of Jackson, currently (rather, forever) at 1.9.2.

The real current version is 2.5.0 and has a new group id `com.fasterxml.jackson.core`; also, some classes moved around.

**Comment by mattrjacobs** [comment]
Thanks for the report @piefel .  Fixed in #763
