### ISSUE TITLE
Why can't I force open a circuit breaker at runtime?

### ISSUE THREAD

**Issue by MrThomasWagner** [Netflix/Hystrix#766]
It would be really nice to be able to force a circuit breaker open at runtime (for example in an MBean).  This way if the properties set at start-up end up not working out, I can force open the circuit without having to do a restart. (Assuming a restart is less desirable than falling back on some service request.  For example: during peak hours).

What is the reason this isn't enabled? There seems to be a hacky way to achieve this but nothing out of the api.

I think it would be really cool if you could force open a breaker and do a rolling restart to pick up a better set of properties.

Edit: words.

**Comment by benjchristensen** [comment]
You can force it open or closed with dynamic properties. This has been possible since v1.0. 

No restarts are needed. The properties are dynamic for everything except max thread pool size (I believe only one needing a restart) which should never be modified anyways.

**Comment by MrThomasWagner** [comment]
Ok my mistake. Thank you.

**Comment by mattrjacobs** [comment]
This is the property: https://github.com/Netflix/Hystrix/wiki/Configuration#circuitBreaker.forceOpen
