### ISSUE TITLE
Can you provide a way to set the HystrixProperty at runtime for a HystrixCommand?

### ISSUE THREAD

**Issue by rajiv-shringi-A1** [Netflix/Hystrix#777]
The way we configure @HystrixCommand is 

    @HystrixCommand( commandProperties = {
        @HystrixProperty(name = "circuitBreaker.requestVolumeThreshold", value = "100"),
        @HystrixProperty(name = "circuitBreaker.sleepWindowInMilliseconds", value = "10000")}
      )

The annotation attribute values have to be compile time constants. However, I want these properties to be configurable with the ability to change them at runtime. How would we achieve such a setup if we are using @HystrixCommand?

**Comment by mattrjacobs** [comment]
Hystrix uses Archaius for dynamic configuration.  See https://github.com/Netflix/Hystrix/wiki/Configuration#introduction and https://github.com/Netflix/archaius/wiki/Overview

**Comment by rajiv-shringi-A1** [comment]
Got it. I can use this to configure.

    ConfigurationManager.getConfigInstance().setProperty(...)

**Comment by BlackRider97** [comment]
I am defining command with some configuration defined in constructor like below 
```
    public static class GetBlockList extends HystrixCommand<Set<String>>{

		String msisdn;

		private static final Setter cachedSetter = 
				Setter
				.withGroupKey(HystrixCommandGroupKey.Factory.asKey(HYSTRIX_COMMAND_GROUP_KEY))
				.andCommandPropertiesDefaults(HystrixCommandProperties.Setter()
						.withExecutionIsolationStrategy(ExecutionIsolationStrategy.SEMAPHORE)
						.withExecutionTimeoutEnabled(false)
						.withExecutionIsolationSemaphoreMaxConcurrentRequests(50)
						.withFallbackEnabled(false)
						.withCircuitBreakerEnabled(true)
						.withRequestCacheEnabled(false));

		public GetBlockList(String msisdn) throws HikeException {
			super(HYSTRIX_ZK_CONFIG_PATH, cachedSetter);
			this.msisdn = msisdn;
		}

		@Override
		protected Set<String> run() throws Exception {
                        return null;
                }
	}
```
then I am dynamically updating configurations reading from some file path
using following line
```
ConfigurationManager.getConfigInstance().setProperty("hystrix.command.GetBlockListount.execution.isolation.semaphore.maxConcurrentRequests ", 1000);
```
But I have observed that it is not update to `1000` while it remained same as defined in constructor. According to doc it should be updated as it has higher precedence.

```
        <dependency>
            <groupId>com.netflix.hystrix</groupId>
            <artifactId>hystrix-core</artifactId>
            <version>1.5.9</version>
        </dependency>
```
