### ISSUE TITLE
Dashboard displays error percentages above 100% when command shares name with thread pool

### ISSUE THREAD

**Issue by genshapiro** [Netflix/Hystrix#792]
![dashboard snapshot](https://cloud.githubusercontent.com/assets/12349330/7638455/f3a7745e-fa42-11e4-8dad-ce145044a605.jpg)

Dashboard displays error rates well above 100%...can this be explained or is this a bug?
Thanks

**Comment by mattrjacobs** [comment]
A lot of those numbers look incorrect.  If it's possible, could you attempt to downgrade Hystrix to 1.4.6 (core/metrics-stream/dashboard) and see if the issue exists there.  I made a recent change that swapped out our implementation of latency data.  I haven't personally reproduced this issue, but if you are able to with 1.4.7 and not with 1.4.6, then that is very useful info for me.

**Comment by genshapiro** [comment]
we are on 1.3.18. Unfortunatelly, we cannot nimbly move between versions in out environment.

Another question came up - is this simply faulty reporting or could it possibly affect circut breaker decision logic?
Thanks

**Comment by mattrjacobs** [comment]
Thanks for the version info - that rules out a class of errors.

Are you able to share some of your raw metrics data that the dashboard is consuming?

**Comment by mattrjacobs** [comment]
Also, is this data being processed by Turbine, or is it coming directly from a single metrics stream?

**Comment by genshapiro** [comment]
Apologies for late response. Yes, we are using Turbine. Also, what we noticed was if Command name is identical to Thread Pool Key name this issue occurs. We do see good dashboard stats in cases where command name is different from that of pool key. Thats an observation.
We are trying to collect more data now.

Thanks

**Comment by mattrjacobs** [comment]
@genshapiro See this comment for one possible solution: https://github.com/Netflix/Hystrix/issues/703#issuecomment-112785989.

**Comment by genshapiro** [comment]
FYI - what we found in our settings was Dashboard was getting confused when command name and thread pool name were the same. As soon as the one of them was renamed the issue resolved itself and Dashboard displayed reasonable stats.

**Comment by mattrjacobs** [comment]
Thanks for the follow-up, @genshapiro.  I'm changing the title of this Issue to reflect your findings.
