### ISSUE TITLE
Thread Pool sizes do not seem right

### ISSUE THREAD

**Issue by genshapiro** [Netflix/Hystrix#793]
![thread pools](https://cloud.githubusercontent.com/assets/12349330/7640836/a5c73eb6-fa53-11e4-8fe1-94ded5b16224.png)

Version 1.3.18

This also seems wrong...we configure pool sizes consistently with low numbers. The dashboard seems to display arbitrary, very high pool size numbers. Does this look like an issue? Would that be an indication of pools actually sizing incorrecly or simply a case of misreporting?

Thanks

**Comment by mattrjacobs** [comment]
@genshapiro I must have accidentally overlooked this when you initially reported this.  Is this still an issue for you?

**Comment by mattrjacobs** [comment]
Closing due to age.  Please re-open if you'd like to continue the discussion
