### ISSUE TITLE
Can't define overload functions in hystrix-clj

### ISSUE THREAD

**Issue by killme2008** [Netflix/Hystrix#811]
As below example:

```clj
(defcommand hello ([] (hello 1)) ([n] (str "hello," n)))
(hello)
CompilerException java.lang.ClassCastException: clojure.lang.PersistentList cannot be cast to clojure.lang.IPersistentVector, compiling:(/private/var/folders/90/xwqqy61d6lg6v8ztpbfhwb5c0000gp/T/form-init8537870057202438788.clj:1:9) 
(hello "dennis")
CompilerException java.lang.ClassCastException: clojure.lang.PersistentList cannot be cast to clojure.lang.IPersistentVector, compiling:(/private/var/folders/90/xwqqy61d6lg6v8ztpbfhwb5c0000gp/T/form-init8537870057202438788.clj:1:9) 
```

**Comment by killme2008** [comment]
It seems that the problem is in `: arglists` in command metadata is not correct for overload functions.

I created a PR to fix this issue

https://github.com/Netflix/Hystrix/pull/812

Hope it can be merged into master and release a new hystrix-clj version ASAP,thanks.

**Comment by mattrjacobs** [comment]
I will release a new Hystrix by end-of-day for this (and a few other small issues)

**Comment by killme2008** [comment]
@mattrjacobs Thanks a lot.

**Comment by killme2008** [comment]
@mattrjacobs  Did you released a new version of hystrix ? We are waiting for this fix.

**Comment by mattrjacobs** [comment]
Yes, it's in 1.4.11. I haven't typed up the release notes yet.

On Jun 11, 2015, at 10:55 PM, dennis zhuang <notifications@github.com>
wrote:

@mattrjacobs <https://github.com/mattrjacobs> Did you released a new
version of hystrix ? We are waiting for this fix.

—
Reply to this email directly or view it on GitHub
<https://github.com/Netflix/Hystrix/issues/811#issuecomment-111368734>.

**Comment by killme2008** [comment]
@mattrjacobs  Cool, thanks. I upgrade it right now.

**Comment by mattrjacobs** [comment]
Release notes complete now: https://github.com/Netflix/Hystrix/releases/tag/v1.4.11.
