### ISSUE TITLE
How to pass threadpool parameters to HystrixObservableCommand

### ISSUE THREAD

**Issue by PK85** [Netflix/Hystrix#819]
Hello,

we has changed default isolation semapthore of HystrixObservableCommand to thread pool, but HystrixObservableCommand.Setter has no ability to set Setter#threadPoolPropertiesDefaults.

Is that missing functionality in Setter, or I should do that in different way?

Cheers, Piotr

**Comment by mattrjacobs** [comment]
I believe this is a duplicate of #805.  See @benjchristensen's comment: https://github.com/Netflix/Hystrix/issues/805#issuecomment-109371037.

After digesting that, is this still a feature you would like?

**Comment by PK85** [comment]
Nope, comments from #805 helped me to understand my needs.

Thank you and have a nice day.
