### ISSUE TITLE
Renewal of HystrixCommandProperties information reported by HystrixCommandMetrics

### ISSUE THREAD

**Issue by TheTweak** [Netflix/Hystrix#822]
I have a simple custom HystrixPropertiesStrategy that maintains properties cache with time-based eviction, but when some property changes, it is not propagated to HystrixCommandMetric. I haven't found any plugin (tried HystrixMetricsPublisher) setup that allows to invalidate HystrixCommandMetric too.
Hystrix version is `1.3.19`

**Comment by mattrjacobs** [comment]
I'm not 100% sure I understand your use case here.  Are you saying that you want a properties strategy which has a TTL on properties?  

When a HystrixCommand gets constructed (in both 1.3 and 1.4), the properties are retrieved through the HystrixPropertiesStrategy layer of indirection.  So you should be able to model any sort of property algorithm you'd like with a custom HystrixPropertiesStrategy.

I'm not sure what the metrics publishing has to do with properties.

**Comment by TheTweak** [comment]
My problem is that after I've implemented TTL on properties using custom HystrixPropertiesStrategy, and when properties are changed, this change is not propagated to HystrixCommandMetrics because HystrixCommandMetrics get properties once it is created, and it cannot be changed.

**Comment by mattrjacobs** [comment]
I'm pursuing a way to create custom HystrixCommandMetrics instances in #843.  This should be possible once that change is done and released

**Comment by TheTweak** [comment]
Ok, cool, closing it with reference to #843.
