### ISSUE TITLE
Javanica: How to get similar functionality to vanilla HystrixCommand#getFailedExecutionException() within the fallback method when using hystrix-javanica?

### ISSUE THREAD

**Issue by mariusneo** [Netflix/Hystrix#828]
I'm trying to integrate hystrix-javanica into my project and I have the issue that I don't see within the fallback methods the exceptions which occur within the methods performing remote calls.

In vanilla Hystrix, this can be done via HystrixCommand#getFailedExecutionException().
Can you point out in the documentation how to achieve a similar functionality within fallback methods for hystrix-javanica @HystrixCommand annotated methods?

Thanks in advance.

**Comment by mariusneo** [comment]
I've found in the meantime 

```java
public Link defaultDogeLink(Account account) {
     LOG.warn("exception occured while building doge link for account " + account, getCommand().getFailedExecutionException());
     return null;
}

@HystrixCommand(fallbackMethod = "defaultDogeLink")
public Link buildDogeLink(Account account) {
     // some code that may throw Runtime Exceptions
}  


private com.netflix.hystrix.HystrixInvokableInfo<?> getCommand() {
    return HystrixRequestLog.getCurrentRequest().getAllExecutedCommands().iterator().next();
}
```

Is there a better way to do this?

**Comment by mattrjacobs** [comment]
@dmgcodevil Is there any facility for this in hystrix-javanica?

**Comment by mattrjacobs** [comment]
@dmgcodevil Can you take a look at this?

**Comment by dmgcodevil** [comment]
Yes. I'll take a look

**Comment by dmgcodevil** [comment]
Hi @mariusneo, if I got your question correctly so you're asking how you can get exception thrown within command in fallback method. If yes, then there is no such ability in javanica , but I can suggest a solutions to solve this problem: 
1. You can use solution that you have mentioned in your comment, but I can't say that this approach is save and durable, so you can ask @mattrjacobs as far as it is correct.
2. We can support two signatures for fallback method, one with the same as command method signature and seconds with an additional parameter:

```java
public Link defaultDogeLink(Account account, Exception e) {
     LOG.warn("exception occured while building doge link for account " + account, e);
     return null;
}
```

Exception arg is derived and comes from getFailedExecutionException()

WDYT ?

**Comment by mariusneo** [comment]
Hi @dmgcodevil I think the 2nd option you've mentioned seems easy enough to be grasped by any developer new to the framework.

**Comment by mattrjacobs** [comment]
@mariusneo / @ dmgcodevil  The solution presented above suffers from a race condition.  The HystrixRequestLog get's written to by all threads in a request, so it's not guaranteed that any lookup against it's contents is exactly the command instance you're interested in.

The API itself it stable and at very low risk of changing, but it may not return the data you're interested in.

**Comment by dmgcodevil** [comment]
@mattrjacobs thanks, then we're going to implement second solution.

**Comment by dmgcodevil** [comment]
@mattrjacobs hi, go ahead to close it
