### ISSUE TITLE
Build failure :(

### ISSUE THREAD

**Issue by TJMshaisa** [Netflix/Hystrix#829]
C:\Users\Lebo\Documents\GitHub\Hystrix\hystrix-examples-webapp [master]> ../gradlew jettyRun
[Fatal Error] httpcore-4.2.4.pom:2:1: Content is not allowed in prolog.
[Fatal Error] httpcore-4.2.4.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'hystrix'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.apache.httpcomponents:httpcore:4.2.4.
     Required by:
         :hystrix:unspecified > com.netflix.nebula:gradle-netflixoss-project-plugin:2.2.5 > com.netflix.nebula:gradle-in
fo-plugin:2.0.0 > org.eclipse.jgit:org.eclipse.jgit:3.3.2.201404171909-r > org.apache.httpcomponents:httpclient:4.2.5
      > Could not parse POM https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.pom
         > Content is not allowed in prolog.
      > Could not parse POM http://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.pom
         > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 25.491 secs

**Comment by mattrjacobs** [comment]
Thanks for the report, @TJMshaisa.  Sorry for the delay responding - was out of the country on vacation and just got back.  

I haven't seen this failure before, and building the head of master (with Java 7 on a Macbook Pro) works as expected for me.  Are you still able to consistently replicate this failure?

**Comment by mattrjacobs** [comment]
Pleas open a new issue if you can reproduce this, @TJMshaisa

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://nikwatch.com/cast.php?kp64>

 

arnon@moscona.com

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://majorinvesting.com/being.php?bp>

 

arnon@moscona.com

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://saolucasnatal.com.br/fond.php?jr6pm>

 

arnon@moscona.com

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://antistatikzeminkaplama.com/I.php?hw>

 

arnon@moscona.com

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://mhpearls.com/voice.php?v5>

 

arnon@moscona.com

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://mannyaniceto.com/determined.php?x9x>

 

arnon@moscona.com
