### ISSUE TITLE
incorrect use of Clojure :arglists metadata?

### ISSUE THREAD

**Issue by stuarthalloway** [Netflix/Hystrix#831]
The proposed fix to Clojure bug http://dev.clojure.org/jira/browse/CLJ-1232 appears to break hystrix-clj, which (if the ticket comments are correct) uses arglists metadata in a way different from the Clojure compiler.

At first glance this seems to be a bug in hystrix-clj that will become breaking once http://dev.clojure.org/jira/browse/CLJ-1232 is applied.  Looking for input/context before we do that.

**Comment by benjchristensen** [comment]
Thanks @stuarthalloway for the heads up on this.

@daveray Can you help look into this?

**Comment by daveray** [comment]
Sorry for the slow response. Vacation + sickness. I'll take a look this week.

**Comment by mattrjacobs** [comment]
@daveray Are you still able to take a look?

**Comment by daveray** [comment]
Hi. @stuarthalloway there's a proposed fix here: https://github.com/daveray/Hystrix/commit/11d5baddb5e393f24346975628ea698176a9396b
The only reason for the generated `:arglists` was to make `(doc command)` look nice. Hope this helps. Sorry about the delay.

**Comment by mattrjacobs** [comment]
Thanks @daveray.  I don't know enough Clojure to evaluate the fix - are you comfortable with me merging and releasing, or would you prefer to wait until some validation can be done?

**Comment by daveray** [comment]
@mattrjacobs I'm comfortable with merge and release.

**Comment by mattrjacobs** [comment]
Merged in #852
