### ISSUE TITLE
How to save the Dashboard Data Permanently

### ISSUE THREAD

**Issue by RajeshSamson** [Netflix/Hystrix#832]
Hi,
I'm newbie to this hystrix. I was successfully able to use the hystrix command in my project. I just want to know is there any way to permanently save the hystrix dashboard data.

Thanks and Regards

**Comment by benjchristensen** [comment]
There are two approaches:

1) Subscribe to and persist the realtime stream in something like Kafka (though I'm not aware of anyone doing this).
2) Use a MetricsPublisher (https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#metrics-publisher) to publish metrics. This is the expected approach to persisting metrics for historical records.
