### ISSUE TITLE
Backpressure sensitivity of cache() in Hystrix

### ISSUE THREAD

**Issue by akarnokd** [Netflix/Hystrix#833]
I've recently implemented backpressure in RxJava's `cache()` operator which unfortunately failed in Netfix' canary environment: threads got accumulated over time probably due to hangs in the downstream. I've also run Hystrix' unit test with 1.0.13RC and everything passed.

I've looked at the `AbstractCommand` but it looks complicated and I don't really see what is subscribing to the cached Observable that could hang.  The addition of backpressure causes the operator to not send any values unless requested; if there is a downstream operator that forgets to request, it will hang (previously, it just got the next value). The second change is that cache replays its buffer live instead of accumulating a synchronous source first, causing changes in timing of the value delivery.

**Comment by mattrjacobs** [comment]
Thanks for the report, @akarnokd.  Sorry for the delay in responding - was out of the country on vacation and just got back.  I will investigate and pick up the relevant context from @benjchristensen and @abersnaze.

**Comment by mattrjacobs** [comment]
To add some more context to this thread, the initial change to RxJava was https://github.com/ReactiveX/RxJava/pull/2969.  It was canaried in a release candidate in: https://github.com/ReactiveX/RxJava/issues/3076.  The revert was done here: https://github.com/ReactiveX/RxJava/pull/3081

**Comment by mattrjacobs** [comment]
This was not an issue with Hystrix.  I don't know the precise issue that manifested in the Netflix internal canary, but it was resolved without a Hystrix change
