### ISSUE TITLE
Impossible to reset executionIsolationSemaphoreMaxConcurrentRequests

### ISSUE THREAD

**Issue by Illapikov** [Netflix/Hystrix#834]
Hello,
I'm creating new HystrixCommand for each request and each time specifying it's parameters like executionIsolationSemaphoreMaxConcurrentRequests.

If I do this firstly:
```
new HystrixCommand<FetchData<Double>>(
                HystrixCommand.Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey(HYSTRIX_GROUP_KEY))
                        .andCommandKey(HystrixCommandKey.Factory.asKey(HYSTRIX_COMMAND_NAME))
                        .andCommandPropertiesDefaults(HystrixCommandProperties.Setter()
                                .withExecutionIsolationStrategy(ExecutionIsolationStrategy.SEMAPHORE)
                                .withExecutionIsolationSemaphoreMaxConcurrentRequests(1)));
```
and then this:
```
new HystrixCommand<FetchData<Double>>(
                HystrixCommand.Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey(HYSTRIX_GROUP_KEY))
                        .andCommandKey(HystrixCommandKey.Factory.asKey(HYSTRIX_COMMAND_NAME))
                        .andCommandPropertiesDefaults(HystrixCommandProperties.Setter()
                                .withExecutionIsolationStrategy(ExecutionIsolationStrategy.SEMAPHORE)
                                .withExecutionIsolationSemaphoreMaxConcurrentRequests(2)));
```

as a result I will only have command with MaxConcurrentRequests == 1, which is not expected.

Thanks, Sergey

**Comment by mattrjacobs** [comment]
@Illapikov Thanks for the question - it's a good one.  

The reason this works in this manner is that the HystrixCommandProperties for a command are cached per-HystrixCommandKey.  That means that the first set of properties a command gets configured with will be used throughout the applications lifecycle (or until `Hystrix.reset()` is called).

This design was chosen to make understanding and reasoning about the system as straightforward as possible.  Basically, simplicity is favored over flexibility.  The gain is that all commands in a running system with the same command key share the same config.  That means we can use the command key as a good identifier for metrics/system behavior.  There's no need to add more dimensions than command key to understand how a command is configured.  The cost, as you mentioned, is that reconfiguration attempts fail (and somewhat silently).  

Do you have any recommendations on additions/changes to documentation that might make this more clear?

**Comment by Illapikov** [comment]
@mattrjacobs Thanks for the answer.

But I did Hystrix.reset() before each creation of HystrixCommand. And I think this isn't expected behaviour.

**Comment by mattrjacobs** [comment]
OK, that helps narrow it down.  I'll attempt to reproduce your findings with a unit test and report back.

**Comment by mattrjacobs** [comment]
@Illapikov There was a commented-out test case in HystrixTest covering this specific case.  See #280 as well.  The scenario you described looks to work as expected in the unit test.  

Is there anything you would change in the unit test that can reproduce your issue?

**Comment by mattrjacobs** [comment]
@Illapikov AFAICT this works as expected.  Please re-open with a way to reproduce if you're still seeing this issue
