### ISSUE TITLE
Add documentation to GLOBAL scope in HystrixCollapser

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#842]
Ran into an issue where HystrixCollapser with GLOBAL scope was used and HystrixRequestContext was incorrect.

At a minimum, I need to add documentation of this option.

After reviewing the code, I will likely need to make changes to how GLOBAL collapsing works w.r.t. request state. My guess is that the first thread to submit work to a GLOBAL collapser attaches its request  context for the duration of the JVM.  Will confirm and then suggest a fix.

**Comment by khawes** [comment]
Yikes !  I would think a global anything would have exactly no request
context. :)

-- Keith
_____________________________________________________
Don’t listen to me, I play with Christmas lights
<http://www.christmasoutloud.com/> all year long.

**Comment by mattrjacobs** [comment]
Added GLOBAL/REQUEST discussion to Wiki here: https://github.com/Netflix/Hystrix/wiki/How-To-Use#request-collapsing

**Comment by mattrjacobs** [comment]
There are valid usecases where a batch command may be created with multiple HystrixRequestContexts, so I don't want to remove HystrixRequestContext from a globally-scoped collapser.  However, this option may NOT be used when the batch command is unaware of the work is has to do to create a new HystrixRequestContext out of multiple constituent HystrixRequestContexts.

Does this sound right?
