### ISSUE TITLE
java.util.concurrent.RejectedExecutionException with fallback disabled

### ISSUE THREAD

**Issue by FlavioF** [Netflix/Hystrix#845]
Hi,

I need help understanding an exception.

I am running a HystrixCommand with fallback disabled and I am making **a request each 5 seconds**.
My Hystrix Command configuration is:
```
circuitBreakerSleepWindowInMilliseconds - 15000
circuitBreakerRequestVolumeThreshold - 2
executionTimeoutInMilliseconds - 1000
```

If the request isn't failing everything works ok. However when the requests starts to fail it happens:

```
1 & 2 request - Response Timeout
3, 4, 5 request - Response Short Circuited
6 request - Response Timeout
...
n request (after 10 response timeouts) - instead of Response Timeout I got this error <java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1c25a43b rejected from java.util.concurrent.ThreadPoolExecutor@125f04cb[Running, pool size = 10, active threads = 10, queued tasks = 0, completed tasks = 68]
n+1 - no more Response Timeout but RejectedExecutionException (why?) or Response Short Circuited (as expected).
```

If the request stop failing everything works as expected again.

I understand it all, I just can't understand why the RejectedExecutionException since with only one request each 5 seconds it should have all the 10 threads available.

Is it a normal behavior? Why?

Thanks,
Flávio Ferreira

**Comment by mattrjacobs** [comment]
The error message suggests that there are 10 active threads in the Hystrix thread pool.  You stated that the Hystrix timeout is 1000ms.  That causes the caller thread to walk away after 1000ms, but doesn't necessarily cause the work to stop of the underlying Hystrix thread.

This config property allows you to attempt an interruption of a Hystrix thread in the event of a timeout: https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.interruptOnTimeout.
Java doesn't allow you to force-interrupt, so this is best-effort.  It's probably worth creating a thread dump to see what work is keeping your thread-pool busy.

**Comment by FlavioF** [comment]
Thanks for the clarification @mattrjacobs.
I'm closing this issue now.
