### ISSUE TITLE
Hystrix and Apache HttpClient timeout setting

### ISSUE THREAD

**Issue by billyy** [Netflix/Hystrix#858]
Does anyone have good recommendation for Hystrix timeout and Apache HttpClient timeout?   Making them the same could be problematic if Hystrix is timeout before Apache HttpClient timeout?   I can always make the Hystrix timeout longer, but then by how much?   Does it make sense to set Apache HttpClient timeout to 1 seconds and Hystrix to 2 seconds?

**Comment by mattrjacobs** [comment]
It's a decision that only your app can make.  If you want Hystrix to manage cleaning up the HttpClient and its state, then make the Hystrix timeout shorter.  If you want your own code (in the HystrixCommand's run() method) to handle the cleanup, then make the Hystrix timeout longer.

It's likely you can do better than Hystrix, which just interrupts the IO thread, but either choice is valid.

If you do choose to have network timeouts fire first, then note that those failures will look like FAILUREs to Hystrix (and not TIMEOUTs).  If your system gets very backed up and the time it takes for the thread to get scheduled exceeds (HystrixTimeout - NetworkTimeout), only then would you see TIMEOUTs.

**Comment by billyy** [comment]
OK.  Thanks.   That's in line with what I am thinking.

If I want to do my own clean up and use the Http Client timeout, then should I just simply use Semaphore instead of thread pool?    What is the purpose of Hystrix thread pool here if I am able to "walk away" with the http Client?    That's the part I am struggling with.

**Comment by billyy** [comment]
Matt,

In this situation, I am really trying to understanding whether I should use ThreadPool or Semaphore.  Any insight will be greatly helpful.  Thanks.

**Comment by mattrjacobs** [comment]
If you put your blocking I/O call on a caller thread, then that caller thread cannot make forward progress until the I/O is complete.  The I/O call may also not gracefully exit, leaving your calling thread completely consumed.

As a rule of thumb, you should always put blocking I/O calls in thread-isolated commands.

**Comment by billyy** [comment]
Thanks for the reminder of the blocking I/O and the benefit of using Hystrix Thread pool to make it non-blocking.   That really helps!
