### ISSUE TITLE
Which is the 3rd level of precedence?

### ISSUE THREAD

**Issue by taringamberini** [Netflix/Hystrix#863]
At [this point](https://github.com/Netflix/Hystrix/wiki/Configuration#introduction) in the documentation there's written:

> 1.Global default from code
> 
> This is the default if none of the following 3 are set.

but after that point there is only 2 and 4:

> 2.Dynamic global default property
> 4.Dynamic instance property

Which is the 3rd level of precedence?

Thanks,
Tarin

**Comment by DavidMGross** [comment]
The #3 heading got removed during an edit a long while back.  I did some
digging and restored it.

On Wed, Aug 19, 2015 at 3:30 AM, Tàrin Gamberìni <notifications@github.com>
wrote:

> At this point
> <https://github.com/Netflix/Hystrix/wiki/Configuration#introduction> in
> the documentation there's written:
>
>
>    1. Global default from code
>
> This is the default if none of the following 3 are set.
>
> but after that point there is only 2 and 4:
>
>
>    1. Dynamic global default property
>    2. Dynamic instance property
>
> Which is the 3rd level of precedence?
>
> Thanks,
> Tarin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Netflix/Hystrix/issues/863>.
>



-- 
David M. Gross
PLP Consulting

**Comment by taringamberini** [comment]
Thank you very much,
Tarin

**Comment by taringamberini** [comment]
I've seen that:

    super(Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("ExampleGroup"))
            .andCommandPropertiesDefaults(HystrixCommandProperties.Setter()
                   .withExecutionTimeoutInMilliseconds(500)));

could be simplified by the overloaded constructor:

    super(HystrixCommandGroupKey.Factory.asKey("ExampleGroup"), 500);

If I was right could that overloaded constructor be used in the documentation to simplify it?

**Comment by mattrjacobs** [comment]
Good catch, @taringamberini.  I added that convenience constructor to solve cases just like this and never changed the docs.  Will take a pass through and make that type of update
