### ISSUE TITLE
ttl on hystrix cache

### ISSUE THREAD

**Issue by peb73** [Netflix/Hystrix#864]
Hello,

I'm new on hystrix and i try to make a TTL cache on a command. Have you got any **smart** idea how to do that ?

I tried to use a spring scheduler to clear cache, but hystrix don't expose all couple key/value.

tx for the answer,
Pierre-Emmanuel

ps : Thanks for this  tools ;-), hystrix rocks

**Comment by mattrjacobs** [comment]
@peb73 What's the problem you're trying to solve via the addition of a TTL cache?

Hystrix does have a per-request cache that can ensure a single command runs per cache-key (thereby de-duplicating work).  See https://github.com/Netflix/Hystrix/wiki/How-To-Use#request-cache for more details.

**Comment by peb73** [comment]
@mattrjacobs thx fot you answer.
I use a command to call a REST API (with feign), and i think that use hystrix request-cache could be a good thing to reduce service call.
But i need that this cache has a lifetime.

My first idea was to clean regularly the per-cache key map...

For the moment i'm using a mongodb cache.

**Comment by mattrjacobs** [comment]
@peb73 What you're describing is more of an application-level concern.  Hystrix only caches for the duration of the request, and is generally agnostic about what happens in a command execution.

A good pattern we often see is 1 HystrixCommand for a cache lookup, 1 command for a Network call.
Application logic checks the cache via the CacheCommand.  If found, you're done.  If not, then the NetworkCommand may be invoked.  Both may then be tuned separately to protect against errors/latency on either the cache or remote server.

**Comment by mattrjacobs** [comment]
@peb73 I don't see anything to add to the Hystrix library here.  Please re-open if you'd like to discuss further.

**Comment by follettdevelopment** [comment]
I was just looking for something similar.  We have a back-end service that gets hit thousands of times a minute.  We are looking at using Hystrix in the client calling this back-end system.  The data might change hourly.  I was wondering how to leverage the Hystrix cache to reduce calls, but clear/purge it after 15 minutes or so.  I will continue the search.

**Comment by gpthome** [comment]
I was just looking for something similar. We have a back-end service that gets hit thousands of times a minute. We are looking at using Hystrix in the client calling this back-end system. The data might change hourly. I was wondering how to leverage the Hystrix cache to reduce calls, but clear/purge it after 15 minutes or so. I will continue the search.

**Comment by jiacai2050** [comment]
@gpthome I think what you need is redis/memcached. The cache of hystrix command is accessible during the lifecycle of a request, to be exactly, inside a HystrixRequestContext
