### ISSUE TITLE
strategy for tuning the hystrix configuration

### ISSUE THREAD

**Issue by igorsechyn** [Netflix/Hystrix#866]
Hello,

first of all thank you for a great tool. I have recently started writing microservices for NodeJs and was searching for something similar in javascript. Although there are some options, none of them seemed to be complete or met my requirements. So I started an attempt of porting Hystrix to javascript and am trying to introduce it into our nodejs services and eventually into java services as well. One of the most frequent questions I get, is how to find the best configuration for commands in terms of timeouts, thresholds, etc... Is there some strategy behind it? Or is it just observing the behaviour in production and tuning the config based on the results?

Thanks a lot, Igor.

P.S. if you guys are interested in the js lib, it can be found here https://bitbucket.org/igor_sechyn/hystrixjs/overview. I would love to have some feedback.

**Comment by mattrjacobs** [comment]
That's great, @igorsechyn !  I'll check out the HystrixJs port.

The specific question you asked is a good one (and common for us as well).  This just came up in https://github.com/Netflix/Hystrix/issues/862#issuecomment-133481740, so please check out the answer I gave there.  Also, please see #131 for even more context.

I believe that there is more that can be done to solve this problem, but at the end of the day, it will always require some production data to accurately tune.  Taking threadpool sizing as an example, without knowing the distribution of threadpool and queue utilization and the number of rejected tasks, you're left with a guess-and-check approach that walks through config space until you reach an optimal point.  However, if you had those, you could very straightforwardly choose a desired % of thread pool rejections, then look at your distribution to find the proper sizing.

You should see some Github activity around metrics like those coming soon from me.

Also, as you productize your library and get experience with production traffic/tuning, any insights you can offer would be very welcome.

**Comment by igorsechyn** [comment]
Thank you for a quick reply, @mattrjacobs. Those are really interesting topics, will definitely spend some time digging myself into it.

Will definitely post some feedback as soon as we have more insights. 

cheers, Igor.
