### ISSUE TITLE
Question about number and percentile buckets

### ISSUE THREAD

**Issue by pgrinchenko** [Netflix/Hystrix#87]
We are building a Zabbix plugin to perform snapshotting our Hystrix command metrics every 1 minute. I am trying to figure out best configuration in terms of the following properties:

hystrix.command.default.metrics.rollingStats.timeInMilliseconds = 60000
hystrix.command.default.metrics.rollingStats.numBuckets = 60;

hystrix.command.default.metrics.rollingPercentile.timeInMilliseconds = 60000
hystrix.command.default.metrics.rollingPercentile.numBuckets = 60;

Should it be 60000/60 or am I mis-calculating something? Should I make it wider than 1 minute to make metrics/counters more precise.

**Comment by titojoseph** [comment]
Hi,
We have already integrated Hystrix with JMX.Need to perform snapshotting our Hystrix command metrics every 1 second. Provided below configuration properties to achieve the same

hystrix.command.default.metrics.rollingStats.timeInMilliseconds = 1000;
hystrix.command.default.metrics.rollingStats.numBuckets = 10;

That will keep all RollingNumbers (counters) for 1000ms (1 sec) in .01 second increment (1000ms /10 == 100ms).

At any point in time when you request a metric it will give you the count for last 1 second (100ms*10) with the bucket rotating each 0.01 second.. But the metrics getting refreshed only in default 10 seconds, not the custom set 1 second window. Could you please advice.
