### ISSUE TITLE
Hystrix Dashboard to monitor a REST Service

### ISSUE THREAD

**Issue by vaibhavthapliyal** [Netflix/Hystrix#878]
Hi,
I have an existing REST API which I ported to Hystrix recently. I did so by replacing each method with its corresponding Hystrix command. The business logic is represented in resource classes which form the dependencies for other applications. Now I want to monitor this whole system using the Hystrix-Dashboard ie monitor these individual dependencies. How can I perform this?

Thanks 
Vaibhav

**Comment by mattrjacobs** [comment]
This Wiki page describes how to get your dashboard up and running: https://github.com/Netflix/Hystrix/wiki/Dashboard.  Please feel free to suggest/make improvements to that doc if you have any.

**Comment by vaibhavthapliyal** [comment]
Thanks for your reply.

I was able to get this running by using the Rx-Netty-metrics-stream module. I used it within my Resource classes in the Rest API to send regular server sent events having Hystrix metrics to a URL which I monitored via the Hystrix Dashboard.

However if you could provide an example about using the Rx-Netty-metrics-stream within the doc, it would be helpful.

Thanks
Vaibhav

**Comment by mattrjacobs** [comment]
Glad to hear it worked.  I'll look at adding this to docs shortly.  If you're willing, contributing your setup experience via a PR would be valuable - I've never personally set up the RxNetty stream

**Comment by muralivaranasi2009** [comment]
https://github.com/Netflix/Hystrix/wiki/Dashboard. I am not able to find anything here.. can you help me for dashboard to Spring Rest Application

**Comment by vaibhavthapliyal** [comment]
@muralivaranasi2009 You could check the spring cloud netflix module. Here's something that might get you started. https://cloud.spring.io/spring-cloud-netflix/single/spring-cloud-netflix.html
