### ISSUE TITLE
Missing null check in HystrixCacheKeyGenerator creates a NullPointerException.

### ISSUE THREAD

**Issue by fredboutin** [Netflix/Hystrix#894]
When no @CacheKey are specified, a NullPointerException occurs. A null check on cachekey should be added here : https://github.com/Netflix/Hystrix/blob/1.4.x/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/cache/HystrixCacheKeyGenerator.java#L61

**Comment by mattrjacobs** [comment]
Thanks for the report.  Do you have any interest in submitting a pull request?  If not, I can get to this sometime shortly?

**Comment by fredboutin** [comment]
Pull request sent!

**Comment by mattrjacobs** [comment]
Thanks @fredboutin

**Comment by proccyboy** [comment]
Fuck off let's see you find this email address / like a fucking gohst you
thick fucker ps you are being tracked for sim card data theft you tit lol
