### ISSUE TITLE
Hystrix 1.4.15 not available on Maven Central

### ISSUE THREAD

**Issue by chrisgray** [Netflix/Hystrix#898]
Hystrix 1.4.15 release looks to be cut, but it's not available on Maven Central (search.maven.org)

**Comment by mattrjacobs** [comment]
Thanks for the report, @chrisgray .  I didn't change anything about the release process, so don't know what happened yet.  I'll investigate.

**Comment by mattrjacobs** [comment]
Problem also exists on Bintray: https://bintray.com/bintray/jcenter/com.netflix.hystrix%3Ahystrix-core/view.  Will get both resolved ASAP

**Comment by chrisgray** [comment]
Thanks for the quick turnaround!

**Comment by mattrjacobs** [comment]
This is now fixed and both download links on https://github.com/Netflix/Hystrix/releases/tag/v1.4.15 now work
