### ISSUE TITLE
Enable Hystrix Dashboard to monitor multiple independent applications

### ISSUE THREAD

**Issue by sasrin** [Netflix/Hystrix#906]
Came across a use case where we needed to monitor more than one microservice using Hystrix Dashboard. So I ended up with a modified dashboard code to support the use case. If we think that it would be useful for everyone, I would be happy to submit a pull request.

https://github.com/sasrin/Hystrix/commit/338b765c06dd31df7afda6483d3708b1e08aca38

<img width="1416" alt="Hystrix Dashboard with multiple applications" src="https://cloud.githubusercontent.com/assets/9708004/10036592/751d4310-615e-11e5-9bf6-3b81a2b55bfd.png">

**Comment by mattrjacobs** [comment]
@sasrin Thanks for the idea!  

Does this imply that you've got multiple services running on the same machine that's hosting the dashboard?

**Comment by sasrin** [comment]
> Does this imply that you've got multiple services running on the same machine that's hosting the dashboard?

On a local testing environment, we have multiple services running at different ports on the same machine as the Hystrix Dashboard. 

On a production environment, we run the services using its own host names and on its own physical or virtual machines. In addition to that, we have multiple application instances serving each of the services and load balancing the requests among those application instances.

Independent of how and where we run these applications and the dashboard, we would able to monitor all services using a single dashboard using hystrix streams or in the case of clustered applications instances using turbine streams.

For quick reference, the modified dashboard home page would look as below:

<img width="882" alt="Modified Hystrix Dashboard" src="https://cloud.githubusercontent.com/assets/9708004/10092525/385010c6-62fc-11e5-9cac-2df0fcf9cb84.png">

**Comment by mattrjacobs** [comment]
Sure, I'm interested in how you put that together.  If you send a PR, I'll be happy to review it.  I think that if you keep the ability to view a dashboard for a single app, then any purely-additive change would not break any existing users (and probably make a few very happy)

**Comment by sasrin** [comment]
Thank you... will submit a pull request.

**Comment by sasrin** [comment]
Thanks for merging the pull request.
