### ISSUE TITLE
Future fallback for Async Hystrix Command

### ISSUE THREAD

**Issue by William-Woodhead** [Netflix/Hystrix#929]
When creating a method 

```
@HystrixCommand(fallbackMethod = "myFallback")
public Future<List<myType>> getSomethingAsync() { ...
```

with the fallback 
```
private Future<List<myType>> myFallback() { 
    return Futures.immediateFuture();
}
```

When calling .get() on the returned future from the fallback, it returned the future itself.

It seems that the fallback actually needs to be 
```
private List<myType> myFallback() { 
    return Collections.emptyList();
}
```

The method signature for the fallback needs to omit the future part.

However this is not documented? 

1. is this behaviour expected?
2. If so, can it be documented please?

**Comment by mattrjacobs** [comment]
@dmgcodevil Are you able to answer this?  I'm not sure the status of wrapping async work (like in `HystrixObservableCommand`) in `hystrix-javanica` is.

**Comment by dmgcodevil** [comment]
Hi, 
Actually there are two cases: fallback as regular method and a method annotated with ``` @HystrixCommand ```
Both cases aren't documented and I'll fix it for sure, but meantime let's consider each case.
1. Fallback as regular method. In this case I think fallback method return type should be a type that used as generic parameter in Future i.e.

```java 
@HystrixCommand(fallbackMethod = "myFallback")
public Future<List<myType>> getSomethingAsync() { ...
```
 fallback

```java
private List<myType> myFallback() { 
    return Collections.emptyList();
}
```

2. Fallback as command (marked with HystrixCommand annotataion). 
2.1 Fallback as sync command - works
2.2 Fallback as async command - doesn't work, throws ClassCastException. We need to support this case, I'll fix it once #907 is closed and merged back to master, I'm going to do it shortly.

**Comment by dmgcodevil** [comment]
@mattrjacobs, issue was solved and pr merged, so you can close it

**Comment by rdifrango** [comment]
In what version is this corrected as I'm running `1.4.23` [shown below] and it still returns a Future inside another future so I have to call the invoke method.

Here's the dependency:

```xml
<dependency>
	<groupId>com.netflix.hystrix</groupId>
	<artifactId>hystrix-javanica</artifactId>
	<version>1.4.23</version>
</dependency>
```

And our code

```java
@Override
@HystrixCommand(groupKey = "XmlTransactionThingsDao", commandKey = "retrieve", fallbackMethod = "retrieveAllByAccountId")
public Future<List<TransactionThing>> retrieveAllByAccountIdFailure(
		Context context, String accountId) {
	throw new ApiSystemException("retrieveAllByAccountIdFailure Failed on purpose");
}

@Override
@HystrixCommand(groupKey = "XmlTransactionThingsDao", commandKey = "retrieve")
public Future<List<TransactionThing>> retrieveAllByAccountId(
		Context context, String accountId) {
	logger.debug("In Thread Named {} with thread id {} and correlation id {}", Thread.currentThread().getName(),
			Thread.currentThread().getId(), EPFContextContainer.getContext().getCorrelationId());

	BankThingEntityCollectionResponse response = adaptor.readXml("AccountTransactionDetailData.xml");

	final Optional<BankThing> found = Iterables.tryFind(response.getEntries(), new AccountFinder(accountId));

	return new AsyncResult<List<TransactionThing>>() {
		@Override
		public List<TransactionThing> invoke() {
			if (found.isPresent()) {
				logger.debug("Transactions found: {}", found.get().getTransactions());
				return found.get().getTransactions();
			}
			else {
				logger.debug("No Transactions found");
				return Collections.EMPTY_LIST;
			}
		}
	};
}
```

**Comment by mattrjacobs** [comment]
@dmgcodevil Are you able to take a look at this?

**Comment by dmgcodevil** [comment]
Hi, I'm not aware about the procedure of releasing new versions and I'm not controlling what versions contain some changes of fixes. Your code should work fine, could you try 1.4.25 or later ?

**Comment by mattrjacobs** [comment]
Latest releases 1.4.26/1.5.2 should contain all relevant changes
