### ISSUE TITLE
The Application is Vulnerable to Open Redirect Vulnerability

### ISSUE THREAD

**Issue by theSupremeLord** [Netflix/Hystrix#961]
Hi,
I am a pen tester, and I have found that the application is vulnerable to open redirect.
https://HOST:PORT/ganglia/?c=<b>http://www.owasp.org/index.php/Open_redirect</b>&hc=4&m=load_one&mc=2&r=hour&s=by name

An attacker can you this vulnerability in order to redirect users to malicious sites without the user even realizing.

**Comment by mattrjacobs** [comment]
@theSupremeLord I need more context here to investigate.  Hystrix is a purely internal library.  Ganglia is not involved at all.  What role does Hystrix play in the URL above?

**Comment by theSupremeLord** [comment]
My mistake, thought it was related to Hystrix, now i understand that it is ganglia. 

Sorry..!
