### ISSUE TITLE
Missed setter methods in HystrixObservableCommand.Setter

### ISSUE THREAD

**Issue by dmgcodevil** [Netflix/Hystrix#966]
Hi, I've noticed that HystrixObservableCommand.Setter has the following fields
``` java
protected HystrixThreadPoolKey threadPoolKey;
protected HystrixThreadPoolProperties.Setter threadPoolPropertiesDefaults;
```

But this HystrixObservableCommand.Setter class doesn't have methods to set the fileds, is it expected behavior ?

Thanks

**Comment by mattrjacobs** [comment]
@dmgcodevil You're correct - those do not exist at the moment.  See the reasoning here: https://github.com/Netflix/Hystrix/issues/805#issuecomment-109371037

**Comment by dmgcodevil** [comment]
Thanks. Close this issue.
