### ISSUE TITLE
set servlet-api dependency provided

### ISSUE THREAD

**Issue by davidkarlsen** [Netflix/Hystrix#969]
hystrix-core drags in servlet-api 2.5 as a runtime dependency - maybe this should be set as provided as it is usually provided by container - and many may run v3.1 or 3.0

**Comment by mattrjacobs** [comment]
Which version are you pulling in?  When I look at 1.4.20, servlet-api is not directly referenced in the hystrix-core POM:

https://bintray.com/netflixoss/maven/Hystrix/1.4.20/#files/com/netflix/hystrix/hystrix-core/1.4.20

**Comment by davidkarlsen** [comment]
Sorry - I squinted a bit on mvn dependency:tree.
It is through http://repo1.maven.org/maven2/com/netflix/hystrix/hystrix-metrics-event-stream/1.4.20/hystrix-metrics-event-stream-1.4.20.pom and http://repo1.maven.org/maven2/com/netflix/hystrix/hystrix-request-servlet/1.4.20/hystrix-request-servlet-1.4.20.pom

**Comment by mattrjacobs** [comment]
OK got it.  I'll make that change for those 2 projects, that was an unintentional product of #944.  I'll leave `hystrix-core` alone, as that looks like it doesn't have the issue you described.

**Comment by mattrjacobs** [comment]
I think #972 should resolve this.
