### ISSUE TITLE
Hystrix without Archaius

### ISSUE THREAD

**Issue by tine2k** [Netflix/Hystrix#970]
I want to use hystrix (1.4.20) **without** the dependency to archaius. My goal is to not having to deploy the archaius-core.jar with my application as I dont want to deal with its depencies (like commons-lang etc.). As documented in the wiki, this should be possible by implementing a custom `HystrixPropertiesStrategy` and registering it by calling `HystrixPlugins.getInstance().registerPropertiesStrategy()`. Unfortunately, `HystrixPlugins` has a compile depency to archaius (`ConfigurationManager`) in the constructor:
```java
    private HystrixPlugins() {
        try {
            // Load configuration from hystrix-plugins.properties, if that file exists
            ConfigurationManager.loadCascadedPropertiesFromResources("hystrix-plugins");
        } catch (IOException e) {
            // fail silently
        }
    }
```

How I can use my custom `HystrixPropertiesStrategy` without having to deploy archaius-core.jar?

**Comment by everve** [comment]
+1 This is also a blocker for a lot of adoption I have in mind.


On Thu, Nov 12, 2015, at 01:29 AM, Martin Maier-Moessner wrote:
> I want to use hystrix (1.4.20) *without* the dependency to archaius.
> My goal is to not having to deploy the archaius-core.jar with my
> application as I dont want to deal with its depencies (like commons-
> lang etc.). As documented in the wiki, this should be possible by
> implementing a custom HystrixPropertiesStrategy and registering it by
> calling HystrixPlugins.getInstance().registerPropertiesStrategy().
> Unfortunately, HystrixPlugins has a compile depency to archaius
> (ConfigurationManager) in the constructor:


> private HystrixPlugins() {
        try {    // Load configuration from hystrix-plugins.properties,
        if that file exists ConfigurationManager.loadCascadedProperties-
        FromResources("hystrix-plugins"); } catch (IOException e) {
        // fail silently } }
> How I can use my custom HystrixPropertiesStrategy without having to
> deploy archaius-core.jar?


> — Reply to this email directly or view it on GitHub[1].


>


Links:

  1. https://github.com/Netflix/Hystrix/issues/970

**Comment by mattrjacobs** [comment]
Yeah, this will be going into Hystrix 2.0, and is the main reason for that major version bump.  I haven't started work on this yet, but I intend to get to it in the next month or so.

Agreed that this is a pain point.  See #252 for a bit more context
