### ISSUE TITLE
Throwable in extended fallback is null for timeouts

### ISSUE THREAD

**Issue by victormferrara** [Netflix/Hystrix#974]
Hi,

I've been using the extended fallbacks made in #828 (which are great) and I've seen that when the execution times out the Throwable is null as the execution didn't actually fail. It would be nice to have some kind of TimeoutException there to know the real reason and don't have to dead with nulls. Looking at the code, probably the same thing happens with rejected executions.

Thanks!

**Comment by mattrjacobs** [comment]
Is this specific to `hystrix-javanica`, or are you using Hystrix directly?

**Comment by victormferrara** [comment]
hystrix-javanica

**Comment by mattrjacobs** [comment]
@dmgcodevil Could you take a look at this one also, please?

**Comment by dmgcodevil** [comment]
Yes, I'll take a look

**Comment by dmgcodevil** [comment]
@mattrjacobs btw, it largely relates to hystrix core, to get exception javanica uses getFailedExecutionException(), do you have any clue why it returns null in the case of timeout error ?

**Comment by mattrjacobs** [comment]
Thanks for taking a look, @dmgcodevil.  I'll dive in and see what's happening in hystrix-core.

**Comment by dmgcodevil** [comment]
@mattjacobs, he is complaining because javanica passes null in extended
fallback method that is really annoying and can facilitate bogus code and I
agree with it. So the question is what we can do in order to avoid passing
null in fallback if a command fails because of timeout or rejected. I think
I can use the methods that you suggested and create exception with
corresponding text and pass it to fallback using additional argument. So
your answer helped, I guess

**Comment by victormferrara** [comment]
@mattrjacobs yeah, it's exactly what @dmgcodevil explained. Thanks!

**Comment by mattrjacobs** [comment]
`hystrix-core` itself is generating these Short-Circuit and Timeout exception instances.  Are we missing a feature where `hystrix-core` exposes these exceptions, so `javanica` does not need to?

**Comment by dmgcodevil** [comment]
@mattrjacobs it could be better if we had an abilitty to get such exceptions within a command

**Comment by mattrjacobs** [comment]
@dmgcodevil Agreed.  I just added #998 to add this to hystrix-core.  Once it's there, `hystrix-javanica` can leverage this.  Will note the PR in these comments so you can review

**Comment by mattrjacobs** [comment]
Now merged via #1008 / #1003

**Comment by mattrjacobs** [comment]
This should be fixed in #1167
