### ISSUE TITLE
Under high concurrency, timeouts not always firing

### ISSUE THREAD

**Issue by jojitj** [Netflix/Hystrix#985]
I have been playing with hystrix for sometime. 
My configurations as per our requirements is 
execution.isolation.thread.timeoutInMilliseconds is 50 millis
circuitBreaker.enabled is false, since our boss doesn't want the remote call to be skipped.
and then I have a fallback method too which should get triggered if ever the timeout is crossed.

hystrix.threadpool.default.coreSize is 50 since my concurrency for the outgoing call is around that.

I am using the javanica annotations. 
Also my annotated method is a Synchronous method, resulting in the HystrixCommand.execute() call.

My observation is, at low TPS, when the concurrency is below 10 or something it is good.
I put in some logs, and I could see that the below code in the AbstractCommand gets triggered 
            final Reference<TimerListener> tl = HystrixTimer.getInstance().addTimerListener(listener);
The Timer triggers at 50 millis  and everything is a happy flow, cutting off the remote call after 50 ms and falling back.

But when the TPS increases, the the Timer is not getting triggered everytime. It does work sometimes but not everytime. 
I am having a hard time understanding what is going wrong. One thing I observed is the ScheduledThreadPoolExecutor in HystrixTimer has a core size of 4, since my box is 4-core, but this need not be  trouble as I understand.

I was considering a future.get() based custom framework if I can't get this to work, since all I need is a timeout-cutoff-fallback framework. Let me know if any thoughts/paramters to be tuned.

**Comment by mattrjacobs** [comment]
Let me restate your problem to make sure I understand it:

You're saying that, under high concurrency, sometimes the timeout mechanism does not fire.  

Is that right?

**Comment by jojitj** [comment]
Yes. that is correct.

**Comment by mattrjacobs** [comment]
OK, I will see if I can reproduce.

**Comment by mattrjacobs** [comment]
I reproduced the problem in #990.  I'm working on understanding the root cause, then will fix the issue.  Thanks again for the report!

**Comment by jojitj** [comment]
Thank you. 
But I was wondering since Hystrix is already being used in Neflix prod, this level of concurrency is never needed? So what is the normal level of concurrency?

**Comment by mattrjacobs** [comment]
Here's a little bit more insight into the problem.  When a timeout gets registered on a command instance, under the covers that calls ScheduledThreadPoolExecutor.scheduleAtFixedRate with the timeout value as one of the arguments.

At this point, the command execution (either happening in a Hystrix thread pool if THREAD-isolated, or on the caller thread if SEMAPHORE-isolated) is racing the `HystrixTimer` thread.  If the command latency is close to the timeout value, then the non-determinism of thread-scheduling means that sometimes the command will return a value before the `HystrixTimer` thread delivers the `HystrixTimeoutException`.

When I adjust my test to have more difference between command latency and timeout value (100ms/3ms respectively), I'm seeing timeout fire 100% of the time, and not seeing any concurrency problems.

@jojitj Can you describe any differences your application has from this unit test?

**Comment by mattrjacobs** [comment]
I just pushed a commit to #990 with latency of 100ms, timeout of 3ms, 30 concurrent commands, 1000 trials, as described above.  When I avoid failing the test due to the thread race, I don't see any concurrency issues.

**Comment by jojitj** [comment]
My timeout value is 50 millis and when the command sometimes takes around 100ms+, and still the timeout will not get triggered. So I guess this is a slightly different 
I have put some logging in the hystrix code to demonstrate this. Shall I create a fork, and share the logs from my execution?

**Comment by mattrjacobs** [comment]
Yeah, that would be quite helpful.  Thanks

**Comment by jojitj** [comment]
I have put loggers in the HystrixTimer in my fork https://github.com/jojitj/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixTimer.java

**Comment by jojitj** [comment]
[HystrixTimerLogging.txt](https://github.com/Netflix/Hystrix/files/43119/HystrixTimerLogging.txt)

Attached is the log file.

**Comment by jojitj** [comment]
Thought of providing my conclusion. Due to GC pauses, Future.get(timeout) will not exit even after the timeout expires. It was confirmed in the same environment.

**Comment by mattrjacobs** [comment]
Thanks for providing that info, @jojitj .  If I'm understanding this, the sequence you observed was:

* Command started asynchronously
* GC pause started that lasted longer than Hystrix command timeout
* By the time GC pause was over, the timeout had no opportunity to fire "on time" since the HystrixTimer thread wasn't scheduled

It's not clear to me what the caller thread observed after the GC pause - could you provide that info?

**Comment by jojitj** [comment]
Yes. Your understanding is correct. 
Regarding the caller thread, I cannot fully confirm what exactly happens within Hystrix. 

I had missed to mention that I had created a Future.get(timeout)-based framework for the same use-case as I had mentioned in my first comment. In this framework the called thread will get the java.util.concurrent.TimeoutException after the GC pause. E.g., if my timeout is 50ms and the GC pause is for 500 ms, the 50ms Timeout occurs after the 500ms GC pause.

IIRC, if I use Hystrix, the Timer which is supposed to unsubscribe will not get triggered. In either case the timer will not act and the observer will not get unsubscribed and the caller thread continues for the full execution as if this was a fully syncronous invocation without hystrix.
