### ISSUE TITLE
ClasscastException on Observable Command Call

### ISSUE THREAD

**Issue by lukaseichler** [Netflix/Hystrix#987]
When I try to call a method that is annotated with `@HystrixCommand` and returns a `ObservableResult` I get the following exception:
 `java.lang.ClassCastException: rx.subjects.ReplaySubject cannot be cast to com.netflix.hystrix.contrib.javanica.command.ObservableResult`. 

Hystrix/javanic version: `1.4.21`
rxjava-Version: `1.0.14`
aspectJ-Version: `1.8.7``
WeavingMode: LoadTime

    @HystrixCommand
    public ObservableResult<Data> get(@NotNull final String id) {
        return new ObservableResult<Data>() {
            @Override
            public CarportData invoke() {
               return new Data();
            }
        };
    }

**Comment by dmgcodevil** [comment]
@lukaseichler there is open [issue](https://github.com/Netflix/Hystrix/issues/948) for it.
[PL](https://github.com/Netflix/Hystrix/pull/977) is going to be merged soon. Collapser for observable commands is one thing is left to do

**Comment by lukaseichler** [comment]
@dmgcodevil Thanks for the fast reply. This there a there a timeline for this?

I want to use javanic outside of Spring Cloud and it doesn't seem possible because of this issue and the ctw-jar not being available in maven central.

**Comment by dmgcodevil** [comment]
@lukaseichler you don't need ctw-jar if you're not using compile time weaving. PL with fix for observable is going to be close by the end of the week I guess (note it will not include collapser feature for observable  commands).

**Comment by dmgcodevil** [comment]
@lukaseichler please use >= 1.4.25 version, class cast error should go away.

**Comment by mattrjacobs** [comment]
This should be fixed now
