### ISSUE TITLE
hystrix-javanica:compileAjcJava cannot be built with Java 8

### ISSUE THREAD

**Issue by mattrjacobs** [Netflix/Hystrix#988]
Discovered in https://github.com/Netflix/Hystrix/issues/702#issuecomment-158264925.  

From a clean gradle cache, I see:

Download https://jcenter.bintray.com/org/aspectj/aspectjtools/1.7.4/aspectjtools-1.7.4.pom
Download https://jcenter.bintray.com/org/aspectj/aspectjtools/1.7.4/aspectjtools-1.7.4.jar
[ant:iajc] /Users/mjacobs/Projects/forks/Hystrix/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/MethodProvider.java [error] The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files
[ant:iajc] (no source information available)
[ant:iajc]
[ant:iajc] 1 error
:hystrix-javanica:compileAjcJava FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mjacobs/Projects/forks/Hystrix/hystrix-contrib/hystrix-javanica/build.gradle' line: 55

* What went wrong:
Execution failed for task ':hystrix-javanica:compileAjcJava'.
> compile errors: 1

**Comment by mattrjacobs** [comment]
@dmgcodevil Can you take a look at why Java8 is not building hystrix-javanica?

**Comment by dmgcodevil** [comment]
Moving to Java 8 ? Nice, nice.

**Comment by mattrjacobs** [comment]
To be clear, I'm not targetting Java8 yet.  That will come in 2.0.  But for some reason Java7 can build the tip of master but Java8 cannot.  That seems worth understanding ahead of the Java8 change to the Hystrix codebase.

**Comment by slobodanl** [comment]
Upgrade of  AspectJ version to aspectjVersion = '1.8.6' seems to correct the error above

**Comment by mattrjacobs** [comment]
Thanks @slobodanl !  Submitted #1009

**Comment by mattrjacobs** [comment]
Fixed in #1009
